gardenlinux/gardenlinux

tests/__main__.py, tests/_dev.py, tests/integration/gcp.py, tests/integration/sshclient.py, tests/integration/test_gardenlinux.py, tests/test_config.yaml
- authenticate using configured service account credentials
- create a compute instance using the configured image
- wait until it is reachable
- run integration tests
- delete the compute instance
=> Finish implementation of first GCP integration tests

hack/Dockerfile, hack/docker-compose.yml, hack/nginx.conf, hack/packages_debian, hack/readme-repo, hack/repo.sh, hack/reprepro/packages_debian, hack/reprepro/repo.sh, hack/reprepro/reprepro/conf/distributions, hack/reprepro/reprepro/conf/options, hack/reprepro/settings, hack/settings
Creating a Debian repository with Debian and custom packages.
Fixes #7 
=> adding the hack/repo

hack/libdb/Dockerfile, hack/libdb/libpam-modules.sh, hack/libdb/pam-remove-libdb.diff, hack/libdb/py37-remove-libdb.diff, hack/libdb/py37.sh, hack/libdb/py38-remove-libdb.diff, hack/libdb/py38.sh
We need to remove Berkley DB from certain packages.
Fixes #
=> Remove libdb from libpam-modules and python

ci/cicd.yaml, ci/glci/azure.py
Contains some final adjustments to the Azure image upload not included in the previous PR.
=> Finalize azure marketplace upload

bin/make-ali-ami, features/ali/file.include/etc/cloud/cloud.cfg.d/ds-identity.cfg, features/ali/pkg.include
Fix bootstrap issues on Alicloud
Fixes #53 
#52 
```improvement operator
```
=> Alicloud fix

features/ali/file.include/etc/systemd/timesyncd.conf
set ntp server for Alicloud
Fixes #
```improvement operator
```
=> set ntp server for Alicloud

logo/gardenlinux-logo-black-text.svg, logo/gardenlinux-logo-white-text.svg, logo/gardenlinuxio-black-text.svg, logo/gardenlinuxio-white-text.svg
- Logo with project name, text in black or white
- URL of gardenlinux.io home page, text in black or white
These are the images used for the gardenlinux t-shirt.
NONE
=> Logo images for gardenlinux t-shirt

build.yaml
add support for Alicloud
Fixes #
```improvement operator
```
=> add support for Alicloud

features/ali/image
Fixes #
```improvement operator
```
=> change makef.sh file path for Alicloud

Makefile, ci/cicd.yaml, ci/glci/alicloud.py, ci/glci/model.py, ci/promote.py, ci/requirements.txt, ci/tkn/model.py
Implements scripts to import image from S3 for Alicloud
Fixes #
```improvement operator
```
=> support image import for Alicloud

ci/glci/alicloud.py
fix bug of alicloud image upload
Fixes #
```improvement operator
```
=> fix bug of alicloud image upload

features/server/file.include/etc/default/grub.d/enable-swap-cgroup-accounting.cfg
Fixes #111 
```improvement user
Swap memory accounting is now enabled by default.
```
=> Enable swap cgroup accounting

ci/glci/az.py, ci/glci/azure.py, ci/glci/model.py, ci/promote.py, ci/requirements.txt
Same as https://github.com/gardenlinux/gardenlinux/pull/80 to different traget branch `main` .
```improvement operator
Enable automated publishing of gardenlinux images to Azure Marketplace.
```
=> Az marketplace improvements

ci/cicd.yaml, ci/glci/model.py, ci/glci/openstack_image.py, ci/promote.py, ci/requirements.txt
Same as https://github.com/gardenlinux/gardenlinux/pull/91 to different traget branch `main`.
```improvement operator
The OpenStack image upload procedure is now integrated.
```
=> Add OpenStack image build upload procedure

features/azure/exec.config
/platform azure
Enable verbose logging for waagent
Fixes #
```improvement operator
[Azure] Verbose logging is now enabled for the waagent.
```
=> [Azure] Enable verbose logging for waagent

.gitignore, ci/glci/alicloud.py, ci/promote.py
Provide remove images method for AliCloud
Fixes #
```improvement operator
```
=> clean alicloud image based on Image name

.ci/lib.sh
=> Switch config set used in pipeline

features/gardener/exec.config, features/gardener/pkg.include
This is needed as a workaround for https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970525 till the fix is delivered to the stream used by Garden Linux.
Fixes #
```improvement operator
```
=> Pin docker.io version to 19.03.13+dfsg1-2

features/server/exec.config
Fixes #
```improvement operator
```
=> missed one packages for python

Makefile, features/_dev/devkey.sh, features/server/test/rkhunter.conf, flavours.yaml
Fixes #
```improvement operator
```
=> small bugfixes

hack/kvmvirt.xml
Fixes #
```improvement operator
```
=> libvirt example

README.md
Fixes #
```improvement operator
```
=> just some typos

ci/requirements.txt
Signed-off-by: Christian Berendt <berendt@23technologies.cloud>
=> Update openstacksdk to 0.50.0

README.md
Fixes #108 
Fixes #151
I think I caught all of them. A more detailed description of which programs from the coreutils are used would be possible but too long.
=> More detailed requirement documentation.

features/openstack/image
Signed-off-by: Christian Berendt <berendt@23technologies.cloud>
=> Create qcow2 image when using the OpenStack builder

features/cloud/file.include/usr/share/pam-configs/garden, packages/defaults, packages/linux
Little things. But I think it is important to use the right name of the product everywhere.
=> Use "Garden Linux"

features/cloud/test/pam_faillock
=> PAM - typo in test

features/aws/exec.config, features/aws/file.include/usr/lib/dracut/modules.d/98gardenlinux/clocksource-setup.sh, features/cloud/file.include/usr/lib/dracut/modules.d/98gardenlinux/module-setup.sh
/kind bug
/area os
Fixes #
```bugfix operator
Fix aws ntp configuration
```
=> Aws ntp fix

features/_pxe/exec.config, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/any.conf, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-overlay-setup.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-sysroot-generator.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/module-setup.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/squash-mount-generator.sh
/kind TODO
/area os
Fixes #
```other operator
```
=> overlay for ignition

features/server/test/helpers, features/server/test/packages_musthave.chroot, features/server/test/rkhunter, features/server/test/rkhunter.chroot
Small fixes for the rkhunter and packages tests for the server feature.
=> Small test fixes

ci/build-task.yaml.template
/area os
Upgrade base image for build container to newer version to fix broken build in pipeline
=> add newer image to pipeline build job

features/azure/file.include/etc/cloud/cloud.cfg.d/91_azure_datasource.cfg
/kind TODO
/area os
Remove cloud-init leftover.
Fixes #
```other operator
Remove cloud-init leftover file.
```
=> Remove cloud-init leftover

bin/garden-init
/kind bug
/area os
Fixes #226 
```bugfix develloper
move declaration of tmp variable out of conditional (#226)
```
=> move declaration of tmp variable out of conditional

Makefile, bin/make-ec2-ami, features/ali/pkg.include
/kind TODO
/area os
Fix AWS build and upload a bit.
```other operator
Fix AWS build and upload.
```
=> Aws build fix

Makefile, bin/make-ec2-ami, features/ali/pkg.include, tests/Pipfile, tests/Pipfile.lock, tests/integration/aws.py
/kind TODO
/area os
Fixes #
```other operator
Fix tests for new security policies.
```
=> Integration test update

features/ali/exec.config, features/cloud/exec.config, features/gardener/exec.config
/kind TODO
/area os
Fixes #
```other operator
Add stable links to extra packages.
```
=> Rel 318 cleanup

VERSION
/area os
Prepare next dev version 318.9
Fixes #
```other operator
```
cc @gardenlinux/garden-linux-maintainers
=> Prepare next dev version 318.9

ignition/install.yaml
Feature
/area os
install script to write the ram disk to local disk, with UEFI and LEGACY (GRUB) support
=> add ignition/install.yaml

bin/garden-build.sh, build.sh
Add a docker volume for the artifacts. 
Store the build logs in the build directory.
Fixes #267 #268
=> Add docker volume for build (and logs)

docker/build-image/debootstrap.patch, packages/manual/dracut.d/noperl.patch
/kind doc
/area os
Adds some comments to package patches.
=> Annotate package patches

bin/garden-build.sh
/kind TODO
/area os
Fixes #
```feature user
```
=> keep the tar output for the pipelines

bin/garden-build.sh, ci/steps/build_image.sh, ci/steps/upload_results_step.py
/area os
FIx broken pipeline build after tar is not built any longer
Fixes #
=> Fix pipeline build

ci/glci/model.py, ci/glci/util.py, ci/render_pipeline_run.py, ci/render_pipelines.py, ci/render_pipelines_and_trigger_job, ci/render_task.py, ci/requirements.txt, ci/steps.py, ci/steps/pre_check_tests.py, ci/steps/run_tests.py, ci/steps/upload_test_results.py, ci/tasks.py, ci/test_cfg.yaml, integration_tests/ali/ali_test.py, integration_tests/ali/conftest.py, integration_tests/aws/aws_test.py, integration_tests/aws/conftest.py, integration_tests/aws/legacy_test.py, integration_tests/azure/azure_test.py, integration_tests/azure/conftest.py, integration_tests/conftest.py, integration_tests/gcp/conftest.py, integration_tests/gcp/gcp_test.py, integration_tests/openstack/conftest.py, integration_tests/openstack/openstack_test.py
/area os
Foundation for integration tests
NONE
=> Inttestmerge3

bin/.cicd-cli.py
/area os
improve command line tools for finding manifests
=> ci: improve command line tools for finding manifests

bin/azurewrapper.py, bin/garden-version, bin/make-azure-ami, docker/integration-test/Dockerfile, tests/Pipfile.lock, tests/integration/azure.py, tests/integration/test_gardenlinux.py, tests/run_full_test.py
/kind TODO
/area os
Fixes #
```feature user
```
=> Test development dirk

ci/glci/model.py, ci/steps/notify.py
/kind TODO
/area os
small fixes in ci
=> ci: small typo-like fixes

features/azure/exec.config
/kind bug
/area os
Fixes #107
```feature user
Fixes Problem where Azure VMs cannot resolve its own hostname 
```
=> Fixes Problem where Azure VMs cannot resolve its own hostname 

bin/.cicd-cli.py
/kind TODO
/area os
allows to download log files or build artifacts from S3
=> ci: add download option to retrieve_single_manifest cmd-line tool

Makefile, bin/azurewrapper.py, bin/garden-version, bin/make-azure-ami, bin/make-ec2-ami, bin/make-gcp-ami, docker/Makefile, docker/integration-test/Dockerfile, tests/Pipfile, tests/Pipfile.lock, tests/README.md, tests/integration/aws.py, tests/integration/azure.py, tests/integration/conftest.py, tests/integration/gcp.py, tests/integration/test_gardenlinux.py, tests/run_full_test.py
This PR is a contribution for fully automated integration tests.
/kind test
/area os
Fixes #
```feature user
```
=> Integration tests for Azure and AWS

Makefile
/kind cleanup
/area os
Fixes pxe-dev output directory and adds dev variant for kvm target (it was using _dev feature but was built along the other non-dev targets).
=> Dev build targets output

packages/manual/dracut, packages/manual/dracut.d/dracut-core.install.patch, packages/manual/dracut.d/dracut-network.install.patch
/kind TODO
/area os
Fixes #
```feature user
```
=> fixes for dracut package

features/aws/upload, features/gcp/exec.config
/kind bug
/area os
Remove extra file
Fixes #
```feature user
```
=> Remove extra file

bin/garden-build.sh, build.sh
/kind TODO
/area os
/os test
Error out on failed tests, but keep created artifacts for debugging purposes.
Fixes #266
=> Error out when tests are failing

features/chost/file.include/overlay-redirect-dir.conf
"/kind" identifiers:     enhancement
performance improvement
https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html#renaming-directories
-->
/kind TODO
/area os
```feature user
```
=> activate overlay redirect_dir

features/server/pkg.include
/area os
Update python3.9 and iprounte2 packages used.
=> Update iproute2 and python3

features/azure/exec.config, features/azure/file.include/etc/systemd/system/walinuxagent.service.d/10-startpost.conf
/area os
Properly "change" the walinuxagent.service unit file by using a systemd drop in.
=> walinuxagent edit / switch to drop in

tests/integration/azure.py, tests/integration/test_gardenlinux.py
/kind test
/area os
Additional integration tests for the Azure platform.
Fixes #
```feature other
```
=> Azure integration tests

tests/integration/test_gardenlinux.py
/area os
This PR adds integration tests to validate that the specific AWS configuration is correct.
Fixes #323
```feature other developer
```
=> AWS configuration integration test

packages/manual/google-guest-agent, packages/manual/waagent, packages/manual/waagent.d/networkctl, packages/manual/waagent.d/tobytes
/area os
Adds the custom waagent package and fixes the google-guest-agent dscverify failure when using dget.
=> Add waagent, other small fix

tests/README.md
/kind cleanup
/area os
This PR enhances the documentation for integration tests by a comprehensive description of available configuration options in the configuration files.
**Special note to reviewer**:
These changes to the documentation already reflect the changes introduced by PR #382 .
```feature user
docs(integration-tests): comprehensive description of configuration files
```
=> docs(integration-tests): comprehensive description of configuration files

ci/glci/model.py, ci/glci/util.py
=> ci: undo model change b94ba0

logo/gardenlinux-sticker.svg
/area docs
adds a sticker with the gardenlinux logo
Fixes #
=> Gardenlinux sticker svg

bin/make-ec2-ami
/area os
Fixes #315 
```feature user
Add option to make-ec2-ami for setting tags on ami images
```
=> Add option to set tags for ec2 amis

features/openstack/file.include/etc/cloud/cloud.cfg.d/50-datasource.cfg
/area os
Configure correct datasource for cloud-init in order to avoid timeouts during startup.
Fixes #
```feature user
Boot time of OpenStack image reduced significantly.
```
=> Configure correct datasource avoiding timeouts

ci/params.py, ci/render_all.py, ci/render_pipeline_run.py, ci/render_pipelines.py, ci/render_pipelines_and_trigger_job, ci/render_task.py, ci/steps.py, ci/tasks.py, ci/tkn/model.py
/area os
simplify and optimize handling of Tekton parameters in ci scripts
```feature user
```
=> ci: simplify and optimize handling of Tekton parameters

tests/integration/openstackccee.py, tests/integration/util.py
/kind test
/area os
Optionally use floating ip instead of fixed ip for openstack tests.
Fixes #
```feature other
```
=> Openstack tests to use floating ips

bin/makepart, docker/build-image/Dockerfile
/area os
Just align fstab columns.
Fixes #
=> Align fstab columns

ci/render_pipeline_run.py, ci/steps.py, ci/steps/build_cert.sh
Some fixes as the previous pull-request was merged before it should've been.
=> ci: Some fixes to recent cfssl-changes

docker/integration-test/Dockerfile, tests/Pipfile, tests/Pipfile.lock, tests/integration/azure.py
/kind test
/area os
The platform/integration tests for Garden Linux on Azure now exclusively uses the Azure Python SDK to interface with the platform. This is in preparation for future integration of automatic platform/integration tests into the build process.
Also, lots of fixes on the way to improve robustness and mitigate resource leaks in Azure.
```feature developer
- test(azure): switch Azure tests to Azure Python SDK 
```
=> test(azure): switch Azure tests to Azure Python SDK

docs/kernel.md
/area documentation
doc: Added simple Q&A doc for Kernel Integration.
No issue created
=> Initial Doc for Kernel Integration

packages/manual/cyrus-sasl2
/kind bug
/area os
fix cyrus-sasl2 package build to work with new version from debian
=> packages: fix cyrus-sasl2 build

ci/render_pipeline_run.py, ci/render_pipelines.py, ci/steps.py
/area os
smaller fixes for CI
Fixes #
```feature user
```
=> Ci improve

features/server/pkg.include
/kind bug
/area os
We need to update iproute2's version as building is currently broken because of it.
Fixes #
=> Update iproute2 to 5.15

bin/garden-build.sh
/area os
We should copy over only the tests that really need to run chrooted.
=> Copy only the tests that run in a chroot

.gitignore, Makefile, bin/.constants.sh, bin/garden-build, bin/garden-config, bin/garden-init, build.sh, ci/steps/build_base_image.py, docker/Makefile, docker/build-image/Dockerfile
feat: builds now with minimized feature descriptor
bug: features in os-release are now complete
bug: ssh buildkeys are now proper deleted again
bug: pipeline needs new garden-feat binary in build-image
=> feature descriptor optimization

tests/integration/aws.py
/kind test
/area os
Refactoring of the integration test environment on AWS. Makes extensive use of tags so that resources in AWS can be easily identified and checked whether they were created by a specific test. Rewrote image uploading logic to use the boto library and functions that were already present in ci/cd code. No longer have to bring your own S3 storage account for image upload but the test can create one on the fly. Finally, better resource cleanup that (should) prevent accidental leakage of resources on AWS.
All of this is in preparation of automating the integration tests with the pipeline.
```feature developer
- test(aws): refactoring of AWS test environment with tags for …
```
=> test(aws): refactoring of AWS test environment with tags for automation

README.md
=> LTS is 5.15

tests/integration/azure.py
/kind test
/area os
Integration/Platform tests for Azure can now directly receive the image-under-test from a storage location in S3 (where build artifacts from the pipeline end up in).
```feature developer
- test(azure): upload test images directly from S3
```
=> test(azure): upload test images directly from S3

ci/release.py, ci/templates/github_release.md
/kind fix
/area os
re- add missing file for Github release
Fixes #
```feature user
```
=> re-add lost template for github release

bin/.cicd-cli.py, ci/clean.py, ci/glci/model.py, ci/glci/util.py, ci/params.py, ci/render_pipeline_run.py, ci/render_pipelines.py, ci/results.py, ci/steps.py, ci/steps/attach_logs.py, ci/steps/notify.py, ci/steps/promote_step.py, ci/steps/upload_results_step.py, ci/tasks.py, ci/tkn/model.py, integration_tests/ali/ali_test.py
/area os
CI: Improved handling of log files 
Fixes #
```feature user
```
=> Ci upload logs fix

bin/makepart, docker/build-image/Dockerfile, features/kvm/fstab, features/server/pkg.include
=> dm-verity support

ci/logs.py, ci/params.py, ci/render_pipelines.py, ci/steps.py, ci/steps/attach_logs.py, ci/steps/get_logs.py, ci/steps/notify.py
/area os
CI: fix a problem that notifications are no longer sent if an error in certain tasks happens
Fixes #
=> Ci notify fix

ci/build_kaniko.py, ci/clean.py, ci/glci/aws.py, ci/glci/model.py, ci/glci/util.py, ci/logs.py, ci/promote.py, ci/release.py, ci/render_pipeline_run.py, ci/render_pipelines.py, ci/render_task.py, ci/steps.py, ci/steps/attach_logs.py, ci/steps/build_base_image.py, ci/steps/clone_repo_step.py, ci/steps/clone_simple_step.py, ci/steps/component_descriptor.py, ci/steps/notify.py, ci/steps/pre_build_step.py, ci/steps/pre_check_tests.py, ci/steps/promote_step.py, ci/steps/release_step.py, ci/steps/run_tests.py, ci/steps/upload_results_step.py, ci/steps/upload_test_results.py, ci/tkn/model.py, ci/tkn/util.py, ci/wait_for_pipelinerun.py
Replaces `print` with calls of the appropriate-level logging function. Also contains a linting pass.
=> Ci: consistently use logging

ci/logs.py, ci/render_pipeline_run.py, ci/steps/attach_logs.py, ci/steps/notify.py, ci/templates/email_notification.html, ci/templates/email_notification.txt, ci/tkn/model.py
/area os
CI improvements:
* add logging excerpt to notification email
* add limits to package pipeline run definition
Fixes #
```feature user
```
=> Ci 2022 01 04

ci/glci/github.py, ci/release.py, ci/render_pipeline_run.py, ci/steps/notify.py, ci/steps/update_status.py
/kind cleanup
/area os
* avoid hardoded repo org and name in github status update
* fix missing parameter rename
Fixes #
```feature user
```
=> CI minor fixes and improvements

features/base/test/sgid, features/base/test/sgid.d/sgid.list, features/server/test/sgid, features/server/test/sgid.d/sgid.list
/kind test
/area os
Test for files that have the SGID bit set and compare against a list of allowed files.
Fixes #
=> Test for files with the SGID bit set

Makefile, bin/garden-debian-sources-list, bin/garden-fixup, bin/garden-init, build.sh, docker/build-image/Dockerfile
/area os
- adds option to provide local packages, overloading the ones from the repository
- this allows to more easily test packages before deploying them to the repository
=> use local packages for dev / testing

build.sh
* correct name of feature is `_slim`
=> Fix: typo in sample helptext

features/_pxe/exec.config, features/_pxe/file.exclude, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/cleanup.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.service, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.sh, features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/module-setup.sh, features/_pxe/pkg.include
/area os
Use igniton package provided by debian.
Remove file test for the squashfs.
Fetch remote files (ignition/squashfs) after resolved.
=> PXE updates

features/cloud/pkg.include
/kind bug
/area os
Update kernel version for Garden Linux 576.3
Fixes #
```bugfix user
Update kernel version for Garden Linux 576.3
```
=> Update kernel version for Garden Linux 576.3

README.md
=> fix typo in project description text

bin/garden-build, bin/garden-debian-sources-list, features/chost/file.include/overlay-redirect-dir.conf, features/server/exec.post
Bug: overlay redirect=on need only one set
Bug: typo
Feature: reduced output files, increased comments in sources.list
Feature: new names based on extensions
=> Minorpatch

ci/make_github_release.py, ci/release.py
/area os
Add script to manually create a Github release
Fixes #
```feature user
```
=> ci: add script to manually create github release, fix small bug

features/server/pkg.include
/kind bug
/area os
Fix CVE-2021-4034
Fixes #
```bugfix user
Fix CVE-2021-4034
```
=> Add fix for CVE-2021-4034

README.md
=> Fix (Readme): Fixed link to LICENSE.md

Makefile
simple intermediate type metalk-dev for development
=> adding new intermediate type

Makefile
/kind cleanup
/area os
Fixes makefile formatting
```feature user
```
=> Makefile format fix

bin/garden-build, features/base/file.exclude
/kind bug
/area os
Create a clean image
Fixes #626
```feature user
```
=> Delete “External Installation Planner Protocol” log

ci/github_release.py
=> fix component descriptor

.gitignore
/kind cleanup
/area os
Integration tests might leave log files behind which should not make their way into the repository.
```feature developer
chore: git-ignore logs files from tests
```
=> git-ignore log files left behind from tests

ci/render_task.py, ci/steps.py
ci: change environment variables
Fix problem after automatic credential rotation for pipeline secrets was enabled.
/kind fix
/area os
Fixes #
```feature user
```
=> ci: new job image, add generation to environment

features/server/pkg.include
/kind bug
/area os
add selinux allow rules for the selinux denied messages at boot
Fixes #540 #542 
```feature user
```
=> add gardenlinux-selinux-module

features/metal/pkg.include
Would like to have the tpm2-tools available for the metal installations.
=> Add tpm2-tools for metal

features/cloud/file.include/etc/kernel/postrm.d/zz-update-syslinux, features/metal/file.include/etc/kernel/postrm.d/zz-update-syslinux
syslinux kernel removal is a bit to vocal.
=> fixing typo in kernel scripts

features/cloud/pkg.include, features/metal/pkg.include
=> update(kernel): use kernel 5.15

tests/integration/chroot.py
/kind test
/area os
The currently used `tarfile` lib doesn't support handling of `xattrs`. Therefore, the migration of the unit tests to integration tests fails when it comes to validating the `xatts` from the `$gardenlinux.tar.xz` artifact. Unfortunately, we need to call `tar` as a command, now. 
Fixes #732
fyi @chrinorse
```feature user
```
=> fix(test): Adjust 'unarchive' func. in chroot platform to support xattrs

README.md, tests/README.md
/kind test
/area os
Adjust the documentation for integration/unit testing.
NONE
```feature user
```
=> doc(test): Adjust the docs for integration/unit testing

tests/README.md
/area os
* Adding ToC to tests documentation
* Adding content for `Misc`
* Reordering content
* Fix wording
NONE
```feature user
```
=> doc(tests): Add ToC, reorder content, adjust content

bin/garden-feat.go, features/README.md, features/example/info.yaml
* Add possibility to make features exclusive
* Adjust feature docs
* Add example in feature/example/info.yaml
/area os
Fixes #739
```feature user
```
=> feat(features): Add possibility to make features exclusive

docs/FAQ.md, docs/Repository/README.md
/area documentation
- FAQ created
- Repository README.md
=> Documentation: FAQ.md and Repository Readme

bin/garden-feat.go
/kind cleanup
/area os
Silences the go compilers complaint "Error strings should not be capitalized or end with punctuation" (the rest is gofmt doing its work).
```feature user
fix: remove error message for error string
```
=> fix: remove error message for error string

ci/glci/alicloud.py, ci/requirements.txt
/area os
Support publish image to community on AliCloud.
Fixes #
```feature user
Now users can find GardenLinux images from community on AliCloud.
```
=> support community image for AliCloud

bin/Makefile
fixes explicit docker image locations in podman
=> fixes image location

CONTRIBUTING.md
/area os
Add to the contribution guidelines that we prefer squashed PRs.
```feature user
- doc: require squashed commits in contribution guidelines
```
=> doc: require squashed commits in contribution guidelines

bin/README.md
/area os
Add documentation for the `bin/` directory. This provides a small overview of the given toolset in GL.
Fixes #793
```feature user
NONE
```
=> feat(doc): Add documentation for the `bin/` directory

features/cis_aide/file.include/usr/bin/aideinit, tests/integration/kvm.py, tests/integration/misc/sshd-integration.test.service
/kind bug
/area os
harden/improve the kvm test environment
Fixes #803
```feature user
```
=> harden kvm test environment

README.md
fix(doc): Adjusting the repo `README.md`
* Fix typos
* Fix gram
* Reorder feature list
/area os
```feature user
NONE
```
=> fix(doc): Adjusting the repo `README.md`

ci/steps/component_descriptor.py
Recent PR attempted to set the digest on the wrong model class.
=> ci: fix DigestSpec arg

features/server/test/test_ssh_authorized.py, tests/helper/tests/ssh_authorized.py
/area os
simplify existing pytest ssh_authorized
Fixes #874 
```feature user
```
=> simplify existing pytest ssh_authorized

features/server/test/test_systemctl.py, tests/helper/tests/systemctl.py
/area os
simplify existing pytest systemctl
Fixes #874 
```feature user
```
=> simplify existing pytest systemctl

features/server/test/test_reset_env_vars.py, tests/helper/tests/reset_env_vars.py
/area os
smplify existing pytest reset_env_vars
Fixes #874 
```feature user
```
=> smplify existing pytest reset_env_vars

features/base/test/test_users.py, tests/helper/tests/users.py
/area os
simplify existing pytest users
Fixes #874 
```feature user
```
=> simplify existing pytest users

features/cis/test/config.yaml, features/cis/test/test_debian_cis.py, tests/helper/tests/debian_cis.py
feat(test): Simplify `CIS` PyTest
/kind test
/area os
Use simpler version of `PyTests`
Fixes #874
```feature user
NONE
```
=> feat(test): Simplify `CIS` PyTest

features/base/test/debsums.d/debsums_exclude.list, features/base/test/test_debsums.py, tests/helper/tests/debsums.py
/area os
simplify existing pytest debsums
Fixes #874 
```feature user
```
=> simplify existing pytest debsums

features/base/test/test_duplicate_uids.py, tests/helper/tests/find_dup_uids.py
/area os
simplify existing pytest duplicate uids
Fixes #874 
```feature user
```
=> simplify existing pytest duplicate uids

tests/conftest.py
/kind bug
/area os
reimplement feature .disable function for tests
Fixes #966 
```feature user
```
=> reimplement feature .disable function for tests

features/server/test/test_autologin.py
fix(pytest): Fix path to systemd unit for `test_autologin`
/kind bug
/area os
fix(pytest): Fix path to systemd unit for `test_autologin`
Fixes #960
```feature user
NONE
```
=> fix(pytest): Fix path to systemd unit for `test_autologin`

features/base/test/test_password_shadow.py, tests/helper/tests/password_shadow.py
/area os
simplify existing pytest password shadow
Fixes #874 
```feature user
```
=> simplify existing pytest password shadow

features/cis_os/file.include/etc/selinux/config
feat(selinux): Activate SELinux (mode=enforcing)
/area os
Activate SELinux (mode=enforcing) for feature `cis` only
Fixes #787
```feature user
- - target_group: user
```
=> feat(selinux): Activate SELinux (mode=enforcing)

ci/glci/aws.py
fix(ci): Fix Py syntax errors
/kind bug
/area os
=> fix(ci): Fix Py syntax in `aws.py` errors

tests/integration/azure.py
/kind test
/area os
Greatly improves upload speed for uploading test images to Azure by `seek()`-ing past holes in the image file.
**Fixes:**
Fixes #987 
```feature user
- improved upload speed for uploading test images to Azure 
```
=> test: speed up Azure image upload

features/_readonly/info.yaml
/area os
enable verity in readonly feature
Fixes #679 
```feature user
```
=> enable verity in readonly feature

bin/makepart, features/_fstab_verity/fstab.mod
/kind bug
/area os
set machine-id properly on read only filesystem
Fixes #1053 
```feature user
```
=> mount /overlay and etc overlay in initramfs

README.md, bin/garden-init, features/base/test/test_sgid_suid_files.py
/area os
Add crossbuild compatibility to build `arm64` on `amd64`.
Add crossbuild compatibility to build `amd64` on `arm64`.
Fixes #1063
```feature user
NONE
```
=> feature(build-pipeline): Add crossbuild compatibility

.github/workflows/build.yml, Makefile, bin/garden-build, bin/make_reproducible_ext4, bin/makepart, features/firecracker/file.exclude, features/firecracker/fstab.mod, features/firecracker/image, features/firecracker/info.yaml, features/firecracker/pkg.exclude, features/firecracker/pkg.include, features/server/exec.post
/area os
adds a platform feature for [firecracker](https://firecracker-microvm.github.io/)
Fixes #1047
**TODO**:
=> add firecracker platform feature

features/metal/pkg.include
/kind bug
/area os
bird2 is back iin debian testing
Fixes #
```feature user
```
=> re-add bird2 package

features/metal/file.include/usr/sbin/enroll-gardenlinux-secureboot-keys, features/metal/pkg.include
/kind bug
/area os
use efi-updatevar to write to efivars
Fixes #1045 
```feature user
```
=> use efi-updatevar to write to efivars

features/base/test/test_debsums.py
/kind bug
/area os
don't run debsums in an environment that prevents to run apt-get update and install additional packages.
Fixes #1101 
```feature user
```
=> run debsums check only in chroot integration test environment

tests/README.md
feat(tests): Add chart
/kind test
/area os
This PR adds a flowchart, how artifacts are tested.
```feature user
NONE
```
=> feat(tests): Add chart

.github/workflows/upload_to_s3.sh
/kind cleanup
/area os
Fixes some fields in the meta YAML file that is used to hand over build-artifacts from GitHub actions to the publishing code in Tekton.
```feature user
fix: add some fixes to S3 meta yaml
```
=> fix: add some fixes to S3 meta yaml

bin/start-vm
Update Start-VM: Added support for Manjaro as Arch-based Distribution
Added Support for Manjaro to start-vm script
```feature user
```
=> Update Start-VM: Added support for Manjaro

build.sh
/kind bug
/area os
check if .git directory is present
Fixes #1149 
```feature user
```
=> check if .git directory is present

features/_readonly/README.md
/area os
The enhancement adds some references to the `dm-verity` documentation making the feature more clear to beginners.
=> feat(docu): Enhance the documentation of the _readonly feature

features/server/pkg.include
Enable GardenLinux SELinux module
/area os
Enable GardenLinux SELinux module providing all necessary rules
Fixes #1202 
```feature user
NONE
```
=> feat(selinux): Enable GardenLinux SELinux module

docs/build/README.md
/kind bug
/area os
add docs to explain the problem and how to achieve the same result without running into limitations
Fixes #1181 
```feature user
```
=> add local_packages and how to replace the kernel to the docs

.github/workflows/aws_tests.sh, .github/workflows/tests.yml
/area os
enable aws platform tests for arm64
=> feat: github actions: arm64 aws platform tests

features/azure/file.include/etc/systemd/99-azure-unmanaged-devices.network, tests/README.md, tests/integration/azure.py
/area os
Fixes #1198
The Azure feature is described here: https://docs.microsoft.com/en-us/azure/virtual-network/accelerated-networking-overview
I have checked the configuration on the VM to ensure it is enabled and working. I will add an integration test for this later on.
```feature user
Garden Linux supports Azure accelerated networking.
```
=> Enable Azure accelerated networking

features/github_action_runner/pkg.include
/area os
Includes the package `azure-cli` to the image for GitHub Actions runner which is needed for automated platform tests on Azure.
```feature operator
feat: add azure-cli to GitHub actions runner image
```
=> feat: add azure-cli to gh-actions runner

features/chost/README.md, features/chost/exec.config, features/chost/file.include/etc/sysctl.d/ip-forward.conf
/kind cleanup
/area os
Cleanup and fixing docs.
Fixes #
```feature user
NONE
```
=> cleanup(chost): Cleanup chost feature

features/firewall/test/test_nft_config.py, features/firewall/test/test_packages_musthave.py, features/firewall/test/test_systemd_units.py
/kind test
/area os
Add tests for feature `firewall`.
Fixes #1173
```feature user
NONE
```
**Tests**:
```
PASSED firewall/test/test_nft_config.py::test_nft_config
PASSED firewall/test/test_packages_musthave.py::test_packages_musthave
PASSED firewall/test/test_systemd_units.py::test_systemd_unit[nftables]
```
=> tests(firewall): Add unit tests for feature `firewall`

features/chost/test/test_systemd_unit.py
tests(chost): Add unit test for feature `chost`
/kind test
/area os
Add unit test for feature `chost`
Fixes #1173
```feature user
NONE
```
=> tests(chost): Add unit test for feature `chost`

.github/workflows/aws_tests.sh, .github/workflows/azure_tests.sh, .github/workflows/nightly.yml, .github/workflows/tests.yml
/kind test
/area os
Enables automatic platform tests on Azure for the nightly builds.
Once merged, the trust relationship of the OIDC configuration in Azure needs to be reviewed.
```feature user
- tests: automatic platform tests on Azure
```
=> tests: automatic platform tests on Azure

features/vhost/README.md, features/vhost/test/test_packages_musthave.py, features/vhost/test/test_systemd_unit.py
tests(vhost): Add unit test for feature `vhost`
/kind test
/area os
Add unit test for feature `vhost`
Fixes #1173
```feature user
NONE
```
=> tests(vhost): Add unit test for feature `vhost`

features/fedramp/test/test_packages_musthave.py
tests(fedramp): Add unit test for feature `fedramp`
/kind test
/area os
Add unit test for feature `fedramp` to validate packages that should be in-/excluded.
Fixes #1173
```feature user
NONE
```
=> tests(fedramp): Add unit test for feature `fedramp`

features/vmware/test/test_check_files.py, features/vmware/test/test_content_in_file.py, tests/helper/utils.py
tests(vmware): Add unit tests for feature `vmware`
/kind test
/area os
Add unit tests for feature `vmware`
Fixes #1173
```feature user
NONE
```
**Test(s)**:
```
PASSED vmware/test/test_exist_files.py::test_exists_file[/usr/bin/dscheck_VMwareGuestInfo]
PASSED vmware/test/test_exist_files.py::test_exists_file[/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py]
PASSED vmware/test/test_exist_files.py::test_exists_file[/etc/default/grub.cfg]
PASSED vmware/test/test_exist_files.py::test_exists_file[/etc/cloud/cloud.cfg.d/01_debian-cloud.cfg]
PASSED vmware/test/test_exist_files.py::test_exists_file[/etc/cloud/cloud.cfg.d/99_disable- …
```
=> tests(vmware): Add unit tests for feature `vmware`

features/openstack/test/test_check_files.py, features/openstack/test/test_content_in_file.py
tests(openstack): Add unit tests for feature `openstack`
/kind test
/area os
Add unit tests for feature `openstack`
Fixes #1173
```feature user
NONE
```
=> tests(openstack): Add unit tests for feature `openstack`

tests/README.md
docs(pytest): Add example config for running feature related tests
/kind test
/area os
Add example config for running feature related tests
```feature user
NONE
```
=> docs(pytest): Add example config for running feature related tests

tests/integration/aws.py
/kind test
/area os
Tags resources in AWS that are used for tests so that false Minerva alerts are suppressed.
```feature user
tests: add exception tags to test resources in AWS
```
=> tests: add exception tags to test resources in AWS

features/base/test/test_sgid_suid_files.py, features/server/pkg.include
/kind but
/area os
Hostname cannot be set anymore if policykit is missing. This has been removed altough the original commit message stated that it is required for that purpose.
Fixes #1292
```feature user
```
=> Add policykit again

build.sh
Append test logs to the build log.
=> Append test logs to build log

tests/tools/clean_orphans_aws.py
/kind test
/area os
The script `clean_orphans_aws.py` which can be used to clean AWS resources that were leftovers from previous integration/platform tests got an option to force-remove all resources it comes across without interactively asking. I believe it speaks for itself that this needs to be handled with care...
```feature user
- feat: clean_orphans_aws can be forced
```
=> feat: clean_orphans_aws can be forced

container/integration-test/Dockerfile, tests/README.md, tests/conftest.py, tests/integration/firecracker.py
feat(pytest): Add Firecracker IAAS for PyTest
/kind test
/area os
This PR adds a new IAAS for `Firecracker` / `microvm` types and takes care to adjust filesystem images and to create needed bridge interfaces within a container environment to access the instance.
Fixes #1240
```feature user
NONE
```
=> feat(pytest): Add Firecracker IAAS for PyTest

tests/README.md
Extend testing docs
/kind docs
/area os
Extend testing docs
Fixes #456
```feature user
- category: doc
- target_group:  user
```
=> docs(tests): Extend testing docs

CONTRIBUTING.md, docs/contributing/README.md
doc(contributing): Adding doc for contributing and naming convention
/area os
Adding doc for contributing and naming convention
Fixes #625
```feature user
NONE
```
=> doc(contributing): Adding doc for contributing and naming convention

CONTRIBUTING.md
Mention "cleanup/" as allowed prefix
/area os
Mention "cleanup/" as allowed prefix
```feature user
NONE
```
=> cleanup(contribution): Mention "cleanup/" as allowed prefix

features/base/test/test_sgid_suid_files.py, features/vhost/test/test_sgid_suid_files.py
/kind bug
/area os
Fixes #1340 
```feature user
```
=> fix path to polkit-agent-helper-1 in test_sgid_suid_files

README.md
doc(build): Fix link in `README.md`
/kind TODO
/area os
Fix link in `README.md`
Fixes #1348
```feature user
NONE
```
=> doc(build): Fix link in `README.md`

container/build-image/Dockerfile
/area os
since aws-sdk-cpp and aws-kms-pkcs11 are now available in the gardenlinux repo, install the package from the gardenlinux repo
Fixes #1270 
```feature user
```
=> use aws-sdk-cpp and aws-kms-pkcs11 from gardenlinux repo

docs/build/README.md
doc(build): Extend the build documentation
/area os
Extend the build documentation
Fixes #716
```feature user
NONE
```
=> doc(build): Extend the build documentation

features/_iso/README.md, features/base/README.md, features/cis/README.md, features/cisAudit/README.md, features/cisModprobe/README.md, features/cisOS/README.md, features/cisPackages/README.md, features/cisPartition/README.md, features/cisSshd/README.md, features/cisSysctl/README.md, features/example/README.md, features/example/convert, features/example/file.include.stat, features/example/image, features/firewall/README.md, features/gardener/README.md
feature(example): Adjust docs for example
* Adjust docs for example
* Add further examples for all options
* Fix missing newlines on other docs
/area os
Adjust docs for example
Fixes #1406
None
```feature user
- category: doc
- target_group: user,operator,developer
```
=> feature(example): Adjust docs for example

features/vmware/file.include/etc/kernel/cmdline.d/50-ignition.cfg, features/vmware/file.include/etc/systemd/system/ignition-disable.service, features/vmware/info.yaml
/area os
We'd like to have ignition enabled on VMware.
=> Enable ignition on vmware

features/_oci/test/test_oci.py, tests/README.md, tests/conftest.py, tests/integration/misc/docker_registry_config_integrations_tests, tests/integration/test_gardenlinux.py
feature(pytest): Add local test for _oci-feature
/kind test
/area os
Fixes #1310
=> Feature/1310 add test local and implement testing for  oci feature

flavours.yaml
Add container and sort ASC yaml file
/area os
Add container and sort ASC yaml file
We should add the `container` platform and "sort" the yaml file.
```feature user
NONE
```
=> enhancement(flavours): Add container and sort ASC yaml file

container/build-image/Dockerfile
/area os
add oras to build-image container
Fixes #
```feature user
```
=> add oras to build image container

features/README.md, features/_nopkg/README.md, features/_oras/README.md, features/_persistence/README.md, features/_pxe/README.md, features/_readonly/README.md, features/chost/README.md, features/cis/README.md, features/cisModprobe/README.md, features/cisPackages/README.md, features/cisSysctl/README.md, features/cloud/README.md, features/fedramp/README.md, features/firecracker/README.md, features/firewall/README.md, features/gardener/README.md, features/khost/README.md, features/kvm/README.md, features/metal/README.md, features/server/README.md, features/ssh/README.md
doc(features): Fix typos and layout
/area os
Fix typos and layout
```feature user
NONE
```
=> doc(features): Fix typos and layout

features/vmware/file.include/usr/local/sbin/update-bootloaders
/kind bug
/area os
fixes ignition run
Fixes #
=> feature(vmware): add update-bootloaders

tests/conftest.py, tests/integration/aws.py
Cherry-pick of https://github.com/gardenlinux/gardenlinux/commit/4bf5b248d539e3e5b0f575ef3f1424378d28fb74 
Required to run without glci dependency
=> fix(tests): remove dependency to glci (#1497)

features/azure/file.include/etc/waagent.conf, features/azure/pkg.include
Adding waagent again, because it seems like waagent is a requirement for azure.
=> feat(azure): add waagent again

tests/tools/azure-conformance-test.py
/kind test
/area os
Provides a script to run Azures Marketplace conformance tests - the same tests they run when certifying an image for Az Marketplace.
See more info at https://learn.microsoft.com/en-us/azure/marketplace/azure-vm-image-test
```feature developer
- provide a script to run Azures Marketplace conformance tests
```
=> test: Az Marketplace conformance script

.github/workflows/build.yml, .github/workflows/tests.yml, .github/workflows/upload_to_s3.yml, bin/garden-build, bin/garden-feat, bin/gen_make_targets, container/build-image/Dockerfile, features/githubActionRunner/info.yaml
/area os
rewrite garden-feat using graph library (networkx) to allow more complex operations, specifically exclude
=> feat: rewrite garden-feat using networkx graph lib

features/_selinux/test/test_kernel_cmdline.py, features/firecracker/info.yaml, features/gardener/info.yaml, features/githubActionRunner/file.include/etc/kernel/cmdline.d/99-no-lsm.cfg, features/githubActionRunner/info.yaml, tests/conftest.py
=> use feature exclude for _selinux

hack/gl-search-package.sh
Improve package search tool. User specifies the version to search packages in via fzf.
=> feat(hack): user select garden linux version for package search

features/gardener/exec.config, features/gardener/pkg.include
error in rel934.
we have users that complained about mixed firewall setup. so we are reverting to iptables-legacy for now.
=> remove iptables-nft default relation

requirements.txt
feature(build): Add a `requirements.txt` for Python dependencies
/area os
There may be corner cases, where these packages may not be available in a system's package manager like `macOS`.
Python's pip provides a proper solution by adding a [requirements.txt](https://pip.pypa.io/en/stable/reference/requirements-file-format/) file to solve this.
Fixes #1535
```feature user
- target_group: developer
```
=> feature(build): Add a `requirements.txt` for Python dependencies

.github/workflows/tests-only.yml
* tests-only.yml workflow is called manually
* commitish must match the target build artifact
* build artifact to test will be downloaded from s3
=> ci(tests): run tests for existing builds in gh actions

.github/workflows/gcp_tests.sh
* google-github-actions/auth already sets path to gh credentials json.
* using find to locate the cred file is dangerous, multiple or no credfile could be found but
the error message would be missleading, and
not indicate such an error.
=> ci: fix gcp credential handling

.github/workflows/tests-only.yml, .github/workflows/tests.yml
* syntax for conditional was wrong, so for every target all authentications were
performed, which is unnecesseary
=> fix(ci): platform test action auth condition

features/gardener/info.yaml
gardener is pulling SAP feature now to fullfill requirements
=> pulling sap feature

features/gardener/info.yaml
/area os
* gardener feature should depend on sap feature
* sap feature provides sap specifics
=> feat(sap): include sap feature in gardener feature (#1635)

tests/Pipfile, tests/integration/gcp.py
/kind test
/area os
We need to cherry-pick a7ed52f into rel-934 branch.  
We changed the used api in the gcp platformtest setup in this commit 7b35ac4.
This PR brings the required changes from main to rel-934.
**Note for Reviewer**
I think we should keep the history and NOT squash this PR into a single commit. We added a bunch of commits via cherry-pick from main. History will be more meaningful if we keep the original commit messages.
=> fix(test): backport updated gcp integration test to rel 934

.github/workflows/check-packages.yml
Print package report in case of failure
=> fix(ci): Print Check Packages report

.github/workflows/build.yml, tests/init
note: using fork of [runforesight/workflow-telemetry-action](https://github.com/runforesight/workflow-telemetry-action) due to formatting / process name escape issues (https://github.com/runforesight/workflow-telemetry-action/pull/40)
=> feat: add profiling to github action build

build
* https://github.com/gardenlinux/builder/pull/3
* https://github.com/gardenlinux/builder/pull/5
* only include changes on build script
* https://github.com/gardenlinux/builder/pull/9
/cc @damyan @MalteJ as mentioned in https://github.com/gardenlinux/builder/pull/3#issuecomment-1600467900
UPDATE:
* also updated reference to latest commit tag of builder container image. This contains a fix for keyring
=> latest build script from gardenlinux/builder

tools/import-ec2-ami.py
/area os
Adds a progress indicator to the `import-ec2-ami` script so that it does not seem to have crashed.
```feature user
The `import-ec2-ami` script now features a progress indicator which can be enabled by `--show-progress`.
```
=> Include a progress indicator into import-ec2-ami

features/server/file.include/etc/update-motd.d/05-logo
The hint about bookworm is outdated
=> Update MOTD bookworm -> trixie

tests/README.md
* describe how to start tests
* remove legacy references to build.sh
=> doc: remove legacy references

build, features/_boot/exec.late, features/_boot/file.exclude, features/_boot/file.include/usr/local/sbin/update-syslinux, features/_readonly/README.md, features/_readonly/fstab.mod, features/_secureboot/exec.config, features/_secureboot/fstab.mod, features/_secureboot/test/test_empty_files_boot_efi.py, features/base/fstab, features/cis/test/check_scripts/1.5.1_bootloader_ownership_syslinux.sh, features/cis/test/check_scripts/1.7.1.2_enable_selinux.sh, features/cis/test/check_scripts/4.1.1.3_audit_bootloader.sh, features/cis/test/check_scripts/4.1.1.4_audit_backlog_limit.sh, features/cisPartition/fstab, features/kvm/file.include/etc/systemd/system/ignition-disable.service, features/vmware/file.include/etc/systemd/system/ignition-disable.service
Switch the boot partition from /boot/efi to /efi
Fixes #
=> Switch from /boot/efi to /efi

bin/start-vm
/area os
Allow using the start-vm script on fedora linux
```feature user
```
=> start-vm: Support using fedora linux hosts

.github/workflows/release-page.yml
Add missing boto3 dependency for the `generate_release_notes.py`
=> fix(release notes): install dependencies for generate release py tool

build_bare_flavors
=> refactor: fix shellcheck warning

tests/tools/clean_orphans_gcp.py
/kind test
/area os
Adds a `--force-all` switch to the cleanup tool for GCP test.
```feature user
test: add force_all switch to clean_orphans_gcp
```
=> test: add force_all switch to clean_orphans_gcp

features/firewall/file.include/etc/nft.d/default.conf
=> fix: firewall allow dhcpv6client/server traffic

.github/labeler.yml, .github/workflows/labeler.yml
https://github.com/actions/labeler#breaking-changes-in-v5
=> Adapt to actions/labeler v5

features/sapmachine/exec.config
Simple hardcoded checksum verification. 
Motivated by 🐰
=> Add checksum verification for sapmachine feature

features/sapmachine/exec.config
updates sap machine to LTS 🆙 
fixes nightly 🌙 
motivated by 🐰
=> update sap machine in bare flavour + checksum updates

.github/workflows/build.yml, cert/build
The change in #1874 had unintended side-effects. This PR attempts to mitigate those issues, but might not be the most elegant solution for that.
=> Fix build after breaking it in #1874

hack/lima-dev-env/gl-dev.yaml
Update of debian base image and gh cli client
=> Update dev env

docs/02_operators/deployment/aws-secureboot.md, docs/02_operators/deployment/gcp-secureboot.md, docs/02_operators/deployment/install-non-default.md
=> Update docs for new builder

.github/dependabot.yml
* we do not need to upgrade unnecessary pip or gh actions
* feedback on how to improve this configuration is very welcome
=> ci: dependabot strategy to increase-if-necessary

tests/helper/sshclient.py
In some rare cases, the Garden Linux platform test framework attempts to connect to a machine during its boot-up in that small time frame when SSH already accepts connections but PAM refuses them with the "System is booting up" message. In this case, the tests should not be aborted with an error but the connection should be retried.
Along the lines, a little code cleanup.
```feature user
Garden Linux platform tests no longer abort on pam_nologin but attempt to retry.
```
=> test: handle pam_nologin during connection attempt

features/gardener/README.md
keep informations up-tp-date of features
=> Update README.md of Gardener

features/gdch/info.yaml, features/gdch/pkg.exclude
feature gdch has missing files in rel-1443
=> (rel-1443 branch) fix: add info.yaml for gdch

builder.dockerfile, docs/01_developers/build_image.md, features/_secureboot/exec.config, features/_secureboot/pkg.include
Possible thanks to https://github.com/gardenlinux/builder/pull/73
Tested with podman machine on macos with a new vm that has SELinux enabled
=> Build with SELinux enabled

build
#2083 used new builder container without corresponding build script => not actually using the fake_xattr binary
=> fix: PR #2083

.github/workflows/get_kernelurls.py, .github/workflows/release-page.sh
=> Fix get kernelurls

bin/start-vm
start-vm is broken on mac
Fixes #2172
=> Fix start-vm on mac

bin/start-vm
=> bin/start-vm: add opensuse

docs/00_introduction/README.md, docs/00_introduction/package-pipeline.md
Add high level documentation for our package pipeline, outlining the design decisions and qualities it brings.
=> document package pipeline design

features/azure/file.include/etc/dracut.conf.d/67-azure-nvme-modules.conf, features/azure/file.include/etc/kernel/cmdline.d/45-nvme-timeout.cfg
Adds additional configuration for Azure NVMe according to the guidelines in
https://techcommunity.microsoft.com/t5/running-sap-applications-on-the/converting-virtual-machines-running-linux-from-scsi-to-nvme/ba-p/4162497 
and
https://raw.githubusercontent.com/Azure/SAP-on-Azure-Scripts-and-Utilities/main/NVMe-Preflight-Check/azure-nvme-preflight-check.sh.
```feature user
additional configuration to support NVMe on Azure was added to the Azure feature
```
=> additional support for NVMe on Azure

tools/clean_ec2_ami.py
Fixes a small problem with the `clean_ec2_ami.py` script used for deleting images from AWS EC2. The problems made usability a matter of improvement which was (partly) achieved with this PR.
```feature user
NONE
```
=> Fix a small problem with clean_ec2_ami.py

.github/pull_request_template.md
Add a definition of done to remind about tests, docs and potentially needed backports.
I want to keep this lean, but for sure that dod is not 'done'. Feedback is welcome.
=> Bootstrap PR template

features/_dev/file.include/etc/kernel/cmdline.d/42-forward-journal.cfg, features/kvm/file.include/etc/kernel/cmdline.d/10-console.cfg
This reverses parts of #2167 because that makes working with the serial console too painful
=> Reduce noise on serial console for _dev feature

.github/workflows/nightly.yml
=> fix: correctly set use_kms in nightly

.github/workflows/upload_oci.yml
Closes https://github.com/gardenlinux/gardenlinux/issues/2551
=> Add mediatype to OCI index

features/_usi/file.include/etc/systemd/system/root.mount
=> fix: _usi /root tmpfs permissions

features/_trustedboot/usi.config
=> debug: print more verbose info on KMS PKCS11 signing

.github/workflows/build.yml
=> fix: bump duration of secboot signing OIDC role

docs/architecture/decisions/0005-secure-boot-keys-glci.md
Document decision on handling secure boot keys in glci jointly taken by @MrBatschner, @yeoldegrove and me today
=> document decision on handling secure boot keys in glci

features/gcp/exec.config
=> mask google-guest-agent-manager.service unit

flavors.yaml
Needed for our _cloud infrastructure_ colleagues.
=> feat: add new flavor metal-gardener_pxe

.github/workflows/publish_container.yml
=> Do not use nightly tags anymore for 1443

features/_ephemeral/initrd.include/etc/systemd/system/sysroot-var.mount, features/_nocrypt/initrd.include/etc/systemd/system/sysroot-var.mount, features/_tpm2/initrd.include/etc/systemd/system/sysroot-var.mount, features/_usi/initrd.include/etc/systemd/system-generators/detect-disk-by-efivars
=> fix: use Wants instead of Requires for sysroot-*.mount units

tests/platformSetup/tofu/modules/azure/main.tf
https://github.com/gardenlinux/gardenlinux/pull/2858 introduced a syntax error. This PR fixes it.
=> fix DER cert and KEK on azure platform tests

tests/platformSetup/tofu/modules/azure/main.tf
remove wrong dependency introduced in #2854
=> remove wrong dependency introduced in #2854

.github/workflows/build.yml, build, test, tests/Containerfile.chroot, tests/Dockerfile, tests/Pipfile.lock
Update python dependencies for platform-tests to fix missing `python_gardenlinux_lib`.
- Needs an updated builder image that can run `git`.
- removed remove unused `test_container`
```
❯ podman run -it -v $PWD:/gardenlinux ghcr.io/gardenlinux/gardenlinux/platform-test-tofu:nightly bash -c "pipenv lock"
Courtesy Notice:
Pipenv found itself running within a virtual environment,  so it will automatically use that environment, instead of 
creating its own for any project. You can set
PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create  its own instead.
You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
⠹ Locking …
```
=> update python dependencies for platform-tests

features/khost/exec.late
When using the _khost_ feature _crictl_ would be nice to have.
=> feat: add crictl via the khost feature

.github/workflows/platform-test-images.yml
This PR fixes an issue with all artifacts created being downloaded for building the platform test images.
Fixes #2879
=> Fix download of base platform test image artifact

.github/workflows/build.yml, .github/workflows/download_flavors_images.yml, .github/workflows/publish_oci_containers.yml, .github/workflows/tests.yml
This PR adds conditionals in GitHub workflows to ensure matrices are not empty (by purpose).
=> Support empty matrices for GitHub workflows

.github/workflows/manual_release.yml, .github/workflows/nightly.yml, .github/workflows/publish.yml, .github/workflows/publish_s3.yml
This PR changes the syntax to get failing jobs in GitHub workflows retried automatically.
=> Fix the GitHub workflow syntax to retry certain jobs automatically

.github/workflows/platform_test_cleanup.yml, .github/workflows/test_platform_flavor.yml
This PR focuses again on the following error in `platform_test_cleanup.yml` and `test_platform_flavor.yml`:
```
SyntaxError: missing ) after argument list
```
=> Retry fix for SyntaxError in GitHub workflows (again)

.github/workflows/build_kmodbuild_container.yml, .github/workflows/github.mjs, .github/workflows/tests.yml
This PR adds support to intersect flavor matrices in GitHub workflows to execute tests only for enabled flavors.
=> Add support to intersect matrices for use in GitHub workflows and tests

.github/workflows/download_workflow_data.yml, .github/workflows/publish_kmodbuild_container.yml, .github/workflows/publish_oci_containers.yml
This PR fixes the flavors matrices used in GitHub workflows for publishing.
=> Fix the flavors matrices used in GitHub workflows for publishing

.github/workflows/download_workflow_data.yml, .github/workflows/github.mjs, .github/workflows/publish_kmodbuild_container.yml, .github/workflows/publish_oci_containers.yml, .github/workflows/publish_s3.yml
This PR fixes an issue with using the correct flavor version data for publishing to s3.
This PR requires #2920
=> Use correct flavor version data for publishing to s3

build
Fixes #
- [v ] The code is sufficiently documented
- [ v] Shared the changes with the Team so everyone is aware
- [ v] The code is appropriately tested
- [ v] Checked if the code needs to be backportet to release branches of maintained versions (perform the actual backport after the merge to `main`)
```feature user
```
=> Update to newer builder version including modernized apt sources

container/kmodbuild/Containerfile
backport of https://github.com/gardenlinux/gardenlinux/pull/2989
=> Backport purge excluded packages for rel 1443

.github/workflows/build.yml, .github/workflows/build_flavor.yml, .github/workflows/build_requirements.yml, .github/workflows/download_workflow_data.yml, .github/workflows/manual_release.yml, .github/workflows/manual_tests.yml, .github/workflows/nightly.yml, .github/workflows/publish.yml, .github/workflows/publish_oci_containers.yml, .github/workflows/publish_s3.yml, .github/workflows/test_platform_flavor.yml, features/_usi/exec.post
- Completes the work started in #3012
- Allows distinction between release and nightly channels when building and publishing
=> feat: add support for release and nightly channels to publishing

flavors.yaml
=> feat: enable _usi flavour

tests/platformSetup/tofu/README.md
Document OpenTofu version and provider update.
Fixes #3178
=> document OpenTofu version and provider updates

tests/README.md
Document Platform-Test image github actions workflow.
Fixes #3179
=> document Platform-Test image github actions workflow

features/lima/README.md, features/lima/samples/README.md, features/lima/samples/gardenlinux-containerd.yaml, features/lima/samples/gardenlinux-rootless-podman.yaml
Adding some samples to demonstrate what Garden Linux lima images could be used for.
=> Add lima sample manifests

.github/workflows/build_flavor.yml, .github/workflows/download_flavors_images.yml, .github/workflows/manual_gh_release_page.yml, .github/workflows/platform_test_cleanup.yml, .github/workflows/publish_oci_containers.yml, .github/workflows/publish_s3.yml, .github/workflows/test_platform_flavor.yml, .github/workflows/upload_to_s3.yml
This reverts commit 97326f3ea5ea106dddcf651a1ed54c67d2987033.
This might be the cause for a failed nightly build
https://github.com/gardenlinux/gardenlinux/actions/runs/16742771111/job/47400495878
https://github.com/gardenlinux/gardenlinux/issues/3257
=> Revert "build(deps): bump aws-actions/configure-aws-credentials"

build
Include rebuild of the builder https://github.com/gardenlinux/builder/commit/d6d24ba1aec66889a2acab83aedcb00e869abfcd
Fixes https://github.com/gardenlinux/gardenlinux/issues/3269
=> Update the builder image to testing after debian trixie was released

tests-ng/test_nodejs.py
Related to https://github.com/gardenlinux/gardenlinux/issues/3181, but this feature did not have tests before
=> Add tests for nodejs feature

.github/workflows/manual_gh_release_page.yml
fix: in manual_gh_release_page.yml put flavors_matrix into own step
This fixes #3406 and it's wrong checkout of files.
**Notes for reviewer**:
I cannot test this because of branch restrictions :(
=> fix: in manual_gh_release_page.yml put flavors_matrix into own step

.github/workflows/build.yml
trying to fix workflow permissions in included "build"-workflow.
=> remove workflow permissions setting from included workflow. refs #3215

tests-ng/plugins/network.py, tests-ng/test_network.py
Migrates the tests from `features/base/test/test_network.py` to a new file for our new testing framework. The original test relied on external connections to the general internet being available. These were replaced by tests that work with our contained environment.
Fixes: [#3438](https://github.com/gardenlinux/gardenlinux/issues/3438)
Tracks https://github.com/gardenlinux/gardenlinux/issues/3181
=> Tests: Migrate `features/base/test/test_network` to new testing framework

features/lima/README.md
=> fix lima readme

docs/architecture/decisions/0006-garden-linux-versioning.md, docs/architecture/decisions/0011-garden-linux-versioning.md
=> Add new ADR regarding GL versioning

.github/workflows/github.mjs, .github/workflows/tests.yml
This PR fixes two issues related to `.github/workflows/tests.yml` not validating correctly if a test environment is enabled.
=> Fix test environment checks in GH workflow

.github/workflows/manual_gh_release_page.yml, .github/workflows/publish_s3.yml
use glrd@v4 for semantic versioning support
=> feat: use glrd@v4 for semantic versioning support

README.md
=> Update README for the new versioning
