features/server/file.include/etc/sysctl.d/enable-unprivileged-user-namespaces.conf

This PR makes it possible for non-root users to use user namespaces.
User namespaces are used by rootless container tools. For example, [buildah](https://github.com/containers/buildah/), [img](https://github.com/genuinetools/img/), [rootless podman](https://github.com/containers/libpod), and more. 
Most distributions have this support automatically enabled - the Debian project disables this in their kernel builds. Enabling this will restore parity with CoreOS and SuSE.
```improvement user
User namespaces are enabled for non-root users.
```

Enable user namespaces for non-root users

---

ci/README.md
ci/integrationtest-run.yaml
ci/integrationtest-task.yaml

This PR adds a initial tekton task to run integration test within a pipeline.
The tested images are currently hardcoded and all available cloudproviders are currently tested.
In the future we want to have dynamic images depending on the current dev version.
And we only want to test certain versions to run build, upload and tests in parallel.
- AWS is working as expected (only IPV6 is not working)
- GCP is not correctly working as SSH is not working
co-authored: @dguendisch 
cc @msohn

Add initial integration test task

---

bin/debuerreotype-config

All the included files in the final image from the file.include directory (from features) are going to have wrong owners depending on which user cloned the repository.
Fixes https://github.com/gardenlinux/gardenlinux/issues/4#issuecomment-620411860

fix user/group ownership of file.include files

---

Makefile
bin/make-gcp-ami

Make GCP images public by default
Fixes #
https://cloud.google.com/compute/docs/images/managing-access-custom-images#share-images-publicly
```improvement operator
The script uploading the GCP images is now making them available to all authenticated GCP users.
```

Make GCP images public by default

---

ci/render_pipeline_run.py
ci/task.yaml
ci/tkn/model.py

- Adds an in-memory volume to the build pods (to be used to expedite builds later on)
- Adds memory-requests and -limits to the build pods due to the new in-memory volume
- Adds a node-selector to pods spawned by the pipeline-run to select machines that are more memory-optimised.

Improve build-pipeline

---

ci/integrationtest-run.yaml
ci/integrationtest-task.yaml

Adapts the tekton task for the integration tests to respect the newly introduced `--iaas` flag.
The taskrun now demonstrates the usage with the `aws` infrastructure.
Only when we integrate the tasks into a pipeline can we run e.g. an aws- and a gcp-task in parallel.

Adapt tekton task to integration test --iaas option

---

Dockerfile
features/server/exec.config

Add libcap2-bin to the Dockerfile so that getcap is available for the unit tests not running chrooted.
Change permissions for the wheel sudo rules as they get flagged by "visudo -c" and a lot of others that are based on that (e.g. tiger)

Small fix - getcap / sudoers permissions

---

hack/nginx.conf

only one request will be allowed to populate a new cache-element, i.e. other requests that hit the same cache-entry have to wait until the first request has updated the cache.
After the timeout (currently `30s`), they will nonetheless bypass the cache **without** updating it.

Add cache-lock to hack/nginx.conf

---

tests/Pipfile.lock
tests/integration/test_gardenlinux.py

- use ping6 instead of ping
- ping 2001:4860:4860::8888 instead of 8.8.8.8
- also ping dns.google
- update dependencies of integration tests
Fixes #
<!--  Write your release note:
1. Enter your release note in the below block.
2. If no release note is required, just write "NONE" within the block.
NONE

Fix ipv6 ping tests

---

hack/libdb/py27-remove-libdb.diff
hack/libdb/py27.sh

Remove Berkley DB from python2.7 packages.
Fixes #

remove libdb from python2.7

---

hack/libdb/py27.sh
hack/libdb/py37.sh
hack/libdb/py38.sh

The packages, after getting built, don't get moved to the proper place because of incorrect permissions.
Fixes

Python package build - fix permissions

---

hack/packages/apt
hack/packages/apt.patch
hack/packages/python2.7.patch

Remove ftparchive from apt-utils so BerkeleyDB is no longer needed for apt.
Update for the python 2.7 patch getting rid of the _bsddb module.
Fixes #

python 2.7/apt fixes

---

bin/makef.sh
features/server/pkg.include

This PR enables project quotas on the ROOT filesystem for GardenLinux images.
Fixes #62 
```improvement user
GardenLinux now supports enabling the kubelet `LocalStorageCapacityIsolationFSQuotaMonitoring` feature gate. 
```

Enable project quotas on the ROOT filesystem

---

features/cloud/file.include/etc/ssh/sshd_config

Enable TCP forwarding to be able to ssh to garden-linux host via ssh forwarding.
```improvement operator
None
```

Allow tcp forwarding

---

ci/cicd.yaml
ci/glci/azure.py
ci/glci/model.py

Adds a script that copies an object from s3 to an Azure storage account and updates an Azure plan to use it. This should enable us to automate our uploads to Azure.
Fixes #
see `copy_image_and_publish_offer` for a list of required parameters. Also requires a release of our cc-utils to add the required config classes

add initial version of azure marketplace upload

---

features/azure/image

Sets the size of the built Azure image to exactly 4 GB

ensure Azure image size is exactly 4GB

---

features/azure/image

First, revert previous change as Azure is calculating in GiB, thus the previous size param resulted in exactly the right size as per local testing.
Second, use the force_size option as suggested by the Azure documentation.
For more information, see
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-generic#resizing-vhds

Take another shot at the azure image upload

---

features/gardener/file.include/etc/docker/docker.conf

Fixes #81 
Based on the suggestion in item (2) in https://github.com/golang/go/issues/37436#issuecomment-593315935 .
```noteworthy user
Allows Golang 1.14 binaries to run correctly by increasing the default max memory lock ulimit size for Docker containers.
```

Added a default-ulimit setting for max memory lock size of 64Mb.

---

features/server/exec.config

Add new version of gnutls
Fixes security issue CVE-2020-13777 in libgnutls
@gehoern  please review
```improvement user
Fix CVE-2020-13777 in gnutls
```

Fix for CVE https://security-tracker.debian.org/tracker/CVE-2020-13777

---

features/gardener/exec.config

By installing the debian package containerd, Gardenlinux already contains the file containerd config file in /etc/containerd/config.toml.
Gardener does not override an existing containerd config, and as a consequence does not generate the default configuration file.
This is currently not a problem, but could become one in the future, when Gardener adds support for containerd configuration via the Shoot.yaml.
Fixes #
I tested `containerd` running successfully with `gardenlinux` using a  version of the Gardener that [includes this fix](https://github.com/gardener/gardener/commit/6886fbe56daebba7d7537e13d710747149deb85b)  together with [this PR version of the …

Remove containerd config

---

Dockerfile
bin/.boot.pxe
bin/start-vm
features/_pxe/exec.config
features/_pxe/image
features/_pxe/pkg.include
hack/docker-compose.yml
hack/nginx.conf

Modified the _pxe feature in order to add the live-boot package and tweak the image (script) as to create a proper Initrd containing the complete image (without /boot) as squashfs. 
The start-vm script has also been modified so that it can start a live gardenlinux setup and boot from PXE. It can also load the needed files via http for better performance. (use --pxe)(needs the local nginx started)
start-vm can now be used to boot via pxe and get a live gardenlinux setup:
e.g.
./start-vm --pxelocal ../.build/gcp/20200616/amd64/bullseye/ disk_stuff.raw
Yes, a disk/image still needs to be provided, but can be blank, this must be improved.
Fixes #94

PXE support

---

features/server/file.include/etc/sysctl.d/allow-nonroot-dmesg.conf

Allows non-root users to use `dmesg`.
Fixes #96 
```improvement user
Non-root users can now use dmesg.
```

Unrestrict dmesg from non-root users

---

features/server/pkg.include

Add cifs-utils package to make it possible to mount cifs volumes on the nodes.
Fixes #
```noteworthy user
`cifs-utils` package is now part of the image
```

add cifs-utils package

---

hack/nginx.conf

Includes the latest changes to the live nginx cache config, namely:
- 'OK' and 'moved permanently' responses (200 and 301) are valid for 30d
- 'moved temporarily' responses (302) are valid only for one hour
- any other response expires after ten minutes

Contribute detailed nginx cache config back to gardenlinux-repo

---

features/server/exec.config
features/server/pkg.include

Fixes #109 
There's no easy way to install the `open-iscsi` package and have the daemon stay down. The `open-iscsi` package isn't integrated with systemd`s just-in-time socket activation functionality.
The overhead for this daemon seems to be small (around 10MiB) when it is just loaded.
```
root@localhost:/root# ps l 407 409
F   UID     PID    PPID PRI  NI    VSZ   RSS WCHAN  STAT TTY        TIME COMMAND
1     0     407       1  20   0   4904   284 -      Ss   ?          0:00 /sbin/iscsid
5     0     408       1  10 -10   5408  5020 -      S<Ls ?          0:00 /sbin/iscsid
```
```improvement user
GardenLinux supports mounting iSCSI volumes. 
This enables using …
```

Install open-iscsi by default

---

ci/glci/model.py
ci/glci/openstack_image.py
ci/promote.py
ci/requirements.txt

Add procedure to upload gardenlinux images to OpenStack environments.
~~For each OpenStack environment we need to create a `Openrc` object with proper access information. This need to be passed for each environment to the function `upload_image()` together with the name of the image, builddate and the path to the image vmdk file in the local filesystem.~~
Updated the PR. For each OpenStack environment we need a `glci.model.CicdCfg` which contain internally an `glci.model.Openrc` object with access information and image properties. The image is now uploaded directly via web url (e.g. S3 object url) to Glance instead of uploading it from file system.
It's now also integrated with the publish process.
cc @ccwienk 
```improvement …
```

Add OpenStack image build upload procedure

---

ci/cicd.yaml
ci/glci/az.py
ci/glci/model.py
ci/promote.py

The ci fetch now the configuration for the Azure publishing procedure from SecretServer correctly.
```NONE
```

Connect ci and Azure publishing procedure

---

ci/glci/alicloud.py
ci/requirements.txt

Share gardenlinux image to other accounts
Fixes #
```improvement operator
GardenLinux images are built for all regions on Alicloud and are made shared with other accounts.
```

make image shared hiddenly on Alicloud

---

bin/make-ova
docs/vmware-ova.md
features/vmware/image
templates/vmware.ovf.template

This allows make-ova to be used with different OS.
This also adds support for SUSE CHOST 15 SP2.
I'm not sure this is the right place in the script to add the GUEST_OS since the repo is for `gardenlinux`.
**Release note**: 
```improvement operator
NONE
```

Make make-ova os agnostic

---

features/gardener/file.include/etc/docker/daemon.json

The original intent in #82 was to set the ulimit to 64Mib.
Unfortunately, #82 set the limit to 64Kib. This PR fixes that.
64Kib is the default for Docker without any additional configuration. 64Mib is high enough to solve the original problem.
Fixes #81 correctly.
Can be verified by running `ulimit -l` in a container. The correct output should be:
```shell
$ ulimit -l
65536
```
The configuration file specifies the limit in bytes, while `ulimit` shows the limit in kilobytes.
```improvement operator
Allows Golang 1.14 binaries to run correctly by increasing the default max memory lock ulimit size for Docker containers.
```

Increase the memlock ulimit to 64Mib

---

ci/glci/az.py

We're currently uploading the unchanged rootfs for azure. This needs to be changed to the generated vhd files, which this PR does.

Fix azure release-artifact upload

---

features/server/file.include/etc/profile.d/50-nohistory.sh
features/server/test/history
features/server/test/history.chroot

This is going to disable the bash history. This is a SAP Security requirement.
Bash history is disabled.

Disable bash history

---

features/cloud/test/tmout
features/cloud/test/tmout.chroot
features/cloud/test/umask
features/server/test/debsums.chroot
features/server/test/packages_musthave.list
features/server/test/systemctl_enabled.list
features/server/test/user_groups.list

Small output fix for the debsums test - removing a debconf warning.
Adding a test for the presence of TMOUT.
Adding auditd to be checked if package is installed and if the service is enabled.
Updating groups for the user_groups test. 
NONE

Small tests updates

---

bin/garden-build.sh

Add the version in the pretty name.
In this way the OS version will be visible via k8s 
Currently, it is 
```bash
$  k get node -o wide
NAME                                          STATUS   ROLES    AGE   VERSION    INTERNAL-IP     EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION        CONTAINER-RUNTIME
ip-10-222-13-140.eu-west-1.compute.internal   Ready    <none>   35m   v1.17.12   10.222.13.140   <none>        Garden Linux   5.4.0-4-cloud-amd64   docker://19.3.7
```
After the change it will be something like 
```bash
k get node -o wide
NAME                                          STATUS   ROLES    AGE   VERSION    INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION        CONTAINER-RUNTIME
ip-10-222-13-140.eu-west-1.compute.internal …
```

Add the version in the pretty name

---

features/azure/pkg.include

After cursory testing The Microsoft Azure Linux-Agent does not seem to depend on python2 anymore. My current best guess for the required python version is 3.8+, as given by https://github.com/Azure/WALinuxAgent/blob/develop/requirements.txt

rm python2 from azure build

---

features/server/test/autologin
features/server/test/user_groups.chroot

Fixes the failing autologin test when the _dev feature is not used.
Ignores the "dev" user from the users-groups test when the _dev feature is used.

Fix autologin test / users-groups test

---

features/gardener/exec.config
features/gardener/pkg.include

The fixed docker version has reached `testing` so we can unpin it now.
This reverts commit 93f71b332296185263adb026d15e1ebf1e59d87a.
Fixes #138 
```improvement developer
The docker version is no longer pinned to `19.03.13+dfsg1-2` but is regularly updated from the testing branch of Debian.
```

Unpin docker version

---

bin/makef.sh

changes the order when quota features are introduced to the fs. This reduces the dependency on a quota module in the building environment's kernel.

moved the quota creation after the disk buildout

---

Makefile

Fix build error if .build directory does not exist.
Fixes #152 
```improvement user
Fix build error if .build directory does not exist.
```

Fix build problem if build directory .build does not exist

---

ci/integrationtests/pipeline.yaml
ci/integrationtests/pipelineresource.yaml
ci/integrationtests/pipelinerun.yaml
ci/integrationtests/task.yaml
ci/integrationtests/taskrun.yaml
tests/integration/gcp.py
tests/test_config.yaml

Refactors the tekton part of the integration tests by making parameters like image name configurable and adding an example pipeline.
In addition:
- removes the pipenv dependency and uses only pip to install requirements.
- allows to have a different gcp image project than the project used to create the test VM.

Refactor integrationtests pipeline

---

Dockerfile
packages/Dockerfile
repository/Dockerfile
snapshot/Dockerfile

Signed-off-by: Christian Berendt <berendt@23technologies.cloud>

Set DEBIAN_FRONTEND to noninteractive in Debian docker images

---

features/gardener/file.include/etc/systemd/system/containerd.service.d/override.conf

Downport fix for #168 to Garden Linux 184
Fixes #168
Tested with containerd: I started a debian container with containerd and verified that the mlock limit is set to the previously configured value:
```
max locked memory       (kbytes, -l) 65536
```
```improvement containerd
Set LimitMEMLOCK (mlock) parameter to 64MB for containerd and spawned containers.
```

Set mlock limit for containerd and containers

---

features/chost/exec.config

Upgrade to kubernetes version 1.19 the download link for crictl was broken

fix v1.19 download link

---

features/gardener/file.include/etc/docker/daemon.json

I’m working with advanced Docker Proxy. 
This requires reconfiguration of Docker on every Node (/etc/systemd/system/docker.service.d/http-proxy.conf),
daemon-reload, and restart docker.service.
Restart – during bootstrapping - crashes already running container on the Node.
To prevent such crash, /etc/docker/daemon.json should have setting “live-restore: true”

for advanced Docker Proxy.

---

tests/integration/test_gardenlinux.py

This PR adds support to the integration test to validate that all systemd units are started successfully.
Fixes #5

Add support to test if all systemd units are started successfully

---

bin/.snapshot-url.sh
bin/debuerreotype-debian-sources-list
ci/glci/alicloud.py
hack/nginx.conf
hack/raspbian.sh
hack/steamos.sh
packages/Dockerfile
packages/coreutils
repository/repo.sh
repository/settings
snapshot/Dockerfile

Packages are verified by signatures after being downloaded from mirrors. For further enhancement of the integrity this PR replaces non-secure URLs. This change focuses on documented recommendation from e.g. Debian [1] and possible MITM attacks being easily possible without the change. As gpg validation (e.g. for debootstrap) can be deactivated and bootstrap is done from mirrors without user interaction and validation using secure URLs would at least enhance safety to access trusted locations for the later relevant gpg keys in use.
Please note that Ubuntu does not use secure URLs as no TLS support is given at the time of this PR. gpg integrity should be enhanced in other ways here like
[1] e.g. https://wiki.debian.org/DebianRepository/UseThirdParty

Use secure URLs if possible for accessing mirrors

---

features/cloud/exec.config

No PR. We need it to support WireGuard in our Kubernetes clusters.
Fixes #
```improvement user
Add WireGuard module
```

Add WireGuard support

---

features/cloud-anvil/file.include/usr/lib/dracut/modules.d/98gardenlinux/usr-mount.sh
features/cloud/file.include/usr/lib/dracut/modules.d/98gardenlinux/usr-mount.sh

Temporary fix for the usr mount service breaking the boot process.

Temp fix for usr mount service

---

bin/.boot.pxe
bin/start-vm
features/_pxe/exec.config
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.service
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/sd-module-setup.sh

Omit gardenlinux dracut module if included by other feature(s) when live booting.
Properly start systemd-resolved in dracut.

PXE bug fixes

---

features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/module-setup.sh
features/_pxe/image

Calculate the hash of the squashfs, "bake" it into the initrd so that it can be verified while PXE booting.

PXE verify hash of squashfs

---

features/_pxe/exec.config
features/cloud/exec.config
features/server/exec.config
features/server/file.include/etc/dracut.conf.d/general.conf

Reproducibility was/is broken for multiple reasons:
1. timestamps of files included in the initramfs
timestamps will be based on dracut-functions.sh which is coming from the dracut packages
2. /etc/iscsi/initiatorname.iscsi containing an ID generated on first start
reverting to GenerateName=yes - iqn will be generated on first daemon start and once set it won't be regenerated
3. remove __pycache__ from /usr/lib/python3.8 
generation of .pyc files is not reproducible - step takes place in the post install step of the python3.8 package

Reproducibility fixes

---

bin/garden-debian-sources-list

The following repositories security.debian.org/debian-security and archive.debian.org/security and archive.debian.org/debian-security don't provide https access.
Fixes #

repositories - remove https for repos that don't have it

---

bin/garden-build.sh
build.sh

Add --skip-tests flag to skip running the tests when building.

Tests - skip tests when building

---

bin/makef.sh

Add the discard mount option for / and /usr

mount options - add discard mount option for root/usr

---

Dockerfile
Makefile

- no Makefile target did build the docker image by default
- wrong path in Dockerfile for debootstrap.path
/kind TODO
/area os
Fixes #
```other operator
```

Fix build failures

---

build.sh

Stop build container on ctrl-c.

Stop build container on ctrl-c

---

features/cloud/exec.config
features/cloud/file.include/usr/share/pam-configs/garden-extra
features/server/test/debsums_exclude.list
features/server/test/dev
features/server/test/dev_files
features/server/test/password_hashes

Add test for yescrypt password hashes.
Improve dev test from server feature.
Remove /usr/share/pam-configs/cracklib to remove any warnings.

Small PAM and test improvements

---

features/aws/file.include/usr/lib/dracut/modules.d/98gardenlinux/clocksource-setup.sh
features/cloud/file.include/usr/lib/dracut/modules.d/98gardenlinux/module-setup.sh

This is according to https://aws.amazon.com/de/premiumsupport/knowledge-center/manage-ec2-linux-clock-source/#:~:text=The%20recommended%20clock%20source%20for,Nitro%20Hypervisor%20is%20kvm%2Dclock
/area os
Fixes #
```feature operator
set correct clocksource on AWS according to hypervisor
```

Set correct clocksource for aws according to hypervisor

---

features/gardener/file.include/etc/docker/daemon.json

/kind TODO
/area os
/priority high
Fixes #
```other operator
Docker 20 has changed the default cgroup driver to systemd which
breaks the kubelet. This commit is chaning this back to cgroupfs.
```

Change Docker cgroup driver back to cgroupfs

---

VERSION
bin/makef.sh
features/cloud/exec.config
features/server/exec.config
features/server/pkg.include

/kind security
/area os
- Add openssl 1.1.1j-1 which resolves above mentioned CVE.
- quiet several uses of wget in scripts to reduce log cluttering
- add package netcat
Fixes CVE-2021-23841 
```other operator
Fix openssl CVE-2021-23841 
```

Fix openssl CVE-2021-23841 plus minor housekeeping

---

features/ali/exec.config
flavours.yaml

/kind bug
/area os
Downgrade cloud-init from 20.4 to 20.2 due to a bug in cloud-init on alicloud. The cloud-init bug has been reported: 
https://bugs.launchpad.net/cloud-init/+bug/1917875. 
Fixes #
```other operator
Downgrade cloud-init from 20.4 to 20.2 due to a bug in cloud-init on alicloud. cloud-init downgrade is only for alicloud.
```

Downgrade cloud-init for AliCloud

---

ci/cicd.yaml
ci/glci/az.py
ci/glci/model.py
ci/promote.py

In our most recent round of publishing we've received an error from Azure that indicates that a list of email-recipients to notify on status updates is missing.
This PR adds the config and passes it through to the azure build.

Configure recipients for azure publishing-notifications

---

Makefile

/kind cleanup
/area os
If i just run `make`, I get:
```
mbanck@lightning:~/hacking/git/gardenlinux$ make
make: 'cert/sign.pub' is up to date.
```
This PR moves the `all` target to be the first Makefile target, so instead then I get:
```
mbanck@lightning:~/hacking/git/gardenlinux$ make
make --directory=docker build-image
make[1]: Entering directory '/home/mbanck/hacking/git/gardenlinux/docker'
WARNING: You are still using a debian:testing-slim as a temporary replacement of gardenlinux/slim:latest!
Please run 'make slim' to fix
Sending build context to Docker daemon  4.608kB
Step 1/12 : FROM        gcr.io/kaniko-project/executor:latest as kaniko
[...]
```
**Which issue(s) this PR …

add default make target

---

features/server/test/machine_id

/kind TODO
/area os
Fixes #
```other operator
```

tests - allow for uninitialized machine-id

---

Makefile
features/ali/pkg.include

Ali pkg.include did contain cloud-init which is currently
installed manually (until the cloud-init fix for Ali has
reached upstream).
/kind bug
/area os
Fix Makefile.
Fixes #
```other operator
Fix Makefile
```

Makefile fixes and Ali fix

---

features/azure/exec.config

/kind bug
/area os
/priority 5
Overwrite waagent config after it is installed
Fixes #
```bugfix user
[Azure] Fix a bug that prevented the `waagent` to execute the user data of the VM.
```

Overwrite waagent config after it is installed

---

features/azure/exec.config

Cherry pick of #243 on rel-318.
#243: Overwrite waagent config after it is installed
**Release Notes:**
```bugfix user
[Azure] Fix a bug that prevented the `waagent` to execute the user data of the VM.
```

[rel-318] Automated cherry pick of #243: Overwrite waagent config after it is installed

---

bin/garden-build.sh

/area os
Temporary hard-code the version of GL to 318.4 in /etc/os-release
Fixes #
```other operator
```
/invite @AndreasBurger @ccwienk

Temporary hard-code the version of GL to 318.4 in /etc/os-release

---

features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.service
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-overlay-setup.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-sysroot-generator.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/squash-mount-generator.sh

Early boot services, for live booting, have to receive `DefaultDependencies=no` for proper ordering.

PXE - set DefaultDependencies to no

---

security-response-process.md

/area security
For our [CII Badge](https://bestpractices.coreinfrastructure.org/en/projects/3925) Garden Linux requires a Security Response Process description and a Security Team
The referenced google groups are not yet created and can be discussed
Security Response Process and Security Team defined.

initial commit for Security Response Process

---

packages/Makefile

/kind bug
/area os
This makes the default Makefile target in the `packages` subdirectory import the gardenlinux key before package build, so that the packages can be signed with it and the package building process does not error out.
Fixes #234
```other operator
```

import gardenlinux key before building packages

---

VERSION
features/cloud/exec.config
features/gardener/exec.config
features/gardener/pkg.include

/kind bug
/area os
bug fixes, security fixes
Fixes
- https://github.com/gardenlinux/gardenlinux/issues/251
- https://security-tracker.debian.org/tracker/CVE-2021-30465
- bind9: https://security-tracker.debian.org/tracker/CVE-2020-8625
```other operator
Update runc to fix #251 and security fixes (CVE-2021-30465, CVE-2021-30465).
```

Address several runc issues and security updates

---

features/ali/exec.config
features/ali/pkg.include

/kind TODO
/area os
Fixes #
```other operator
Fix reference to previous cloud-init version for ALI compatibility
```

Fix reference to previous cloud-init version for ALI compatibility

---

features/cloud/test/packages
features/cloud/test/packages.validate

/kind TODO
/area os
Fixes #
```other operator
```

Add test to make sure wireguard is installed

---

bin/.snapshot-url.sh
bin/garden-init

This adds support for a "gardenlinux" archive base in snapshot-url, as well as
a check in garden-init whether the gardenlinux-specific packages are present in
the selected snapshot mirror. If they are not, the new above "gardenlinux"
archive base is queried via snapshot-url and this one used instead.
/area os
Fixes #237
```other operator
```

add support for a second mirror that serves gardlinux-specific packages.

---

packages/manual/linux-5.10
packages/manual/linux-5.4

/area performance
This PR enhances kernel package building. It does the following:
* improve git cloning for both Debian kernel package repo and the linux-stable repo
The Debian kernel repo (previously 800-900 MB download) is switched to two shallow clones (2 and 7 MB download)
The linux-stable kernel is needed for the changelog, so cannot be switched to a shallow clone, but at least (as only commit information is needed, no actual source code) can be switched to a bare repository and only the branch in question needs to be cloned. This improves required bandwidth from around 3.5 GB to 1.8 GB. 
In my testing, the functionality as far as the kernel package build needs …

Reduce git cloning download size during kernel package build

---

bin/garden-init
features/khost/exec.config

Make the build log a bit less verbose when downloading the custom files/debian packages.
Remove the .wget-hsts file as it breaks reproducibility. 
Introduce a hackish way of skipping the dracut generation in the garden-init stage in order to speed up the build process.

Small fixes/improvements

---

features/ali/exec.config
features/ali/pkg.include
flavours.yaml

/kind bug
/area os
/priority 1
/platform alicloud
Fix the cloud-init installation for Alicloud, as with the latest version the VMs cannot be initialized properly
Fixes #
```other operator
```

Install the hard-coded cloud-init version

---

flavours.yaml

/kind cleanup
/area os
/priority 3
Enable again all flavours after #264
Fixes #
```other operator
```

Enable again aws, azure, gcp, openstack and vmware flavours

---

features/kvm/pkg.include

/area os
kexec is needed in the kvm feature of gardenlinux, otherwise we can not install the os from ram to disk.

added kexec-tools to kvm feature

---

packages/manual/linux-5.10

We need to stick to the defined debian kernel version in packages/manual/linux-5.10.d/VERSION if a newer debian version is available.

Packages - linux kernel package stick to defined debian version

---

.ci/clean_build_result_repositories
.ci/pipeline_definitions
.ci/run_integration_tests
ci/lib.sh
ci/render_pipelines_and_trigger_job

/kind TODO
/area os
* Do not build packages on every commit (manual triggering)
* Disable notifications from Concourse (avoid double notifications)
NONE

ci: Concourse split build and disable notifications

---

bin/.snapshot-url.sh
ci/render_pipeline_run.py
ci/render_task.py
ci/steps.py
ci/steps/build_cert.sh
ci/steps/build_cfssl.sh
ci/steps/build_kernel_package.sh
ci/steps/build_package.sh
ci/steps/write_key.py
ci/tasks.py
packages/manual/linux-5.10
packages/manual/linux-5.10-signed
packages/manual/linux-5.10.d/sign-helper

Adjust the existing build-scripts so that centrally built packages are now also signed and used.
Also includes some refactoring to the ci-gear to remove the last inlined build-scripts.

Sign centrally build packages

---

features/cloud/pkg.include
features/gcp/pkg.include
features/kvm/pkg.include

/area os
GCP and KVM features of Garden Linux install `rng-tools-debian` for gathering entropy from the hardware random generator provided by virtio-rng. As recommended in the package description of [rng-tools-debian](https://packages.debian.org/bullseye/rng-tools-debian) and [rng-tools](https://packages.debian.org/bullseye/rng-tools) this PR changes the package to rng-tools5.
It also fixes the cosmetic issue of systemd complaining about a missing unit file as rng-tools-debian still uses Sys-V init-scripts, rng-tools5 uses native systemd units.
Also adds the rng-tools5 packages to AWS and Azure feature sets to allow for faster collection of entropy on those platforms.
**Which …

Replace package rng-tools-debian with rng-tools5

---

.gitignore

/kind cleanup
/area os
Most Gardener repositories have a dedicated `dev` folder which is `.gitignore`d to place temporary files that accumulate during development activities. This PR adds such a folder to GardenLinux' `.gitignore` file.
```feature user
Have a dev folder in the projects .gitignore.
```

Add dev folder to gitignore

---

features/cloud/exec.config

For the DEBIAN_FRONTENT to noninteractive for the pam-auth-update commands.

noninteractive pam-auth update

---

ci/glci/alicloud.py
ci/glci/aws.py
ci/glci/az.py
ci/glci/gcp.py
ci/glci/model.py
ci/glci/openstack_image.py
ci/glci/util.py
ci/promote.py
ci/render_pipeline_run.py
ci/render_pipelines_and_trigger_job
ci/render_task.py
ci/steps.py
ci/steps/component_descriptor.py
ci/tasks.py

Adds another step to the promote task of the image-build-pipeline that builds and publishes a Component Descriptor for the current build, if configured.
The required publishing-action is not (yet) set by default, so merging this should be super safe.
For an example, see [this](https://github.com/gardenlinux/gardenlinux/files/6939055/example-cd.txt) descriptor.

Add step publishing Component Descriptor

---

features/chost/file.include/etc/systemd/system/containerd.service.d/override.conf

/area os
Increase memlock ulimit for containerd for the chost feature (clone from gardener)

chost feature - memlock limit for containerd

---

bin/.constants.sh
bin/garden-build.sh
bin/garden-config
bin/garden-init

/kind bug
/area os
Keeping the order of the features is really important, when removing duplicate features, the list of features got sorted. This commit introduced this bug : https://github.com/gardenlinux/gardenlinux/commit/2893b35f12c737c3df74cf9d99eecd25892436d6

Keep the order of features

---

features/cloud/file.include/usr/lib/dracut/modules.d/98gardenlinux/module-setup.sh
features/metal/file.include/usr/lib/dracut/modules.d/98gardenlinux/module-setup.sh
features/metal/file.include/usr/lib/dracut/modules.d/98gardenlinux/sysroot-usr-fsck.service
features/metal/file.include/usr/lib/dracut/modules.d/98gardenlinux/sysroot-usr.mount
features/metal/file.include/usr/lib/dracut/modules.d/98gardenlinux/usr-mount.sh

/kind bug
/area os
Sync the gardenlinux dracut module used in the metal feature with the one from the cloud feature. Add "tr" to the module setup as this is missing from base/dracut-systemd and is going to break the rootfs generator.

Fix metal feature / gl dracut module

---

features/azure/exec.config
features/azure/file.include/etc/chrony/chrony.conf
features/azure/file.include/etc/udev/rules.d/60-udev-hyperv.rules

/area os
Azure recommends in https://docs.microsoft.com/en-us/azure/virtual-machines/linux/time-sync to use PTP. As systemd-timesyncd does not support PTP so it is deinstalled and chrony is being used as proposed in the linked document.
As there might be multiple /dev/ptp devices a udev role has been added to create a stable symlink /dev/ptp_hyperv.
Fixes #
```feature user
This PR changes way VMs on Azure acquire their time from NTP to PTP.
```

Azure clock source

---

README.md

/kind doc
/area os
Clarifies that build results are put into `.build/` (hidden directory), not (as previously stated) `build/`

Clarify build result folder

---

Makefile

/kind cleanup
/area os
Add the metal/metal-dev platform to the `all_prod/all_dev` Makefile targets

Add metal/metal-dev to add_prod/all_dev targets

---

features/gcp/exec.config

/kind bug
/area os
On GCP the wrong file was edited for the correct NTP server. This patch fixes it.
Fixes #
```feature user
Garden Linux on GCP now uses the Google NTP server.
```

Fix NTP server for GCP

---

Makefile

/kind cleanup
/area os
Make clean would delete all containers coming from gardenlinux/build-image
and the image itself, all other container images however would remain.
By calling the clean target of the Makefile within the docker directory,
all container images that were built during a Garden Linux build will be
removed.
Building a Garden Linux release would build both, the build-image and
the integration test image (and others). With this change to the Make
file, only the build container image is created, speeding up the process
significantly. The integration test container image is only built on
demand. …

fix: delete all container images on make clean

---

bin/garden-init

Installation of additional packages via debootstrap may or may not work.
The included dependency resolver is limited.  Instead just use apt-get
to do the heavy lifting.
/area os

Install extra packages via apt

---

packages/manual/google-guest-agent

/area packages
This change uses the Ubuntu source package for google-guest-agent instead of the upstream sources. Upstream sources pull in dependencies from GitHub and need network access for package build. Ubuntu has a working package with the Golang dependencies vendored into the `debian/` directory, which is not nice, but nicer.
I have not tested a full rebuild yet, only the one package script alone.

Rebuild Ubuntu source package for google-guest-agent

---

ci/glci/aws.py

/area os
Adds a tag to AWS AMI IDs to trigger an exception of certain security scans in the Garden Linux AWS account where the images are published.
Fixes #315 
```feature developer
ci[aws]: add tags for image security scanning
```

ci[aws]: add tags for image security scanning

---

.gitignore
docker/Makefile
docker/integration-test/Dockerfile
tests/Pipfile
tests/Pipfile.lock
tests/README.md

/kind cleanup
/area os
The container image for integration tests did not have all required Python modules so far, they had to be manually installed with `pipenv`. With this PR, `pipenv` gets called during the build of the container image so that all requirements are met and a manual step can be omitted. The documentation was updated to reflect the change.
```feature user
refactor(integration-tests): improve container for integration tests
```

refactor(integration-tests): improve container for integration tests

---

features/server/file.include/etc/kernel/cmdline.d/90-selinux.cfg

/area os
Add security=selinux to enable selinux (permissive mode, as default in /etc/selinux/config).
Fixes #333

Add security=selinux kernel parameter

---

features/azure/exec.config
features/azure/file.include/etc/systemd/system/walinuxagent.service.d/10-startpost.conf
features/azure/pkg.exclude
features/azure/pkg.include
tests/integration/test_gardenlinux.py

/kind bug
/area os
This PR fixes several issues with startup errors, unnecessary startup scripts, long startup times, and improves the build script:
* Use waagent 2.2.47-2.2 with the python 3.9 fix. We tried the latest waagent provided by Debian but this had two issues: 
* Waagent returns prematurely before network configuration is finished. systemd-networkd is restarted after waagent startup finishes to pick up the local hostname. This does not work as waagent is not yet done. 
* In some cases we see high CPU consumption by a kworker process that is somewhat caused by waagent. Upon stopping waagent this problem goes away.
* long startup times were caused by waagent attempting to launch non-existing …

Fix azure build and tests

---

ci/glci/oci.py
ci/promote.py
ci/steps.py
ci/steps/component_descriptor.py
ci/steps/upload_results_step.py

/area delivery
Image builds will always publish the created OCI images to GCR at `eu.gcr.io/gardenlinux/gardenlinux`. They will be tagged with `<version>-<canonical release manifest key suffix>` (e.g.: `535.0-oci-base--build-535.0-96be22`).
If a Component Descriptor is to be built, it will also include these published images as resources:
```
…
{
'access': {
'imageReference': 'eu.gcr.io/gardenlinux/gardenlinux:535.0-oci-base-535.0-96be22',
'type': <AccessType.OCI_REGISTRY: 'ociRegistry'>
},
'extraIdentity': {},
'labels': [{
'name': 'gardener.cloud/gardenlinux/ci/build-metadata',
'value': {
'modifiers': ('_slim','base')
}
}],
'name': 'gardenlinux',
'relation': <ResourceRelation.LOCAL: …
```

Publish Built OCI-Images to GCR and Include Them in Component Descriptor

---

bin/make-ec2-ami

/kind cleanup
/area os
Adds a tag to AWS AMI IDs in `make-ec2-ami` to trigger an exception of certain security scans in the Garden Linux AWS account where the images are published.
Fixes #315
```feature user
fix: add security tags to make-ec2-ami
```

fix: add security tags to make-ec2-ami

---

bin/make-azure-ami
tests/integration/azure.py

/kind bug
/area os
Some tools to interact with Azure (and which are used in integration tests) did submit the subscription ID which made them fail if said ID was not somewhere in the environment. Fixed with this PR.
```feature user
tests(Azure): add subscription ID to all az calls
```

tests(Azure): add subscription ID to all az calls

---

features/openstack/file.include/etc/systemd/system/systemd-resolved.service.d/resolv.conf

/kind bug
/area os
Our CC EE colleagues recommend the following options in /etc/resolv.conf:
```
options rotate timeout:1
```
Unfortunately there is no obvious way to configure systemd-resolved to do that, however the systemd-resovled has this functionality built in. This PR changes the symbolic link from /etc/resolv.conf to point to the /run/systemd/resolve/stub-resolv.conf file. 
Fixes #326
```feature user
Configure openstack image according to the recommendations of our CC EE colleagues.
```

Change dns server in resolv.conf to point to local revolver

---

features/gardener/pkg.include

netcat was deprecated in Debian. We use anyhow most of the time socat, but some SRE requesting netcat to be present in Gardener environments.

reenabling netcat for debugging

---

packages/Makefile

.packages folder is not created. so all docker builds are in some docker volume

create .packages folder

---

features/vmware/file.include/etc/cloud/cloud.cfg.d/99_enabled-datasources.cfg
features/vmware/file.include/usr/bin/dscheck_VMwareGuestInfo
features/vmware/file.include/usr/lib/python3/dist-packages/cloudinit/sources/DataSourceVMwareGuestInfo.py
features/vmware/pkg.include

/area os
This patch adds support for the Cloud-Init Datasource, VMwareGuestInfo, to the VMware image. The files in this commit were copied from release `v1.4.1` of the datasource from https://github.com/vmware/cloud-init-vmware-guestinfo.
The datasource has a dependency on the `netifaces` library, and so the package `python3-netifaces` was added to the package file for the `vmware` image.
The patch was verified by:
1. Building the VMware image:
```bash
make vmware
```
2. Verifying the cloud-init datasource's files were copied into the image correctly:
```bash
$ tar vtf .build/vmware/20210718/amd64/bullseye/rootfs.tar.xz | grep 'DataSourceVMware\|dscheck_VMware'
-rw-rw-r-- 0/0 …
```

vmware: Support cloud-init datasource GuestInfo

---

bin/garden-chroot
features/openstack/file.include/etc/resolv.conf
features/openstack/file.include/etc/systemd/system/systemd-resolved.service.d/resolv.conf
features/server/file.include/etc/resolv.conf
features/server/file.include/etc/systemd/system/systemd-resolved.service.d/resolv.conf

/area os
Related to #369 - remove the handling of the resolv.conf symlink from the drop-in for systemd-resolved and just include the proper symlink in the image via file.include

resolv.conf symlinks

---

docs/openstack.md
features/openstack/README.md

/kind documentation
/area os
This PR adds some documentation which clearly mentions that the current OpenStack feature set is a reference
implementation that is designed for the (not so common) CCEE setup with ESXi as hypervisor.
```feature user
docs: clearly mention OpenStack reference implementation
```

docs: clearly mention OpenStack reference implementation

---

bin/make-ec2-ami

/kind bug
/area os
PR #389 (which I apparently approved a bit too quickly) introduced a non-working function call to make-ec2-ami. Fixed by this PR.
```feature user
user: fixes internal bug in make-ec2-ami
```

bug: fix wrong function call in make-ec2-ami

---

features/openstack/file.include/etc/resolv.conf

/kind bug
/area os
Remove the /etc/resolv.conf symlink pointing to /run/systemd/resolve/stub-resolv.conf. Keep the default pointing to /run/systemd/resolve/resolv.conf coming from the server feature.

remove resolv.conf symlink from openstack

---

packages/manual/linux-5.10

Fixes absent cert-file for the central build

Handle multiple paths for the kernel.full cert

---

cert/Makefile
ci/params.py
ci/render_all.py
ci/render_pipeline_run.py
ci/render_pipelines_and_trigger_job
ci/render_task.py
ci/steps.py
ci/steps/build_cert.sh
ci/steps/build_cfssl.sh
ci/tasks.py
docker/build/Dockerfile
docker/build/install-cfssl.sh

Instead of building cfssl once in every task that needs it, this PR changes it so that a version of cfssl is included in the build-image. This version is then used during the central build process, if configured.

CI: Don't build cfssl from scratch for every build

---

tests/README.md
tests/integration/manual.py
tests/integration/test_gardenlinux.py

/area os
The integration/platform tests we have so far create VMs in hyperscalers all automatically. In case this fails for whatever reasons or the tests should just run on an already built-up machine, the proper pytest fixtures were missing for that.
```feature developer
- test(manual):  allow tests on prepared hosts
```

test(manual):  allow tests on prepared hosts

---

ci/steps/component_descriptor.py

Previously, the component-descriptor publication was limited even if configured - first to releases, then to release-candidates. This PR finally removes this limitation, as our consumers downstream have been configured to react only to releases.

Always upload component-descriptor (if configured)

---

bin/makepart

/kind bug
/area os
Fixes issue with bootctl in makepart if `/tmp` is not mounted as a tmpfs
**Origin of the issue:**
- If `/etc/machine-id` is not on a tmpfs mount then bootctl's `--make-machine-id-directory` arg will default to yes ([man bootctl](https://man7.org/linux/man-pages/man1/bootctl.1.html#:~:text=%22auto%22%20is%20equivalent%20to%20%22yes%22%20if%0A%20%20%20%20%20%20%20%20%20%20%20/etc/machine-id%20resides%20on%20a%20filesystem%20other%20than%20tmpfs%20and%0A%20%20%20%20%20%20%20%20%20%20%20%22no%22%20otherwise))
- makepart executes bootctl in a chroot on `/tmp`, so if `/tmp` is not a tmpfs `/etc/machine-id` also won't be on a tmpfs  
&xrArr; bootctl will attempt to use the machine-id, which …

makepart: fix bootctl not working if /tmp is not mounted as a tmpfs

---

.ci/pipeline_definitions
ci/README.md
ci/glci/model.py
ci/lib.sh
ci/params.py
ci/promote.py
ci/render_pipeline_run.py
ci/render_pipelines_and_trigger_job
ci/steps.py
ci/steps/attach_logs.py
ci/steps/build_base_image.py
ci/steps/component_descriptor.py
ci/steps/pre_build_step.py
ci/steps/pre_check_tests.py
ci/steps/promote_step.py
ci/steps/release_step.py
ci/steps/run_tests.py
ci/steps/upload_results_step.py
ci/steps/upload_test_results.py

/area os
* CI: replace publishing action by buils-targets
* CI: add option to use an existing base image during build (env var: GARDENLINUX_BASE_IMAGE)

Ci publishing action onstable

---

ci/cleanup_namespaces
ci/lib.sh
ci/render_pipelines_and_trigger_job

Moves the pipelines created by each Git-branch to their own k8s-namespace. The name of the namespace is derived from the branch-name by replacing all non-alphanumeric characters with `-` (Note: This will still fail if the branch starts/ends with a non-alphanumerical character, but at least the error message should be self-explanatory).
Also provides a script that can autmatically clean-up namespaces that did not see any testrun within the last 20 days (not yet added to pipeline-def)

Ci: Move each branches pipelines to their own namespace

---

ci/render_task.py
ci/steps/build_kernel_package.sh
ci/steps/build_package.sh
ci/steps/clone_repo_step.py
ci/tasks.py

With Tekton version `v0.24.0` (we use `v0.21.0`, most recent is `v0.29.0`) some overrides that we currently rely on are removed. This PR prepares our pipelines for upgrades of Tekton past `v0.24.0`.
The necessary changes are actually rather small:
- explicitly set `HOME` to a directory in the shared `\workspace` (currently `\workspace\tekton_home`) and make sure it exists.
- adjust scripts to use absoulte paths where necessary (as the default working dir of `\workspace` is no longer provided and the image-default is used instead).
Also tested with the current version of Tekton.

Prepare pipeline for tekton-upgrade

---

CONTRIBUTING.md

/area os
Includes the requirement to use Conventional Commits into the contribution guidelines (`CONTRIBUTING.md`). Also, leaves the numbering for a numbered list to the .md renderer.
```doc developer
- docs: Conventional commits in contribution guidelines
```

docs: Conventional commits in contribution guidelines

---

README.md

Garden Linux has passed the basic CII criteria and the respective badge is added to the README file by this PR.
Fixes #471

solves issue 471: CII badge added to README.md

---

ci/cicd.yaml
ci/glci/model.py
ci/steps/notify.py

With this pull-request, failing pipeline-builds on `main` (configurable) will also try to post to our internal `gardenlinux-dev` (configurable) channel. A link to the tekton-dashboard will be included, and if a build-log is available it will also be attached.

Ci: also notify via slack for build failures.

---

docker/needslim

/kind regression
/area os
Building a Garden Linux 318 release requires the build containers to come from Debian Bullseye (which 318 is based on). Having `debian:testing-slim` in our files will pull in `bookworm-slim` or newer nowadays which will cause the build to fail.
Do not merge to `main`! This PR must be merged to `rel-318`.
```feature dependency
- fix: make sure build container is based on bullseye for 318 release branch
```

fix: make sure build container is based on bullseye for 318 release branch

---

docker/Makefile

/kind bug
/area os
`docker/Makefile` currently depends on `dpkg` being available on the host to determine BUILDARCH env for build container.
This breaks if the build system is not debian or debian based.
This PR should fix it by only using `uname`.

docker/Makefile: no longer depending on host having dpkg

---

features/_dev/test/groups.d/groups.list
features/base/test/groups.chroot

/kind bug
/area os
The user/group lists are handled wrong when being merged together from the multiple list files presented by the features where the test is enabled. 

Fix for administrative users test

---

bin/garden-config

/kind bug
/area os
When running the exec.config scripts, the features are copied to /tmp, but they weren't properly removed afterwards.

Remove features from /tmp

---

ci/steps/notify.py

This PR will prevent the notification-step from sending slack-notifications for dev-pipelines that are based on `main`.
Safe to merge, but holding until `main` is fixed tomorrow.

Prevent Slack-messages from main-branch dev-pipelines

---

ci/glci/github.py
ci/render_pipelines.py
ci/steps.py
ci/steps/notify.py
ci/steps/update_status.py
ci/tasks.py

Will report a 'pending' to the commit being built once the pipeline starts running (immediately after checking
out) and a final 'success' or 'failure' after the pipeline's outcome can be determined.
The status contains a dashboard-link to the corresponding tekton-pipeline
ToDo: Figure out the best way to achieve the same for pull requests

Ci: report pipeline-status to commit

---

Makefile
bin/start-vm
examples/ipxe/start-vm.ipxe

/area os
When using the start-vm script to test the pxe feature, we don't want to use tftp so we're spinning up a helper container in order to serve the needed files.

Start-vm - fetch files via http when pxebooting

---

features/server/file.include/etc/ssh/sshd_config
features/server/test/sshd.d/ssh_expected

/kind bug
/area os
sftp-server in the sshd_config is using the wrong path.
Part of #516 

Proper sftp-server path in sshd_config

---

bin/Makefile
cert/Makefile
packages/Makefile

/kind bug
/area os
Removes `-ti` arg from all docker run commands except for manual builds.
Currently running make with multiple jobs (`make -j $(nproc)`) in a clean repo fails with `the input device is not a TTY`.
This is because make does not allocate a pty as stdin for job subprocesses &rArr; `docker run -ti` does not work.

remove -ti from all docker runs except for manual builds

---

features/cloud/file.include/etc/kernel/cmdline.d/00-default.cfg

/kind bug
/area os
Cloud providers use serial console output as kind of a log, often even with write access.
However access to the graphical console is much less provided.
So we should make sure the serial console becomes default and gets the most information.
Making both more equal in information can be done with plymouth.

Use serial console as default output for cloud

---

tests/README.md
tests/integration/aws.py

/kind test
/area os
Running an integration/platform test on AWS required several parameters in the config file that a user/developer should not be concerned with if a simple test should be run. Such parameters will now be generated. E.g. if no SSH key gets provided for a test, it will be generated just for this test.
```feature developer
- test(aws): parameter and key generation
```

test(aws): parameter and key generation

---

tests/README.md
tests/integration/azure.py
tests/integration/sshclient.py

/area os
Running an integration test on Azure required several parameters in the configfile a user/developer should not be concerned with if a simple test should be run. Such parameters will now be generated. E.g. if no SSH key gets provided for a test, it will be generated just for this test.
```feature user
- test(azure): automatic parameter and key generation
```

test(azure): parameter and key generation

---

features/cloud/file.include/etc/kernel/postinst.d/zz-kernel-install
features/cloud/file.include/usr/lib/kernel/install.d/95-unified.install
features/metal/file.include/etc/kernel/postinst.d/zz-kernel-install
features/metal/file.include/usr/lib/kernel/install.d/95-unified.install

/kind bug
/area os
We've been using a hardcoded path for the unified image, in the post install kernel scripts - ```"/boot/efi/Default/${kernel#*-}/linux"```
This is having unexpected effects when the ESP partition is mounted on a different path, e.g. /efi
Fixes #

Remove hardcoded path for /boot/efi

---

features/_pxe/test/capabilities.d/capabilities.list

/kind bugfix
/area os
We have `/bin/ping` in the PXE feature as well and need to expect capabilities on it.

Expect ping to have capabilities in pxe as well

---

features/_pxe/pkg.include

/kind cleanup
/area os
We have several partition tools installed (`fdisk` and `gdisk`). As `fdisk` can do all the work now, even for GPT, we can remove `gdisk`.

Remove unused gdisk

---

tests/tools/clean_orphans_aws.py

/area os
Garden Linux integration/platform test may leave orphaned resources behind. This script attempts to find all resources (not literally but those utilized by the test) with the tags `component:gardenlinux` and `test-type:integration-test` and interactively offers to remove them.
```feature developer
- tests(aws): provide a script to find and clean orphaned test resources
```

tests(aws): provide a script to find and clean orphaned test resources

---

docker/build-kernelmodule/Dockerfile

Add DKMS  dependencies to build-kernelmodule container
```other developer
NONE
```

FIX: deps for DKMS in kernelmodule container

---

tests/integration/aws.py
tests/integration/test_gardenlinux.py

/kind test
/area os
The platform tests now check if the ena driver was successfully loaded for the default network interface on AWS.
```feature user
- test(aws): check for presence of ena driver
- test(aws): print out tags and fix teardown 
```

Test aws ena

---

bin/makepart

/kind bug
/area os
For reproducible builds we should remove just the log files from /var/log and keep the directory structure intact.

Do not remove full /var/log

---

ci/steps.py
ci/steps/component_descriptor.py

Adds references to the rootfs-archives to the component-descriptor in addition to the existing virtual image file references. Also adds a reference to the release-manifest-set, if one is available.

Add Additional Resources to Component-Descriptor

---

features/gardener/exec.config
features/gardener/file.include/etc/kernel/cmdline.d/80-cgroup.cfg

/area os
This PR removes the code that sets legacy iptables as default in Garden Linux. It also removes systemd configuration that triggers docker to run with cgroupv1.
This change might have an impact on current Gardener and Kubernetes releases. Kubernetes releases prior to 1.19 will definitely not work with this change. I have already opened https://github.com/gardener/gardener-extension-os-gardenlinux/issues/50 to provide a mitigation if necessary.
Fixes #193
```feature user
```

Change Garden Linux defaults to nftables and cgroupv2

---

features/_dev/file.include/etc/systemd/system/emergency.service.d/sulogin.conf
features/_dev/file.include/etc/systemd/system/rescue.service.d/sulogin.conf

/area os
For development builds, we'd like to be able to use the emergency/rescue mode even if the root account is locked (default on our setup).
Fixes #545

sulogin force for emergency/rescue mode

---

VERSION
bin/garden-version

The default version is set to `dev`. The version is used to reference the repo distribution.
/area os

Support and use dev as default version

---

Makefile
bin/garden-build
bin/garden-config
bin/makepart
bin/start-vm
docker/build-image/Dockerfile
features/base/test/root-perm
features/cloud/exec.config
features/cloud/pkg.include
features/metal/exec.config
features/metal/pkg.include
features/server/pkg.include
get_arch.sh

/kind enhancement 
/area os
- adds support for building arm64 images
- cross architecture builds (from x86 to arm and vice versa) are possible by passing the `ARCH=amd64|arm64` variable to `make`
- cross architecture builds require binfmt_misc support on the build host machine, with the appropriate qemu-user-static handlers set for the target architecture
- on debian this can be achieved by installing the packages `qemu-user-static` and `binfmt-support`
(requires #574)
(supersedes #530)

arm64 image build

---

features/base/file.include/etc/apt/apt.conf.d/no-recommends
features/base/file.include/etc/apt/apt.conf.d/no-suggests
features/base/file.include/etc/ucf.conf
features/server/exec.config

Fix about recommends and suggests:
- deselecting recommends and suggests is now in separate files
- recommends have been deselected but not cleaned up if installed
UCF handling
- dpkg is already on leaf old config
- ucf is now as well (became visible on the latest ssh update)
Systemd fixes:
- systemd cleans ip rules and ip routes of foreign configs since 249
- this causes sever damage if you have a lot of foreign routes -> e.g. bgp
- and causes problems if ip rules are manipulated e.g. cilium

minor fixes

---

features/base/test/rkhunter.chroot

/kind test
/area os
The rkhunter test is running chrooted; garden-chroot is bind mounting /dev, /sys and /proc from the build system and that's not really needed and could also create false positives.
Fixes #565 and #592

Rkhunter test fixes

---

README.md

**Overview**
- Adjusted sources that are accessed to obtain needed bins/pkgs/imgs etc.
- Adjusted dep-pkgs for installing 'tekton'
- Added build options table overview
- Some smaller adjustments
/area os
Adjusting the primary documentation / README.md. This gives new users an easier way to test and build *Garden Linux*.
Fixes #593 
```feature user
NONE
```

Adjusted documentation/README fixes #593

---

bin/makepart
features/cloud/exec.config
features/cloud/file.include/etc/repart.d/root.conf
features/metal/exec.config
features/metal/file.include/etc/repart.d/root.conf

/kind bug
/area os
systemd-repart is not properly working as the detection mechanism is not working as expected, hence we're adding special partition type UUIDs from the discoverable partitions specification. Also, we need to enable the systemd-repart dracut module.

Repart fixes

---

features/gardener/pkg.include

/kind bug
/area os
Fix for containerd CVE-2021-43816
Fixes #
Already fixed in main with a new Debian snapshot.
```feature user
Fix for containerd CVE-2021-43816
```

Fix containerd CVE-2021-43816

---

bin/garden-config

/kind bug
/area os
Adjust `bin/garden-config` so that directories within `file.include` may not break the rootfs during the build because they overwrite important sym links (e.g. `lib -> /usr/lib`).
The adjustment will preserve sym links of the target directory (rootfs) in which the tarball of `file.include` will be extracted.
Fixes #606 
```feature user
```

Preserve symbolic links in file.include

---

features/server/file.include/etc/kernel/cmdline.d/90-lsm.cfg

/kind regression
/area os
GardenLinux 576.0 and 576.1 had SElinux enabled, breaking compatibility with previous Garden Linux releases and workloads that require AppArmor. 576.2 attempted to reenable AppArmor with commit be5c1c0 for the `gardener` feature but left SELinux in for the `server` feature. This PR will disable SELinux altogether for GL576.
Must be merged into __rel-576__ branch, NOT into __main__.
```feature user
fix(apparmor): disable selinux completey for 576, even in server feature
```

fix(apparmor): disable selinux completey for 576 for server feature

---

tests/integration/test_gardenlinux.py

/kind test
/area os
Add platform/integration test to assert that AppArmor is running.
```feature developer
test: check is apparmor is enabled
```

test: check is apparmor is enabled

---

features/gcp/file.include/etc/modprobe.d/gce-blacklist.conf
features/gcp/file.include/etc/sysctl.d/60-gce-network-security.conf
features/gcp/file.include/usr/lib/udev/google_nvme_id
features/gcp/file.include/usr/lib/udev/rules.d/64-gce-disk-removal.rules
features/gcp/file.include/usr/lib/udev/rules.d/65-gce-disk-naming.rules
features/gcp/pkg.include

/area os
In order to keep the images similar between the different cloud vendors, we want to get rid of the `google-compute-engine` package and add the configurations manually to the `file.include` directory. Since it does not provide any kind of service, we should remove the package and leave the configuration. 
Moreover, this change ensures that links or other requirements are still fulfilled correctly (e.g. missing dependencies are added to pkg.include).
Fixes #549 
```feature user
```

Move applicable contents of google-compute-engine package 

---

features/base/test/blacklisted-packages.d/blacklisted-packages.list
features/base/test/blacklisted-packages.d/final.list
features/server/exec.post

The explicit removal is not longer needed since we install from a repo not containing it in the first place. Also fix up the test for it.
/kind cleanup
/area os

Drop explicit removal of libdb5.3

---

ci/promote.py
ci/steps.py

The promote-step currently relies on the structure of the relevant config item never changing. This PR changes it so that the proper getters are used.

Make Promote-step Coding More Resilient

---

bin/garden-config

/kind bug
/area os
This PR ensures that directories can also be removed via the `file.exclude` mechanism like it can be used for files. As of now, directories could be referenced but the build pipeline wasn't able to delete them properly and was just printing a warning to the console without aborting the build.
By providing this change, one can also reference directories in the `file.exclude` file then.
Fixes #463

Fix file.exclude for directories

---

features/_pxe/pkg.include

/kind bug
/area os
Fetch ignition package from snapshot.debian.org.
Fixes #

Fetch ignition pkg from snapshot

---

features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-overlay-setup.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/squash-mount-generator.sh

/kind bug
/area os
fixes problem with EFI PXE boot
**Origin of the problem**
dracut runs the squash-mount-generator twice and on the second run /root.squashfs is already moved, so it'll generate live-get-squashfs.service which causes a race condition in systemd unit ordering and sometimes breaks boot

dracut gardenlinux-live module: fix problem from generator being run twice

---

features/_pxe/pkg.include

The `ignotion` package is finally in Debian Bookworm, so it can be fetched from our mirrored repo.

Use ignition from own repo

---

.github/workflows/build.yml

/kind bug
/area os
automatically get newest version of qemu instead hard coded version

GitHub actions: automatically select newest qemu-user-static version

---

features/base/test/suid.d/suid.list
features/server/pkg.include

/kind cleanup
/area os
Do we need policykit for anything? If not we should probably just get rid of it, the less setuid binaries the better.

cleanup: remove policykit

---

ci/cicd.yaml

Instead of re-using some existing secrets, use ones created for gardenlinux. This also moves the final build artifacts to the proper gardenlinux Azure subscription.
After this PR is merged, I will also port it to all release-branches.

CI: use more appropriate service-principal and storage-account

---

ci/glci/model.py

/kind regression
/area os
Restores pipeline functionality that got broken with PR #583.
```feature developer
ci: treat 'dev' version string like 'today' version string
```

ci: treat 'dev' version string like 'today' version string

---

bin/start-vm
examples/ipxe-install/boot.ipxe
examples/ipxe/start-vm-ignition.ipxe
examples/ipxe/start-vm.ipxe

Since the naming of the build artifacts changed, the startvm script cannot be properly used to pxe boot a VM.
Adding a ignfile command line option to the startvm script to be able to use a custom ignition file when pxe booting a VM with the startvm script.

Startvm script fixes

---

bin/garden-build
bin/makepart

/kind bug
/area os
If the build architecture is not set in the environment (which is the case for the build pipeline), then `makepart` will fail with the changes introduced in PR #605  . The architecture is now handed over from `garden-build` to `makepart`.
```feature user
fix: hand build arch over to makepart
```

fix: hand build arch over to makepart

---

features/cloud/file.include/etc/sysctl.d/20-cloud.conf

/kind bug
/area os
This PR disables the kernel reverse path filtering (rp_filter) which clashes with Cilium.
Fixes #
```feature bugfix
Disable reverse path filtering (rp_filter) which clashes with Cilium.
```

Disable rp_filter due to incompatibility with Cilium

---

bin/makepart

/kind bug
/area os
Set proper selinux context for /boot/efi and /overlay
Fixes #541
```feature user
```

Missing selinux context for boot efi

---

.gitignore
features/cloud/pkg.include
features/cloud/test/kernel_config_options
features/metal/pkg.include

/area os
Upgrades the kernel to 5.10.100 and (re-) enables `CONFIG_DEBUG_INFO_BTF`. Disables rp_filter to improve compatibility with Cilium.
This PR must be merged into `rel-576`, not into `main`.
**Fixes**:
Issue #649 
```feature user
feat: Disable rp_filter for better compatibility to Cilium
feat: kernel 5.10.100 with BTF for GL576.4
chore: git-ignore logs files from tests
test: check for required kernel configuration
```

disable rp_filter and enable BTF for 576

---

features/base/file.include/etc/apt/preferences.d/gardenlinux

/kind bug
/area os
It fixes issues with package dependencies like it is currently the case with the `rkhunter` test  during the build by ensuring that packages from the Garden Linux have a higher priority than other package repos (e.g. `debian/bookworm`)
Fixes #668

Fix package priority of the Garden Linux repo

---

features/gcp/exec.config
features/gcp/file.include/etc/default/instance_configs.cfg

/kind bug
/area os
https://gitlab.com/gardenlinux/gardenlinux-package-build/-/commit/f2b28665 updated repo to mirror debian version of google-guest-agent. This broke `gcp/exec.config` because it no longer ships with `/etc/default/instance_configs.cfg`. This PR fixes it by providing a default config in `gcp/file.include`

fix gcp to work with new google-guest-agent package in repo

---

features/kvm/fstab
features/kvm/info.yaml

Temporary disable the 'verity' feature for 'kvm' images. The
current 'verity' implementation seems to be buggy. Therefore, we
need to disable this feature temporary to proceed with other tasks.
Fixes: #677
/kind bug
/area os
This PR deactivates temporary the verity feature for KVM images to make sure we can proceed with other tasks.
Verity must be reimplemented in a more stable way. However, this gives us more possibilities to identify the needed parts while log files (and journal) will be written, now.
Fixes #677 
```feature user
```

Disable verity feature for KVM images

---

features/base/test/rkhunter.d/rkhunter.conf

/kind bug
/area os
This merge request marks the `which.debianutils` file as a script, so that `rkhunter` isn't throwing a false positive during the unit tests.
Fixes #680

Mark which.debianutils as a script

---

features/gardener/pkg.include
features/khost/pkg.include

/kind cleanup
/area os
The package `containernetworking-plugins` just contains "Some reference and example networking plugins" according to their [GitHub project page](https://github.com/containernetworking/plugins). Gardener does not need these, as we are deploying Calico or Cilium as CNI.
```feature user
fix: remove cni demo binaries from garden feature
```

fix: remove cni demo binaries from garden feature

---

.github/workflows/build.yml

/area os
This PR ensures that the Github Action builds are executed with the `--lessram` parameter. It reduces the memory consumption of the Github Action builds which should mitigate failed builds due to memory issues.
Fixes #689

Let Github Actions run with --lessram

---

docs/configuration/ssh-hardening.md

/area os
This PR contains a documentation about the SSH Hardening actions done in Garden Linux. It also explains what SSH configuration parameters have been set (and where) and what the reason were.
Fixes #516
As of now, the current [sshd_config](https://github.com/gardenlinux/gardenlinux/blob/516_add_ssh_hardening_docs/features/server/file.include/etc/ssh/sshd_config#L26-L28) still sets Cipher Suites, Kex Algorithms and MACs explicitly. However, the documentation recommends to use the default algorithms that the OpenSSH implementation provides.
There may be a change in future which affects either these …

Add SSH Hardening documentation

---

bin/garden-build

/kind bug
/area os
Find the rw partition in fstab and move it to be last partition for makedisk input. 
Fixes #631 
A little hackish, but it solves the problem without re-writing the makepart script.
```feature user
```

look for rw partition and make sure it is last for makedisk input

---

features/cloud/pkg.include
features/metal/pkg.include

/area os
* Upgrades the kernel to 5.10.103.
* Disabled `CONFIG_LOCK_DOWN_KERNEL_FORCE_INTEGRITY` again (as in 576.2 and before), to allow usage of externally build drivers. 
Fixes #688
Fixes an issue where users have reported that custom build drivers could not be loaded (due to `CONFIG_LOCK_DOWN_KERNEL_FORCE_INTEGRITY`) 
This PR must be merged into `rel-576`, not into main.
```feature user
feat: kernel update to 5.10.103
```

update: kernel 5.10.103

---

docs/configuration/ssh-hardening.md
features/server/file.include/etc/ssh/sshd_config
features/server/test/sshd.d/ssh_expected

/area os
This PR ensures that the [SSH documentation](https://github.com/gardenlinux/gardenlinux/blob/701_sync_sshd_config/docs/configuration/ssh-hardening.md) and the [sshd_config](https://github.com/gardenlinux/gardenlinux/blob/701_sync_sshd_config/features/server/file.include/etc/ssh/sshd_config) are in sync by ensuring that `Ciphers`, `KexAlgorithms` and `MACs` are set properly. 
In addition, the SSH documentation has been updated to reference the current OpenSSH version and its default configuration.
Fixes #701

Sync sshd_config with SSH documentation

---

features/gardener/pkg.include

/kind bug
/area os
- Setup of arptables and ebtables is broken (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007829)
- Remove both from `gardener/pkg.include` since most features should be covered by iptables anyways

fix: remove arptables and ebtables packages

---

bin/garden-version

/kind bug
/area os
Currently `bin/garden-version` only works with *"dev"* or a date as input, but breaks when given a version number as input. This PR fixes that.

fix: garden-version script when given version number as input

---

.github/workflows/build.yml

/area os
- use selfhosted github action runners instead of github hosted runners
- allows for native arm builds which are significantly faster than current cross architecture builds
- our self hosted runners are configured with more ram than github's runners, so `--lessram` option is no longer needed

feat: use self hosted runners

---

docs/build/driver.md

**What**
Added documentation on where to find the kernel module build container. 
Previous documentation is outdated.
**Note**
We will probably change the location where to find the container. Until then, let us keep the docs up to date.

doc: use new container for kernel module build

---

tests/README.md
tests/integration/chroot.py
tests/integration/test_gardenlinux.py
tests/test_config.yaml

Add 'chroot' as a new integration platform to perform tests.
* New 'chroot' integration platform
* Adjusted 'RemoteClient' to support 'chroot'
* Adjusted 'test_gardenlinux.py' to support in/exclude for 'chroot' tests
/area os
This PR adds a new platform provider for integration tests. This allows us to perform tests inside a `chroot`. Next to the new `KVM` this allows users to run integration (and future unit) tests without any cloud platform like GCP, AWS,....  The new `chroot` platform is also the base for the migration (#676) from unit tests to a common Pytest base.
Fixes #709
The provided `test_config.yaml` can …

feat(test): add chroot as integration test platform (#709)

---

tests/integration/kvm.py

Fix broken `KVM` integration test (wrong func order)
/kind test
/area os
Fixes the `KVM` integration test
Fixes #
NONE
```feature user
```

fix(test): fix broken KVM test (wrong func. order)

---

tests/integration/conftest.py

This fixes the broken integration tests for `ALI`, `chroot`, `OpenStack` and `KVM` that resulted from #724.
/kind test
/area os
Integration tests for  `ALI`, `chroot`, `OpenStack` and `KVM` are currently not usable.
@MrBatschner, please take a short look. Thanks.
NONE
```feature user
```

fix(test): fix integration tests for Ali, chroot, OpenStack, KVM

---

tests/integration/azure.py
tests/integration/sshclient.py

/kind bug
/area os
1. With the changes introduced in PR #730, the ssh-key generator for the test framework will run into an error if the ssh-key file exists but is of size zero (which is the case for the platform tests). Therefore, extending the check if a keyfile is already present by additionally checking on its file size too.
1. The `SubscriptionClient` for Azure which we use to translate a subscription name to its id moved packages which required a small change to the test code.
```feature user
fix(tests): do not attempt to read empty ssh keys
fix(test): honor move of Azure SubscriptionClient
```

fix(tests): do not attempt to read empty ssh keys

---

features/server/test/sshd.d/ssh_expected

/kind bug
/area os
fix cipher order to pass the sshd test
Fixes #758 
```feature user
```

fix cipher order to match order in sshd_config

---

tests/integration/test_gardenlinux.py

/kind test
/area os
As Garden Linux changed the default security module from AppArmor to SELinux, adapting the tests to check for SELinux' presence.
```feature user
test: check for presence of SELinux
```

test: check for presence of SELinux

---

features/cloud/exec.config
features/metal/exec.config

/kind bug
/area os
exec.config from the metal/cloud features are missing the shebang, plus the build process should be aborted if there are any issues.

fix: metal/cloud exec.confing

---

features/gardener/file.include/var/lib/gardener-gardenlinux/03_iptables_backend.sh

/kind cleanup
/area os
We are configuring the netfilter **backend**, not the **frontend**. Just cleaning up the name in the scripts to be consistent.
```feature user
fix: renaming netfilter frontend to backend
```

fix: renaming netfilter frontend to backend

---

ci/build_kaniko.py

This adds another workaround to the current kaniko build: The pre-existing python-binaries will be moved out of reach of the build running in the container (similar to `ùsr/lib` and `cc-utils`) during its run-time.
This will unblock the current issues related to Python 3.10 in the build-deb image.

Fix kaniko build

---

features/cis/test/test_debian_cis.py
tests/conftest.py
tests/integration/test_gardenlinux.py

Move IAAS related fixtures to global 'conftest.py'. This
allows all tests regarding their location to use the functions.
/area os
Currently, it isn't possible to exclude target platforms (`fixtures`) in PyTests within `features` directories. This may tests fail that can't be triggered on specific target platforms. This PR will add the possibility to add `fixtures` as target platform args for related functions to exclude them again.
Fixes #781
```feature user
- target_group: developer
```
Test run:
Command: `pytest --iaas=chroot --configfile=chroot.yaml`
Output:
``` …
```

Move IAAS related fixtures to conftest

---

features/base/test/blacklisted-packages.d/blacklisted-packages.list
features/base/test/blacklisted-packages.d/final.list

/area os
This PR adds `libssl1.1` to the blacklisted packages. Thereby, this change should verify if there are still packages that depend on `libssl1.1`. All Garden Linux packages should depend on `libssl3` instead.
Fixes #796

Add libssl1.1 to blacklisted packages

---

bin/inject-sshkey

/area os
This PR adds a new tool `inject-sshkey` that allows user to add their ssh pub key into a final GL artifact. Afterwards, the image can be booted and the user may connect via the SSHD.
Fixes #780
```feature user
- category:      feature
- target_group:   user
```

feat: Add tool to inject ssh pubkey to a final artifact

---

Makefile
README.md
bin/Makefile
bin/start-vm
build.sh
cert/Makefile
container/Makefile
container/needslim
features/fedramp/test/test.sh

/area os
With PR #702 we changed the container runtime environment for all build and test containers to Podman to exclusively use free and open-source licenses. However, some users might not be able to use Podman (e.g. because they are not sudoer but members of a `docker` group) but a different container runtime which is compatible to Docker/Podman.
With this PR, by setting the environment variable `GARDENLINUX_BUILD_CRE` to e.g. `docker`, the container runtime used for building Garden Linux can be configured.
```feature developer
- feat: build container runtime can be switched
```

feat: switchable build container runtime

---

README.md

Clicking on the badge redirects to the Garden Linux Gitter channel
Fixes #158

fix: Gitter chat badge links to gitter channel

---

features/cis/test/conf.d/6.1.13_find_suid_files.cfg
features/cis/test/conf.d/6.1.14_find_sgid_files.cfg

* Add custom whiteliste for CIS check: 6.1.13: Find SUID
-> Add: /usr/lib/dbus-1.0/dbus-daemon-launch-helper
* Add custom whiteliste for CIS check: 6.1.14: Find SGID
-> Add: /usr/bin/write
-> Add: /usr/lib/systemd-cron/crontab_setgid
/area os
Add and extend whitelist configs for the `CIS` tests. This adds:
```
* Add custom whiteliste for CIS check: 6.1.13: Find SUID
-> Add: /usr/lib/dbus-1.0/dbus-daemon-launch-helper
* Add custom whiteliste for CIS check: 6.1.14: Find SGID
-> Add: /usr/bin/write
-> Add: /usr/lib/systemd-cron/crontab_setgid
```
Fixes ##786
```feature user
NONE
```

Add custom whitelist checks for CIS tests

---

bin/garden-debian-sources-list
features/cis/test/check_scripts/1.2.2_ensure_apt_gpg_keys.sh

/area os
This PR modifies the Garden Linux Repo entry in `/etc/apt/sources.list` 
from:
```
deb https://repo.gardenlinux.io/gardenlinux dev main
```
to:
```
deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/gardenlinux.asc] https://repo.gardenlinux.io/gardenlinux dev main
```
While Debian and Garden Linux are package signed this is not really important. However, we can just add this to be more `CIS` complaint.
Fixes #842
Please check that this change:
* won't break anything else
* implementation style
```feature user
NONE
```

feat(test): Adjust Garden Linux Repository File and Add Test for CIS

---

tests/integration/chroot.py
tests/integration/kvm.py

feat(test): Add validation for supported file extensions
* Validate file extension for KVM test platform
* Validate file extension for CHROOT test platform
/kind test
/area os
This PR catches user errors and will fail when unsupported image types are used on `KVM` or `CHROOT` test platforms.
Fixes #861
```feature user
NONE
```
**Test**:
Failed:
```
ERROR    integration.chroot:chroot.py:123 tar.foo is not supported for this platform test type.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!! _pytest.outcomes.Exit: tar.foo is not supported for this platform test type. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

feat(test): Add validation for supported file extensions

---

ci/release.py
features/base/test/packages-musthave.chroot
features/cloud/pkg.include
features/gardener/pkg.include
features/metal/pkg.include

/kind cleanup
/area os
Introduces changes for Garden Linux 576.9:
- update containerd to 1.5.11-1gardenlinux
- update runc to 1.0.3-2gardenlinux
- both package were rebuilt with golang 1.17.9 to eliminate several golang CVEs
- update docker.io to 20.10.14+dfsg1-1+b1
- package is taken from Debian upstream and built with golang 1.18.1
- update kernel to 5.10.113
- tests(packages): correctly handle URLs in pkg.include for packages.musthave test
- revert changing to the release branch pattern from `rel-XXX` to `release/XXX`
Must be merged into the `rel-576` branch, not into `main`.
```bugfix user
- update containerd to 1.5.11-1gardenlinux
- update …
```

updates for Garden Linux 576.9

---

README.md

/area os
Adjust the podman documentation in the `README.md`. The example of adding `docker.io` to the `registries.conf` did not work for on system on which the `registries.conf` is only writable for root.
The adjustment takes this into consideration now.

Adjust podman documentation in `README.md`

---

README.md

/area os
removes duplicate package `coreutils` from `apt install` line

Remove duplicate coreutils on apt install

---

ci/steps/component_descriptor.py

We plan to sign Component Descriptors in the near future. This PR sets the necessary values in the CDs published for Gardenlinux that tell the signing code to skip including the resources in our s3 bucket for the time being.
Also fixes some under-indented lines.

Set digest attribute for resources in Component Descriptor

---

features/server/test/test_kernel_parameter.py

/kind bug
/area os
fix the expected value for kernel.randomize_va_space that was accidentally changed during testing
Fixes #
```feature user
```

fix expected value for kernel.randomize_va_space

---

tests/Pipfile.lock
tests/helper/tests/password_shadow.py
tests/helper/tests/sgid_suid_files.py
tests/integration/test_gardenlinux.py

/kind bug
/area os
This PR fixes the mentioned issues of #859 
* Fix escaping
* Update paramiko, so that it works with the newer Python version and does not produce warnings
* Disables 'test_loadavg' on 'kvm' and 'chroot' platform since the load heavily depends on the load of the build system in theses cases.
* Disabled `test_selinux` on 'chroot' platform similar to 'test_apparmor'
Fixes #859

Cleanup chroot tests

---

features/base/exec.config

/kind cleanup
/area os
This PR removes old unused code
Fixes #910 
NONE
NONE

910: remove old code path, that will not be called any more

---

bin/start-vm

/kind bug
/area os
Fix Typo in help text of bin/start-vm

Fix typo in bin/start-vm help text

---

docs/README.md

gardenlinux.io/documentation is not public yet.
Fixes #904

fix: remove reference to gardenlinux.io

---

bin/garden-init

fix(pkg): Fix pkg install in debootstrap not using `noninteractive` mode
/kind TODO
/area os
This PR fixes that the debootstrap process doesn't use a `noninteractive` mode for installing packages from repository that may regularly need a further dialog.
Fixes #917
Can be tested with the package `git`
```feature user
bugfix
```

fix(pkg): Fix pkg install in debootstrap not using `noninteractive` mode

---

integration_tests/readme.md

This PR makes it clear that the integration_tests/ folder is only used by tekton pipelines.
A new developer looking for tests may find the integration_tests/ folder.
Fixes #713

doc: make it clear that integration_tests is only used by tekton

---

features/base/test/debsums.chroot
features/base/test/orphaned.chroot
features/base/test/rkhunter.chroot

/kind test
/area os
This PR removes the unneeded package `apt-utils` from legacy test scripts.
Locally tested:
```
test debsums is disabled by the following features: cloud 
test dev is enabled by the following features: base 
testing /dev contents
OK - all /dev devices match
passed
test dmesg is enabled by the following features: server 
testing dmesg access for non-root users (SAP Security 2.90.03)
OK - dmesg restricted | kernel config parameter
passed
test groups is enabled by the following features: _dev base 
testing administrative accounts
OK - all user accounts/groups are as expected
passed
test history is enabled by the following features: server 
OK - …
```

feat(test): Remove unneeded `apt-utils` package from legacy tests

---

features/README.md

/kind TODO
/area os
The heading is currently not rendered correctly because of a missing blank line.
Fixes #
NONE

Fix type in general heading

---

README.md

The readme references baremetal as a platform, and suggests it can be used as feature argument for `./build.sh`

docs: rename reference baremtal to metal

---

bin/start-vm

bin/start-vm immediately exits after `Press any key to continue...` due to wrong input format for `dd` command. 
This PR fixes the parsing for dd parameters.

fix(start-vm): properly split the inflatelist

---

features/cis/test/conf.d/1.5.1_bootloader_ownership.cfg

/kind bug
/area os
Add whitelist for `CIS` check `1.5.1_bootloader_ownership`. Another check is already given by https://github.com/gardenlinux/gardenlinux/blob/main/features/cis/test/check_scripts/1.5.1_bootloader_ownership_syslinux.sh 
Fixes #939
```feature user
NONE
```

fix(cis): Add whitelist for `CIS` check `1.5.1_bootloader_ownership`

---

features/cis_audit/exec.config

fix(cis): Add additional rules for `audit.rules` file
* Add: dotlockfile
* Add: mailq
* Add: nullmailer-queue
/kind bug
/area os
fix(cis): Add additional rules for `audit.rules` file
* Add: dotlockfile
* Add: mailq
* Add: nullmailer-queue
Fixes #943
```feature user
NONE
```
**Validation**:
```
4.1.11_record_privileged_ [INFO] Working on 4.1.11_record_privileged_commands
4.1.11_record_privileged_ [INFO] [DESCRIPTION] Collect use of privileged commands.
4.1.11_record_privileged_ [INFO] Checking Configuration
4.1.11_record_privileged_ [INFO] Performing audit
4.1.11_record_privileged_ [ OK ] -a always,exit -F …
```

fix(cis): Add additional rules for `audit.rules` file

---

features/aws/file.include/etc/dracut.conf.d/90-xen-blkfront-driver.conf

/kind bug
/area os
some aws ec2 instance types use xen vbd for disks, so without the xen-blkfront driver in the initrd the block device for the root partition could not be detected

fix: add xen-blkfront driver to initrd for aws images

---

features/cis_os/file.include/etc/logrotate.d/btmp
features/cis_os/file.include/etc/logrotate.d/wtmp
features/cis_packages/pkg.include

feat(cis): Add package `logrotate` for feature `CIS`
/kind bug
/area os
This adds the missing package `logrotate` and delivers configs for `wtmp` and `btmp` including the customized permissions. `Logrotate` will be daily executed by an auto installed crontab.
Fixes #946
```feature user
NONE
```

feat(cis): Add package `logrotate` for feature `CIS`

---

features/base/test/test_password_hashes.py
tests/helper/tests/password_hashes.py

/area os
simplify existing pytest password hashes
Fixes #874 
```feature user
```

simplify existing pytest password hashes

---

features/base/test/test_debsums.py

fix(pytest): Add `usr/share/runit/meta/ssh/installed` to be excluded
/kind bug
/area os
Fixes the `test_debsums` PyTest and avoids failing the test pipeline.
Fixes #961
```feature user
NONE
```

fix(pytest): Add `usr/share/runit/meta/ssh/installed` to be excluded

---

ci/glci/aws.py
tests/README.md
tests/integration/aws.py
tests/integration/test_gardenlinux.py

/area os
Extends the Integration/Platform tests for AWS to support ARM64 images.
```feature user
- extends the Integration/Platform tests for AWS to support ARM64 images.
```

tests: support ARM64 for tests on AWS

---

bin/start-vm

fix(startvm): Allow virtualized ARM64 systems to run QEMU even when no further accleration is supported
/kind bug
/area os
This PR allows  Apple Silicon (M1/M2) users to run VMs with `bin/startvm` script which may fail based on the underlying virtualization technology like `UTM`.
Fixes #957
```feature user
NONE
```

fix(startvm): Allow virtualized ARM64 systems to run QEMU

---

tests/integration/azure.py

/kind test
/area os
Enables the boot diagnostics for platform tests on Azure so that it is possible to see what went wrong if a machine fails to properly boot.
Fixes #
```feature user
- enable Azure boot diagnostics
```

test: enable Azure boot diagnostics

---

build.sh

/kind test
/kind bug
/area os
Even though Garden Linux builds with PodMan nowadays, it still supports building with Docker by setting the env variable `GARDENLINUX_BUILD_CRE=docker`. For the tests, a container with an elaborate set of capabilities is started but apparently, Docker does not like these capabilities to be supplied as a comma-separated list (PodMan does though) and the tests fail to run. Thus, this PR now supplies each capability with its own `--cap-add` switch.
```feature user
- test: capabilities supplied individually to container runtime
```

test: seperate capability list

---

features/base/exec.config
features/base/file.include/etc/dpkg/origins/gardenlinux

/area os
This PR changes the default vendor from Debian to GardenLinux. GardenLinux is not Debian, but a Debian Derivative.
Fixes #907 
NONE

907: dpkg origin gardenlinux

---

features/cloud/pkg.include
features/metal/pkg.include

/area os
Updates the kernel for Garden Linux 576 to 5.10.123 to provide a fix for CVE-2022-1966.
Must be merged into the `rel-576` branch, **not** into the `main` branch.
```feature user
- feat: update kernel to 5.10.123
```

feat: update kernel to 5.10.123

---

bin/makepart
features/_pxe/image

fix(SELinux): Temporary deactivate 'setfiles' command
/kind bug
/area os
This PR temporary deactivates the `setfiles` command within the `makepart` part of the pipeline. With Debian's new version 3.4-1 of `libselinux1` this does not work anymore on a non active SELinux environment. A proper fix will be delivered soon.
Fixes #1014
This is a quick fix and lets us build images again.
```feature user
NONE
```

fix(SELinux): Temporary deactivate 'setfiles' command

---

tests/integration/aws.py
tests/integration/azure.py
tests/integration/gcp.py
tests/integration/util.py

/kind test
/area os
Change disk type for VM used for platform test on Azure to SSD (instead of HDD) to be consistent across all platforms and to have comparable boot-up times.
And while were are at it, implements the same change for GCP.
```feature user
- test(azure): use ssd for test vm
- test(gcp): use ssd as disk for test vm
- test: minor fixes for the platform tests
```

test: use ssd for test vms

---

tests/integration/chroot.py
tests/integration/kvm.py

/kind bug
/area os
Currently tests fail with
```
ERROR    integration.chroot:chroot.py:123 0-local.tar.xz is not supported for this platform test type.
```
when using any version other then `dev` since in that case everything after the dot in the version number gets treated as part of the image extension.
This fixes it by using the string `endswith` method instead of manually parsing out the extension from the filename.

fix: use .endswith to check for allowed image extensions

---

ci/steps/component_descriptor.py

With this PR, rootfs-resources will also get digest-information added to the component-descriptor.

Ci: also add digest to rootfs-resources

---

build.sh

/kind bug
/area os
`build.sh` was using hardcoded `dev` version of the `base-test` container.
This breaks when building a specific version in a clean build environment where no prior dev builds ran.

fix: use $version instead of hardcoded dev for test container

---

README.md
bin/start-vm

Add support for macOS and CentOS (Stream)
/kind bug
/area os
This PR adds further support of additional OS in `startvm` of:
* macOS
* CentOS (Stream)
Fixes #1025
Fixes #1021
```feature user
NONE
```

Add support for macOS and CentOS (Stream) in `startvm`

---

features/cloud/pkg.include
features/metal/pkg.include

/area os
remove out commented cloud-guest-utils from metal and cloud feature
Fixes #102
```feature user
```

remove out commented cloud-guest-utils from metal and cloud feature

---

bin/make_reproducible_ext4

/kind bug
/area os
ensure debugfs parses the timestamp as a plain timestamps and not some date format

fix: debugfs timestamps

---

tests/integration/test_gardenlinux.py

/kind test
/area os
Provides a platform test that check that file timestamps are not in the future (which could provide a smell for clock skew).
```feature user
- test: check for timestamps in the future
```

test: check for timestamps in the future

---

features/ali/pkg.include
features/server/file.include/etc/systemd/system/systemd-resolved.service.d/wait-for-networkd.conf
tests/integration/test_gardenlinux.py

/kind cleanup
/area os
Changes the cloud-init version that gets installed into the ali-cloud image from the previously pinned 20.2 version to the latest upstream version. Also fixes some typos in the platform tests and changes their order to allow for enough time for the NTP client in Garden Linux to successfully synchronize before checking its status.
```feature user
- fix: install latest cloud-init for alicloud
```

fix: install latest cloud-init for alicloud

---

tests/conftest.py

/kind test
/area os
(Re-)Enables running the platform/integration tests on an already existing and provisioned host of which an SSH key and the IP/hostname is known. This functionality was introduced in PR #461 and got broken in the refactoring of the test framework.
```feature developer
- test(manual): reenable manual test for existing host
```

test(manual): reenable manual test for existing host

---

features/server/test/test_machine_id.py
tests/helper/tests/machine_id.py

feature(pytest): Add PyTest for validating the `machine-id`
This PyTest validates the systemd unit for creating a machine-id
as well as the content of the created machine-id
/area os
This PR adds another PyTest for validating the `machine-id`.
Fixes #1051
```feature user
NONE
```

feature(pytest): Add PyTest for validating the `machine-id`

---

container/Makefile
container/integration-test/Dockerfile

/kind bug
/area os
This PR ensures that the build pipeline uses a dynamic version for referencing the base image of the the `integration-test` container in its Dockerfile. This way, we can ensure that the image version between the `integration-test` and `base-test` (base image of `integration-test`) are kept in sync during the build.
In the past, the base image version has been hard coded and did not work anymore due to a change from `dev` to `today`.
Fixes #1074

fix: use dynamic version for the base image of integration-test

---

bin/garden-integration-test-config
build.sh

/kind bug
/area os
This PR ensures that the correct architecture is passed to the KVM tests during a build. Previously, the `garden-integration-test-config` returned a wrong configuration which provided a pytest configuration for `amd64` tests although the image has been built as an `arm64` image.

Integrate arch for KVM tests properly

---

bin/start-vm

feat(startvm): General enhancements for `startvm`
* Translate `arm64` to `aarch64` on macOS (Fixes: https://github.com/gardenlinux/gardenlinux/issues/1056)
* Fix macOS paths for `qemu-system-$arch` binary (Fixes: https://github.com/gardenlinux/gardenlinux/issues/1055)
* Add `HVF` acceleration on macOS on `AARCH64` systems (Fixes: https://github.com/gardenlinux/gardenlinux/issues/1052)
* Add eval for HomeBrew path (Fixes: https://github.com/gardenlinux/gardenlinux/issues/1079)
* Add eval for QEMU version
* Add eval to obtain correct UEFI code/vars
* Rewrite `-cpu`, `-host`, `-accel` parts
/area os
Fixes #1056
Fixes #1055
Fixes #1052
Fixes #1079 …

feat(startvm): General enhancements for `startvm`

---

bin/README.md
bin/start-vm

feature(startvm): Check if `/dev/kvm` can be used by user
* Check if device is accessible and fallback to non accelerated usage
* Add documentation how to solve a non accessible device
/area os
Fixes #1051
```feature user
NONE
```

feature(startvm): Check if `/dev/kvm` can be used by user

---

bin/start-vm

/kind bug
/area os
Currently, we can not execute `start-vm` as `root` users (which may be especially a problem in containers). This is caused by:
```
[ $(id -u) == 0 ] && virtOpts=(        "-runas nobody" )
```
We can just move it up to avoid overwriting our `virtOpts` like the previously added image file. No further adjustments here at this time (that'll be done in #1062).
Fixes #1084
```feature user
NONE
```

fix(start-vm): Pass $imagefile also when running as `root`

---

Makefile

/kind bug
/area os
add build targets for build-environment and secureboot certs to metal-secureboot and metal-secureboot-dev
Fixes #1043 
```feature user
```

add build-environment and secureboot crt to secureboot target

---

features/metal/pkg.include

/kind bug
/area os
do not install bird2 package as it is missing in debian testing right now, new bird2 version will be commit to testing in 3 days
Fixes #
```feature user
```

temp fix for missing bird2 package

---

features/base/test/test_sgid_suid_files.py
features/server/test/sgid
features/server/test/sgid.d/sgid.list
tests/helper/tests/sgid_suid_files.py

/kind bug
/area os
currently sgid_suid_files test uses hardcoded ids, this occasionally breaks as gids for system groups differ between flavours, probably depending on set of installed packages
this switches the test to use group and user names instead of ids to make the test behave more reproducibly regardless of how ids get assigned to groups

fix: use user and group names instead of ids in sgid_suid_files test

---

features/cloud/file.include/usr/sbin/enroll-gardenlinux-secureboot-keys

fix(secureboot): Symlink enroll-gardenlinux-secureboot-keys to only have a single file
/kind bug
/area os
These two files were drifting...
Fixes #1105
```feature user
NONE
```

fix(secureboot): Symlink enroll-gardenlinux-secureboot-keys to only have a single file

---

README.md

/kind bug
/area os
| old | new |
| - | - |
| [![build](https://github.com/gardenlinux/gardenlinux/actions/workflows/build.yml/badge.svg)](https://github.com/gardenlinux/gardenlinux/actions/workflows/build.yml) | [![build](https://github.com/gardenlinux/gardenlinux/actions/workflows/nightly.yml/badge.svg?event=schedule)](https://github.com/gardenlinux/gardenlinux/actions/workflows/nightly.yml) [![build](https://github.com/gardenlinux/gardenlinux/actions/workflows/dev.yml/badge.svg?branch=main)](https://github.com/gardenlinux/gardenlinux/actions/workflows/dev.yml) |

fix: adapt README badges for new workflow files

---

tests/helper/tests/packages_musthave.py

/kind bug
/area os
This PR resolves an issue with the `packages_musthave` test which did not work properly with `pkg.exclude` files within affected features.
Fixes #1112

fix(test): Make packages_musthave work with pkg.exclude properly

---

features/cis_os/exec.config
tests/integration/kvm.py

/kind bug
/area os
adjust snapshot size for kvm integration tests to make it work for the CIS image
Fixes #1098 
```feature user
```

adjust snapshot size for kvm integration tests

---

container/build-image/Dockerfile

/kind bug
/area os
retry building garden-feat.go in build-image container
this is needed as a workaround to prevent builds occasionally failing with errors like
```
stream error: stream ID 1371; INTERNAL_ERROR; received from peer
```

fix: retry go build of garden-feat

---

tests/README.md

/area os
This PR extends the test documentation by adding information about the login procedure while using MFA. This should help new developers to perform tests more easily.
This PR is related to #1035

feature(test): Add AWS MFA information to the documentation

---

features/cloud/pkg.include
features/metal/pkg.include

/area os
Upgrades Linux kernel of Garden Linux 576 to 5.10.133 to fix a number of CVEs.
Must be merged into `rel-576`, **NOT** into `main`.
```feature user
- Upgrades Linux kernel of Garden Linux 576 to 5.10.133
```

fix: upgrade kernel to 5.10.133

---

features/base/exec.config

/kind bug
/area os
mark usr-is-merged package as manual installed to pass orphaned test. The package is installed by debootstrap, it is a requirement since the debootstrap version 1.0.127
debootstrap 1.0.127 was released on 27.07.2022.
Fixes #1137 
```feature user
```

mark usr-is-merged as manual installed to pass orphaned test

---

bin/garden-build
build.sh

/area os
Inlcudes the long/untruncated git commit hash into `/etc/os-release`.
Required for proper artifact handling in build pipeline and also for consistency - the final artifact should have to full Git commit hash in it.
```feature user
feat: include long git commit hash in os-release
```

feat: include long git commit hash in os-release

---

tests/integration/test_gardenlinux.py

/kind test
/area os
In PR #766 we introduced the check for an enabled SELinux LSM. Since we currently build Garden Linux with AppArmor as LSM, this PR reverts the check to AppArmor.
```feature user
test: check for enabled AppArmor
```

test: check for enabled AppArmor

---

.gitignore
ci/steps/build_base_image.py
docker/needslim
features/cloud/pkg.include
features/metal/pkg.include

/kind cleanup
/area os
- Introduces Kernel 5.10.134 into Garden Linux 576 to fix several CVEs
- changes the build-image for Garden Linux 576 builds from `debian:testing-slim` to `debian:stable-slim` to fix the requirement of the `usr-is-merged` package that the latest versions of debootstrap require and which we will not include into Garden Linux 576
- adds some more files to `.gitignore`
This PR **must** be merged into `rel-576`, **NOT** into `main`. Please do not squash this PR but the keep the individual commits.
```feature user
- Introduces Kernel 5.10.134 into Garden Linux 576 to fix several CVEs
- changes the build-image …
```

576: Kernel-update and fix of build-image

---

features/gardener/file.include/etc/kernel/cmdline.d/90-lsm.cfg

/area os
As some Gardener users are relying on AppArmor to be the configured LSM on their worker nodes, this PR sets AppArmor to be the default LSM in the `gardener` feature.
Test for active AppArmor was already filed with PR #1139 
```feature user
- use apparmor as lsm for Gardener feature
```

feat: use apparmor as lsm for Gardener feature

---

tests/helper/sshclient.py
tests/helper/tests/ssh_authorized.py
tests/integration/aws.py
tests/integration/test_gardenlinux.py

/area os
This PR ensures that feature tests can be executed on the AWS platform, too. As of now, some feature test failed because they couldn't be executed properly. In order to fix this, the current implementation of the SSHClient needed to be adjusted, so that we can control what test commands are executed with `sudo` and which one are not. Some of the feature tests require root privileges but the AWS platform usually uses a dedicated test user called `admin` which does not have these privileges.
By merging this change, each test command that is executed against a AWS VM (EC2 instances) is executed with `sudo` except for some commands which must be executed with the normal user. …

feature(test): Make feature test work with AWS images (arm64/amd64)

---

build.sh

/bug 
it allows to run build on mac. if you run build you can face:
```
./build.sh: line 65: /bin/true: No such file or directory
A83502232@T000cac27a gardenlinux % which -a true                            
true: shell built-in command
/usr/bin/true
A83502232@T000cac27a gardenlinux % sudo ln -s /usr/bin/true /bin/true  
```
there are no issues
- bugfix: builds on mac

bug: build fails on mac because there is no /bin/true

---

tests/README.md

Fix tag/version for testing containers
/kind bug
/area os
This fixes the deprecated usage of `dev` tag for `base-test` containers. Now, it's evaluated by `garden-version` to have all logic in a single place.
```feature user
NONE
```

fix(tests-doc): Fix tag/version for testing containers

---

container/Makefile

fix(build): Fix Makefile for macOS
/kind bug
/area os
Fixes #1163
This has been tested on `macOS` with `Docker` and `Debian` with `podman` which results in:
```
localhost/gardenlinux/build-image  863.0         2283540fdcda  4 minutes ago  763 MB
```
More information about this issue can be found in #1163.
```feature user
NONE
```

fix(build): Fix Makefile for macOS

---

README.md
bin/start-vm

/area os
- Update for Start-VM 
- Update for Readme for crossbuild and general build on Arch/Manjaro
Fixes start-vm boot without --ueficode and --uefivars
`/usr/share/OVMF/x64/OVMF_CODE.secboot.fd` exists in Arch, but does not work. Enrolling Secure Boot keys did not work with this Firmware, but with `/usr/share/OVMF/x64/OVMF_CODE.fd` it works.

Readme Update + StartVM Fix

---

features/base/exec.config
features/base/test/test_umask.py
features/cloud/exec.config

- Move setting of login.defs umask 027 to base feature 
- including test_umask
Fixes #39 
**Notes**
- Noticed during testing: when creating a user with adduser, files from `/etc/skel/*` are copied to the users new home directory. Permission of these files will not respect the umask value of login.defs.

fix: move login.defs umask to base feature

---

bin/makepart
features/_pxe/image

fix(SELinux): Reenable `setfiles` for `SELinux` file contexts
/kind bug
/area os
Reenable `setfiles` for `SELinux` file contexts
Fixes #1014
None
```feature user
None
```
**Test(s)**:
```
root@localhost:~# sestatus -v
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             default
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy …
```

fix(SELinux): Reenable `setfiles` for `SELinux` file contexts

---

features/gardener/test/test_lsm.py
tests/integration/test_gardenlinux.py

feat(test): Move LSM tests to dedicated gardener test folder
/kind test
/area os
Move LSM tests to dedicated gardener test folder and use PyTest syntax.
Fixes #1170
```feature user
NONE
```
**Test(s)**:
```
PASSED gardener/test/test_lsm.py::test_lsm[selinux-False]
PASSED gardener/test/test_lsm.py::test_lsm[apparmor-True]
```

feat(test): Move LSM tests to dedicated gardener test folder

---

features/vhost/pkg.include

feature(pkg): Add pkg virtinst for feature vhost #1174
/area os
Add pkg `virtinst` for feature vhost #1174
Fixes #1174
**Important**: Merge only after Gitlab PR (https://gitlab.com/gardenlinux/gardenlinux-package-build/-/merge_requests/131) got merged.
```feature user
- target_group: user 
```

feature(pkg): Add pkg virtinst for feature vhost #1174

---

features/vhost/pkg.include

feature(pkg): Add pkg virtinst for feature vhost #1174
/area os
Add pkg `dnsmasq` for feature vhost #1179
Fixes #1179
**Important**: Do not merge before: https://gitlab.com/gardenlinux/gardenlinux-package-build/-/merge_requests/132/commits
```feature user
- target_group: user 
```

feat(pkg): Add pkg dnsmasq for feature vhost #1179

---

features/vhost/pkg.include

feat(pkg): Add pkg dmidecode for feature vhost
/kind bug
/area os
Add pkg dmidecode for feature vhost
Fixes #1187
```feature user
NONE
```

feat(pkg): Add pkg dmidecode for feature vhost

---

features/_readonly/fstab.mod
features/cloud/info.yaml

/kind bug
/area os
remove _readonly feature from cloud feature, fix disk full error in tekton pipeline
Fixes #1155 
```feature user
```

remove _readonly from cloud feature

---

features/server/pkg.include

hotfix(selinux): Temporary deactivate gardenlinux-selinux-module
/kind bug
/area os
This fixes the currently broken build pipeline where the new
selinux-policy-default isn't compatible with our gardenlinux-
selinux-module anymore. This package will be reenabled soon.
Fixes #1196
This may be reenabled together with the new refpolicy or completely replaced by the `selinux-fedroa` policy set. While the new `refpolicy` seems to fix our main issues, this could be a game changer. Unfortunately, I need some more time if this is a usable way.
```feature user
NONE
```

hotfix(selinux): Temporary deactivate gardenlinux-selinux-module

---

ci/glci/az.py
ci/glci/model.py
ci/promote.py

Update the release manifest we generate so that we can later on determine the way the image was published (needed for gardener `cloudprofile` generation) and enable publishing via shared image gallery.

CI: publish images on Azure using shared image gallery

---

features/base/test/test_usr_ro.py

/kind test
/area os
Validates that the `/usr` directory is read-only.
Fixes #
The test has been moved to `features/base/test`. This means that 
```
features:
- "base"
```
must be included in the test configuration.
```feature user
```

Validate the /usr is read-only.

---

.github/workflows/gcp_tests.sh

/kind bug
/area os
adding `--arch` argument to github action platform tests in #1229 broke gcp tests, this fixes the issue by using the last instead of the first argument to `gcp_tests.sh`

fix: github actions: gcp ignore --arch arguments

---

bin/start-vm

Fix running `start-vm` inside a container
/kind bug
/area os
Fix running `start-vm` inside a container (e.g. needed for `KVM` unit tests).
Fixes #1234
```feature user
NONE
```

fix(start-vm): Fix running `start-vm` inside a container

---

features/clamav/test/test_clamav_cron.py
features/clamav/test/test_packages_musthave.py
tests/helper/utils.py

Add unit tests for feature `clamav`
/kind test
/area os
Add unit tests for feature `clamav`
Fixes #1173
```feature user
NONE
```
**Failed**:
```
FAILED clamav/test/test_clamav_cron.py::test_clamav_cron - AssertionError: no error='cat: /var/spool/cron/crontabs/root: No such file or directory\n' expected
FAILED clamav/test/test_packages_musthave.py::test_packages_musthave - AssertionError: clamav should be installed, but are missing
```
**Passed**:
```
PASSED clamav/test/test_clamav_cron.py::test_clamav_cron
PASSED clamav/test/test_packages_musthave.py::test_packages_musthave
```

tests(clamav): Add unit tests for feature `clamav`

---

features/firecracker/test/test_packages_musthave.py
features/firecracker/test/test_systemd_unit.py
tests/conftest.py
tests/helper/utils.py

Add unit tests for feature `firecracker`
/kind test
/area os
This PR adds additional unit tests for the `firecracker` feature. However, we can only run some in on IAAS `chroot` or for development cases on `kvm`. While these ones are already working, we should add a new IAAS type `firecracker` (see also: #1240).
Fixes #1173 
* RNG is disabled by systemd architecture condition on `arm64` by droplet
* We can already perform tests on IAAS `chroot`
* Other ones can currently only be used by devs via IAAS `kvm`
* We need to implement a new IAAS `firecracker` (#1240)
* This may help people to not encounter further unit testing issues …

tests(firecracker): Add unit tests for feature `firecracker`

---

features/_secureboot/test/test_empty_files_boot_efi.py
features/_secureboot/test/test_packages_musthave.py
features/_secureboot/test/test_uefi_pki_files.py

tests(_secureboot): Add unit tests for feature `_secureboot`
/kind test
/area os
Add unit tests for feature `_secureboot`
Fixes #1173
```feature user
NONE
```
**Tests**:
```
PASSED _secureboot/test/test_empty_files_boot_efi.py::test_empty_files_boot_efi
PASSED _secureboot/test/test_packages_musthave.py::test_packages_musthave
PASSED _secureboot/test/test_uefi_pki_files.py::test_uefi_pki_files[/etc/gardenlinux/gardenlinux-secureboot.pk.auth]
PASSED _secureboot/test/test_uefi_pki_files.py::test_uefi_pki_files[/etc/gardenlinux/gardenlinux-secureboot.kek.auth]
PASSED _secureboot/test/test_uefi_pki_files.py::test_uefi_pki_files[/etc/gardenlinux/gardenlinux- …
```

tests(_secureboot): Add unit tests for feature `_secureboot`

---

tests/integration/azure.py

/kind test
/area os
Removes a check for name availability of a storage account for platform tests on Azure. The check seems to be broken when used with a subscription only available through a shared tenant and it is unnecessary as creating the storage account would fail if the name were not available.
```feature developer
- test: remove check for storage account name on Az platform tests
```

test: remove check for storage account name

---

tests/README.md
tests/conftest.py
tests/integration/ali.py
tests/integration/aws.py
tests/integration/azure.py
tests/integration/gcp.py

... and avoid code-duplication
/kind test
/area os
Allows to configure the name of a test-run for the platform test and as such, modify the prefix that is used for allocated resources in the cloud providers. Of course, not specifying a `test_name` manually will still fall back to the default that was used before: `gl-test-<YYYYmmDDHHMMSS>`.
```feature developer
tests: make test name for platform tests configurable
```

tests: make test name for platform tests configurable

---

features/ali/test/test_users.py
features/aws/test/test_users.py
features/azure/test/test_users.py
features/base/test/test_users.py
features/gardener/test/test_dmesg.py
features/gardener/test/test_systemd_units.py
features/gcp/test/test_users.py
features/server/test/test_reset_env_vars.py
features/server/test/test_users.py
tests/conftest.py
tests/helper/tests/capabilities.py
tests/helper/tests/file_content.py
tests/helper/tests/kernel_parameter.py
tests/helper/tests/sshd.py
tests/helper/tests/users.py
tests/helper/utils.py

/kind test
/area os
Running the feature tests on cloud platforms such as Azure or AWS will have some problems due to the fact that the user used to log in to the test-VM has no root permissions. This PR:
- adds a `sudo` to commands that require root permissions
- gives to the full path to commands/binaries that reside in `/usr/sbin` which is not in a non-root user's `$PATH`
In addition, it makes sure that additional users that get injected by the cloud platforms are accepted and will not fail the `test_users.py` test.
```feature developer
test: fix tests to run with non-root user on cloud platforms
```

test: fix tests to run with non-root user on cloud platforms

---

features/server/file.include/etc/systemd/system/systemd-coredump@.service.d/override.conf

More details explained in #1226; this fix removes directories left over in /run/systemd/propagate from the instantiated services of systemd-coredump.
Fixes #1226

fix: systemd-coredump remove dirs

---

ci/steps/component_descriptor.py

Adds a label to the oci-image and rootfs-resources of this component, indicating who is responsible for them in respect to our compliance scans.
@MrBatschner seems to be a good fit for the responsible here. Feel free to add/modify the suggested responsibles, e.g.:
```python3
cm.Label(
name='cloud.gardener.cnudie/responsibles',
value=[
{
'type': 'emailAddress',
'email': 'thomas.buchner@sap.com',
}, {
'type': 'emailAddress',
'email': 'andreas.burger@sap.com',
}
],
),
```
Alternatively, responsibles can also be added by github-user, e.g.:
```python3
cm.Label(
name='cloud.gardener.cnudie/responsibles',
value=[
{
'type': 'githubUser',
'email': 'MrBatschner',
},
],
),
```
Once this is merged, this should also be …

Ci: Add component-responsible-labels to Component Descriptor

---

features/_readonly/test/test_mount.py
tests/helper/tests/mount.py

tests(_readonly): Add unit tests for feature `_readonly`
/kind test
/area os
Add unit tests for feature `_readonly`
Fixes #1173
```feature user
NONE
```
**Test(s)**:
Fail:
```
FAILED _readonly/test/test_mount.py::test_mount[/opt-ro-opt_in_option-True] - AssertionError: Could write on mount /opt.
FAILED _readonly/test/test_mount.py::test_mount[/foo-ro-opt_in_option-True] - AssertionError: Could not find option ro for mount /foo in /etc/fstab.
```
Passed:
```
PASSED _readonly/test/test_mount.py::test_mount[/opt-ro-opt_in_option-False]
PASSED _readonly/test/test_mount.py::test_mount[/opt-ro-opt_in_option-True]
```

tests(_readonly): Add unit tests for feature `_readonly`

---

container/integration-test/Dockerfile

/kind bug
/area os
This PR fixes an issue with the `integration-test` container build. It replaces the Azure repo with the distribution repo for installing `azure-cli` in order to resolve an dependency issue with OpenSSL.
Fixes #1260

fix: Use dist repo instead of the Azure one for azure-cli

---

.github/workflows/upload_to_s3.sh

/area os
Use the full prefix (including the minimal feature set) in the S3 object key rather than just the make target.
This will make it easier for the tekton pipeline to find the uploaded images for publishing.

GitHub actions: S3 upload use full prefix in object key

---

container/integration-test/Dockerfile

/kind bug
/area os
This PR fixes a typo of the integration test container Dockerfile introduced due to #1261.
Fixes #1260

fix: Fix typo of the integration test container Dockerfile

---

ci/glci/util.py
ci/package_aliases.yaml
ci/paths.py
ci/steps.py
ci/steps/component_descriptor.py
features/cloud/pkg.include
features/gardener/pkg.include
features/metal/pkg.include
features/server/file.include/etc/systemd/system/systemd-coredump@.service.d/override.conf
features/server/pkg.include

/area os
Introduces updates for Garden Linux 576.12 into the `rel-576` branch:
- ci: freeze cd-step image
- ci: change the way package versions are represented in the CD
instead of putting the package versions into the CD as part of the rather generic 'build-metadata'-label, put them in their own label in a better parseable format. Also provide an initial alias-file.
- ci: add component-responsible-labels (#1140)
- fix: systemd-coredump remove dirs
- fix: upgrade several packages
- Linux Kernel 5.10.141
- libgnutls30 3.7.7 to provide a fix for CVE-2022-2509
- libtirpc3 1.3.1-1+deb11u1 to provide a fix for CVE-2021-46828
- zlib1g 1.2.11.dfsg-4.1 to provide a fix for CVE-2022-37434
- …

Merge changes for Garden Linux 576.12 into `rel-576` branch

---

features/_prod/file.exclude
features/_prod/pkg.exclude

After some discussions with @gehoern it was decided that coredumps should be disabled when using the _prod feature - coredumps are disabled by default (ulimit soft 0, hard unlimited) so removing systemd-coredump is enough.

Remove systemd-coredump from _prod

---

.github/workflows/tests.yml

/kind test
/area os
Exclude arm64 build from automatic platform tests on Azure as this combination is not supported by the test framework yet.
```feature user
tests: exclude ARM64 from automatic platform tests on Azure
```

tests: exclude ARM64 from automatic platform tests on Azure

---

.github/workflows/aws_tests.sh
.github/workflows/azure_tests.sh
.github/workflows/gcp_tests.sh

/kind test
/area os
Integration/platform tests run in nightly currently run the tests in `test_gardenlinux.py` and omit all feature defined tests. This PR adds the list of features to test to the test configuration to have a wider test coverage.
```feature user
tests: include full feature tests into nightly run
```

tests: include full feature tests into nightly run

---

bin/makesecureboot
features/cloud/exec.config
features/metal/exec.config
features/server/file.include/etc/systemd/system/systemd-growfs@.service.d/override.conf

rootfs is not properly resized all the time, growfs is running before or in parallel with systemd-repart.
More information : [here](https://github.com/systemd/systemd/commit/7b45d6b6f64e9f5c006bdf31559a77294dbe00ad)

Fix : rootfs not resized properly sometimes

---

ci/steps/component_descriptor.py

/area os
Disables Checkmarx static code checks for the Garden Linux repo as it only contains build instructions for the final artefact and no source code that will end up in the final artefact.
```feature user
ci: skip static source check for Garden Linux repo
```

ci: skip static source check for Garden Linux repo

---

features/ali/test/test_users.py
features/aws/test/test_users.py
features/azure/test/test_users.py
features/gcp/test/test_users.py
tests/helper/tests/users.py

/kind test
/area os
Allows to have configurable additional users (other than root) to have sudo capabilities in platform tests.
Failing platform test due to users injected by cloud-init having sudo access.
```feature developer
- tests: allow additional sudo users
```

tests: allow additional sudo users

---

.github/workflows/tests.yml

/kind test
/area os
Exclude Azure ARM from nightly platform tests (apparently, the syntax used in PR #1268 was wrong).
```feature developer
tests: exclude Azure ARM from nightly tests
```

tests: exclude Azure ARM from nightly tests

---

features/kvm/file.include/etc/kernel/cmdline.d/50-ignition.cfg
features/kvm/file.include/usr/local/sbin/update-bootloaders

As we don't have a separate /usr anymore, the mount.usr and mount.usrflags kernel cmdline parameters need to be removed.
Simplify update-bootloaders and don't pass the initrd pass as parameter.

KVM ignition fixes

---

.github/workflows/upload_to_s3.sh

/kind bug
/area os
#1258 changed the S3 object key to use the full prefix instead of just the make target name, but these changes were not yet reflected in the corresponding single yaml

fix: use prefix instead of name in single yaml

---

bin/start-vm

start-vm has some small issues that prohibit the usage of the pxe features.

Small fixes for start-vm

---

features/server/test/pkg.ignore
tests/helper/tests/packages_musthave.py

/kind test
/area os
If a less significant feature installs a package via `pkg.include` and a more significant feature uninstalls the package via `pkg.exclude` again, the test `packages_musthave` will fail for the less significant feature. This PR adds the (debatable) `pkg.ignore` file to the `test` folder of a feature that can tell the test to ignore a missing package.
Fixes failing nightlies.
```feature user
- test: allow missing packages to be ignored
```

test: allow missing packages to be ignored

---

features/base/exec.config

/kind bug
/area os
This PR ensures that orphaned packages that have been introduced by the new debootstrap version `1.0.127+nmu1` are marked as manually installed. 
These packages are dependencies of `usrmerge` which is excluded by debootstrap since the new version. However, the dependencies are still installed but they are orphaned. This is a bug which should be fixed in debootstrap. In order to get the build pipeline up and running again though, this PR is needed as a workaround.
Fixes #1305

fix: Mark some orphaned packages as manually installed

---

container/integration-test/Dockerfile

fix(integration-test): Add missing arch eval after moving to new test container
/kind bug
/area os
I missed a line while copying the Firecracker binaries from `base-test` to `integration-test` container. (Rel. #1318)
```feature user
NONE
```

fix(integration-test): Add missing arch eval after moving to new test container

---

container/integration-test/Dockerfile

Add ARM64 util support for integration-test container
/area os
Add ARM64 util support for integration-test container. This obtains the used architecture and downloads the related binaries.
Fixes #1264
```feature user
NONE
```

feat(ARM64): Add ARM64 util support for integration-test container

---

tests/README.md

enhancement(pytest): Align hardware architectures for Pytest
* Architectures: amd64, arm64 (will be mapped according the IAAS type)
* Fix typos
* Adjust docs
/area os
A user shouldn't care about the different hardware architectures (amd64, AMD64, x86, x86_64,...) on different hyperscaler or IAAS types while running the Pytests. Therefore, we should abstract them as `amd64` and `arm64` and evaluate this within the code. Luckily, we already had this in code for all present IAAS (e.g. https://github.com/gardenlinux/gardenlinux/blob/main/tests/integration/aws.py#L56-L57 or https://github.com/gardenlinux/gardenlinux/blob/main/tests/integration/kvm.py#L254) types that support multiple …

enhancement(pytest): Align hardware architectures for Pytest

---

container/Makefile
container/build-image/Dockerfile

/area os
This PR adds the Garden Linux Repo to the build-image container in order to install some build tools that are built in the Gitlab Pipeline and published to the Garden Linux Repo. This makes them accessible in the Garden Linux build.
Fixes #1304

feat: Add Garden Linux Repo and onmetal-image to build container

---

bin/garden-config
features/README.md

feature(buildpipeline): Add possibility to define file permissions
* Change user/group of files
* Change permissions of file
/area os
Add possibility to define file permissions for files that are being included into the image by features. This allows to define a user, group and permission for a file. Requested by @5kt in #920.
Fixes #920
You may validate by placing any file within a `file.include` directory, as well as the new `file.include.stat` file, eg.:
```
features/firewall/file.include.stat
features/firewall/file.include/etc/test
```
Content of `file.include.stat` includes according to the Debian syntax: 
``` …
```

feature(buildpipeline): Add possibility to define file permissions

---

features/_dev/devkey.sh

Remove unused and deprecated devkey.sh file
/kind cleanup
/area os
Remove unused and deprecated devkey.sh file
Fixes #513
With #777 we already cleaned up the static ssh key injection. Now, we should also remove the unused `devkey.sh` from the `_dev` feature, because it never got used and we may use `cloud-init` for further configuration. Next to this, there's still the auto-login on tty0 present and usable.
```feature user
NONE
```

cleanup(feature): Remove unused and deprecated devkey.sh file

---

bin/start-vm

We should be able to use the start-vm script when running on a Garden Linux host.
Fixes #

fix(start-vm): add garden as supported host_dist

---

bin/garden-config

Related to #920, already handled by @gyptazy via #1331
This is just forcing sane defaults (owner root:root, permissions 755/644) for files/directories included via files.include, irrespective of their owner/permissions on the build machine; executable bit will be kept.
Of course, an override will then be possible via file.include.stat.
Setting custom permissions via file.include.stat is now done chrooted to match the users/groups from the build.
Fixes #920

file.include.stat extras

---

README.md
docs/build/README.md

Add doc for building in an air-gapped environment
/area os
Add doc for building in an air-gapped environment
Fixes #1348
```feature user
NONE
```

doc(build): Add doc for building in an air-gapped environment

---

container/Makefile

fix(Makefile): Fix removing/untagging `build-image` container
/kind bug
/area os
Fix removing/untagging `build-image` container
Fixes #1326
```feature user
NONE
```

fix(Makefile): Fix removing/untagging `build-image` container

---

VERSION
features/server/pkg.include
tests/helper/tests/packages_musthave.py

/kind bug
/area os
Updates OpenSSL for Garden Linux 934 to `3.0.7`  to provide fixes for CVE-2022-3602 and CVE-2022-3786.
Only to be merged once the packages are available in [repo.gardenlinux.io](https://repo.gardenlinux.io). Must be merged into `rel-934`, not into `main`.
```bugfix user
fix: update openssl to 3.0.7
```

fix: update openssl to 3.0.7

---

.github/workflows/aws_tests.sh
.github/workflows/azure_tests.sh
.github/workflows/gcp_tests.sh

/kind test
/area os
Automatic platform tests write their test results to a dedicated location (`/tmp/gardenlinux-platform-test-logs`) on the GitHub Actions runner so that they can be collected in later steps.
```feature user
test: write junit.xmls to dedicated location
```

test: write junit.xmls to dedicated location

---

bin/start-vm
docs/test_VM_with_start-vm_and_qemu.md

/area os
It adds support to start-vm for ignition files without the need of _pxe feature.

Add iginiton for start-vm without pxe

---

container/Makefile
container/base-test/Dockerfile

How to categorize this PR?
/area os
What this PR does / why we need it:
This PR adds the Garden Linux Repo to the base-test container in order to install some build tools that are built in the Gitlab Pipeline and published to the Garden Linux Repo. This makes them accessible in the Garden Linux base test.
Which issue(s) this PR fixes:
Fixes https://github.com/gardenlinux/gardenlinux/issues/1349

Add gardenlinux repo to base-test container

---

bin/garden-version

Added feature to retrieve latest minor version from apt repo when calling `garden-version --minor`.
This allows for `rel-<major>` branches to specify only `major` without the minor in the VERSION file.
Fixes #1401 
This PR does not break the old behavior. 
How to test:
```
./bin/garden-version --minor
./bin/garden-version
./bin/garden-version --minor
./bin/garden-version
./bin/garden-version --minor
./bin/garden-version
```

feat: garden-version gets latest minor from gl apt repo

---

container/Makefile

Preserve file permissions when copying GL repo key
/kind bug
/area os
Preserve file permissions when copying GL repo key
Fixes #1408
None
```feature user
- target_group: user, developer, operator
```

feature(container): Preserve file permissions when copying GL repo key

---

bin/start-vm

Passes the `--pidfile file` flag to qemu. 
Fixes #1415 
```
./bin/start-vm --daemonize --pidfile somepidfilename.pid ./build/<some image you build before>
```

feat(start-vm): add --pidfile flag

---

features/cloud/file.include/etc/sysctl.d/20-cloud.conf
features/cloud/file.include/etc/sysctl.d/21-ipv4-settings.conf
features/cloud/file.include/etc/sysctl.d/22-ipv6-settings.conf

/area os
Introduces the `net.ipv6.conf.all.forwarding = 1` and the `net.ipv6.conf.default.forwarding = 1` sysctl setting upon popular request from Gardener development.
To make the file structure in /etc/sysctl.d more concise, rearranges all ` ipv4` and `ipv6` related settings into dedicated files and leaves all other settings in the old `20-cloud.conf`.
Consider cherry-picking to `rel-934` after merging this to `main`.
```feature user
feat: enable ipv6 forwarding by default
```

feat: enable ipv6 forwarding by default

---

flavours.yaml

/area os
Introduces a `gardener` flavor-set to only contain those public cloud platforms currently used by Gardener and leave out anything bare-metal.
```feature user
feat: add a gardener flavour set
```

feat: add a gardener flavour set

---

build.sh
ci/lib.sh
container/build/install-cfssl.sh
features/cis/test/check_scripts/1.2.1_ensure_repository_is_configured.sh
features/cloud/file.include/etc/profile.d/50-autologout.sh
features/server/file.include/etc/profile.d/50-nohistory.sh

/area os
fix errors found by shellcheck
Fixes #
```
$ find . -name '*.sh' -type f -print0 | xargs -n 1 -0 shellcheck -S error
In ./ci/lib.sh line 1:
own_dir="$(readlink -f "$(dirname "${0}")")"
^-- SC2148 (error): Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
For more information:
https://www.shellcheck.net/wiki/SC2148 -- Tips depend on target shell and y...
In ./build.sh line 197:
${gardenlinux_build_cre} run --name $containerName ${dockerArgs[@]} --rm \
^--------------^ SC2068 (error): Double quote array expansions to avoid re-splitting elements.
In ./build.sh line 223:
${gardenlinux_build_cre} run …
```

fix shellcheck erros

---

container/base-test/Dockerfile
container/build-image/Dockerfile

Explicitly sets the file permissions as required by the container image.,
Fixes #1420 
Kudos to @5kt

fix: set file attributes of key in Dockerfile

---

ci/glci/aws.py
docs/deployment/aws-secureboot.md
make_targets/aws-secureboot
tests/README.md
tests/integration/aws.py

/area os
This PR adjust the integration tests for AWS, so that a user can define the `boot_mode` and the `uefi_data` which is required to run AWS instances with secure boot enabled.
In addition, it provides a documentation showing what must be done to run Garden Linux with secure boot enabled on AWS.
Fixes #1324

Enable secure boot on AWS

---

README.md
bin/garden-build
bin/garden-debian-sources-list
bin/garden-init
build.sh
features/example/README.md
tests/helper/tests/debsums.py
tests/helper/tests/tiger.py
tests/helper/utils.py

feature(devel): Add new build command `--debian-mirror`
Add possibility to add the native Debian repository to chroot when
installing package via `pkg.include` function (only in dev mode).
/area os
Add new build command `--debian-mirror`. This adds the possibility to add the native Debian repository to chroot when
installing package via `pkg.include` function and will only work on non production builds. When building a prod artifact this will fail with the following message:
```
Using the native Debian repository on production builds (_prod) is not supported.
```
Fixes #1422
```feature user
- target_group: …
```

feature(devel): Add new build command `--debian-mirror`

---

features/vmware/vmware.ovf.template

/area os
Supports ignition ovf properties. I think it still needs the logic added to act upon these params during the first boot.

add vmware ovf properties for ignition

---

features/firewall/file.include/etc/nft.d/default.conf

feature(firewall): Switch to "allow" for output & forward, allow ICMP:
* Switch to default policy allow for output instead of drop
* Switch to default policy allow for forward instead of drop
* Allow ICMP and ICMPv6 for input
/area os
Switch to "allow" for output & forward, allow ICMP:
* Switch to default policy allow for output instead of drop
* Switch to default policy allow for forward instead of drop
* Allow ICMP and ICMPv6 for input
Fixes #1447
```feature user
NONE
```

feature(firewall): Switch to "allow" for output & forward, allow ICMP

---

tests/integration/chroot.py

/kind bug
/area os
This PR fixes the `chroot` platform so that unit tests are working again. As of now all chroot tests are failing which blocks the nightly builds. This is due to a bug that doesn't let the SSH server run probably. Therefore, pytest can connect to the Garden Linux instance via SSH.
Fixes #1456

fix: Fix wrong error handling in the chroot platform

---

build.sh

Fix docker CRE support for unit testing
/kind bug
/area os
This will redefine the correct image label name to support Podman and Docker as CRE.
Fixes #1455
Tests for Docker and Podman...
**Docker**:
```
Running pytests in chroot
+ wait %1
++ pwd
+ docker run --name 7F1B417D-A933-4A99-9798-082DBEB6D592 --cap-add sys_admin --cap-add mknod --cap-add audit_write --cap-add net_raw --security-opt apparmor=unconfined --rm -v /Users/florian/development/opensource/gardenlinux/github/gardenlinux:/gardenlinux -v /var/folders/b4/wlfrdg9556907s9g1zkk_j0c0000gn/T/tmp.PNnSAvFP:/config gardenlinux/base-test:today pytest --iaas=chroot …
```

fix(pipeline): Fix docker CRE support for unit testing

---

.gitignore
VERSION
bin/makepart
container/Makefile
container/base-test/Dockerfile
container/build-cert/Dockerfile
container/build-image/Dockerfile
container/build/Dockerfile
features/githubActionRunner/exec.config
tests/integration/chroot.py

/area os
* Build Environment Fixes
* explicitly set `gardenlinux.asc` file permissions via 889aa02
* use cdn-aws debian mirros via a8178f1
* git ignore *.cache files (e.g. make_targets.cache) via a49d72e
* bootctl requires /proc mounted manually - taken from 
b372a91b8ab4a17465ac5e465427f00f8dfd85bb
* fix tests that could not connect via paramiko in test environment - taken from  cae061aaca34d0608ee25a20fd96615b351dae89
* make githubactionsrunner feature tests green for this PR - taken from  28c011ce420c9a7af46642d3693b9c2a21613bf0
* upgrade kernel to 5.15.81-0gardenlinux1
* Fixes CVE-2022-3169 via 5.15.80
* Fixes CVE-2022-3435 via garden linux backported patch
* mbcache deadlock fix: …

Prepare 934.2

---

Makefile
README.md
bin/README.md
docs/build/README.md

doc(Makefile): Adjust docs for auto generated make targets from flavour.yaml
/area os
Adjust docs for auto generated make targets from flavour.yaml
Fixes #1462
Update the docs to avoid further confusions regarding the `make` targets, how to handle and edit them. Added an additional target which just uses the regular mechanism to generate the cache file where a regular user can look up the default targets according to the `flavor.yaml` (which contains the default base targets).
```feature user
- category: doc
```

doc(Makefile): Adjust docs for auto generated make targets from flavour.yaml

---

bin/README.md
bin/garden-build
bin/garden-init
features/base/exec.config

Integrate `garden-repo-manager` for repository management
/kind cleanup
/area os
* Integrate `garden-repo-manager` for repository management
* Fix crosscompile in `arm64` (to create `amd64`)
* Fix `local_packages` support
Fixes #1433
Fixes #1470 
Fixes #1473
This is based on the new `garden-repo-manager` package for Garden Linux.
See also: https://gitlab.com/gardenlinux/gardenlinux-package-gardenlinux-repo-manager
```feature user
- target_group: user, operator, developer
```
**WIP**
Within the default case, only the Garden Linux repository will be added:
```
X-Repolib-Name: …
```

feature(build): Integrate `garden-repo-manager`

---

tests/integration/gcp.py

/kind bug
/area os
make the secureboot_parameters parameter optional in the config for tests on gcp
Fixes #1478 
```feature user
```

make secureboot_parameters parameter optional

---

bin/garden-feat

Fix output of `platforms` argument:
* Fix output of `platforms` argument
* Fix typo for argparse description
/kind bug
/area os
`platforms` can't be evaluated
Fixes #1476
```feature user
- target_group: developer
```

fix(garden-feat): Fix output of `platforms` argument

---

features/_prod/file.include/etc/security/limits.conf
features/_prod/file.include/etc/sysctl.d/99-disable-core-dump.conf
features/_prod/file.include/etc/systemd/coredump.conf.d/disable_coredump.conf

feature(_prod): Disable core dumps (legacy & systemd)
/area os
Disable core dumps (legacy & systemd) when using `_prod` feature:
* Disable for services that are started by systemd
* Disable for legacy apps that are invoked in any other way
* Have a fallback if a future feature removes systemd
This will only apply on artefacts built with `_prod` feature. As a result, all other ones may still create core dumps for debugging any issues during the development.
Fixes #38
Just test it by creating an artefact by running:
```
make kvm_prod
```
```feature user
```

feature(_prod): Disable core dumps (legacy & systemd)

---

features/base/exec.config

fix(feature): Fix perl version in `base` feature
/kind bug
/area os
Fix perl version in `base` feature that avoids building GL.
```feature user
NONE
```

fix(feature): Fix perl version in `base` feature

---

features/base/file.include/etc/sysctl.d/10-disable-sysrq.conf
features/base/test/test_disable_sysrq.py

feature(kernel): Disable `sysrq` completely as default
* Disable `sysrq` completely as default
* Add test to validate that `sysrq` is disabled
/area os
Disable `sysrq` completely as default
Fixes #1485
```feature user
```
**Test**:
```
root@garden:~# sysctl -a | grep sysrq
kernel.sysrq = 0```

feature(kernel): Disable `sysrq` completely as default

---

container/build-cert/Dockerfile
container/build-image/Dockerfile

Package `aws-sdk-cpp` was renamed to `libaws-sdk-cpp-dev` 
https://gitlab.com/gardenlinux/gardenlinux-package-aws-sdk-cpp/-/commit/00a1219156dbf1115f0e6c4463d9d0c03ea8255c
**Note**
Please note that the aws-sdk-cpp was also broken, latest libaws-sdk-cpp-dev package fixes the `CURLOPT_PUT` issue.
short:
- aws cpp sdk uses deprecated CURLOPT_PUT: https://github.com/aws/aws-sdk-cpp/blob/main/aws-cpp-sdk-core/source/http/curl/CurlHttpClient.cpp#L421
- Garden Linux patch fixes use of deprecated `CURLOPT_PUT` https://gitlab.com/gardenlinux/gardenlinux-package-aws-sdk-cpp/-/blob/main/patches/curlopt_fix.patch

fix: use libaws-sdk-cpp-dev

---

bin/garden-init

/kind bug
/area os
/etc/apt/trusted.gpg.d/gardenlinux.asc will have whatever permissions the file has on the build system.
This is usually problematic when cloning the repo on machines with strict umasks. 
So we should force 644 as permissions for the file (force root:root as owner as well, not really needed, but just to be clearer).
Fixes #

Force permissions for gardenlinux.asc

---

.github/workflows/README.md

Beta and Stable releases are not yet implemented. Adding Documentation when we have implemented and signed of the process for stable and beta pipelines.
Fixes #1282

doc: remove unimplemented github actions docs

---

bin/make_repart_partition
features/_secureboot/file.include/etc/kernel/cmdline.d/99-no-rd-shell.cfg

ensure waiting for /dev/mapper/sysroot does not timeout
/area os
- disable rd.shell in secureboot
- ensure waiting for /dev/mapper/sysroot does not timeout

feat: disable rd.shell in secureboot

---

features/base/exec.config

Fixes new 934.3 build via backport of https://github.com/gardenlinux/gardenlinux/commit/70479be1039b9deb073380d839b5b1ed664057b2

fix: Fix perl version in base feature (#1491)

---

features/ssh/file.include/etc/ssh/sshd_config

/kind impediment
/area os
`ssh-rsa` was dropped from the list of key algorithms fom OpenSSH 8.8 as it is considered insecure (ref https://www.openssh.com/txt/release-8.8). 
While it is reasonable for SSH clients not to use this algorithm anymore, the SSH server sshd should still advertise it as valid algorithm for host-key verification since there are still clients out there (such as Microsofts _Certification Test Tool for Azure Certified_) which will simply be unable to establish a connection without.
Needs to ported to `rel-934` as well - cherry-pick is not enough since the file-structure changed.
```feature user
enable ssh-rsa as …
```

enable ssh-rsa as HostKeyAlgorithm

---

tests/helper/tests/password_hashes.py

This PR extends the password_hashes test, to also verify `sssd`'s pam.d configuration.
Fixes #1505 
Taking a further look into the [PAMConfigFrameworkSpec](https://wiki.ubuntu.com/PAMConfigFrameworkSpec) separately. Using a config similar to [main/features/cloud/file.include/usr/share/pam-configs/garden](https://github.com/gardenlinux/gardenlinux/blob/main/features/cloud/file.include/usr/share/pam-configs/garden) could be an enhancement.

allow sssd configuration

---

VERSION
features/azure/file.include/etc/waagent.conf
features/azure/pkg.include
features/base/exec.config
features/server/file.include/etc/ssh/sshd_config
features/server/pkg.include
tests/conftest.py
tests/integration/aws.py

/area os
Adds all improvements planned for Garden Linux 934 patch release 3, i.e. `934.3` to the `rel-934` branch. 
Those are in particular:
- bump version to 934.3 in VERSION 
- fix: Fix perl version in base feature
- fix(tests): remove dependency to glci
The following are required to pass Azure Marketplace certification:
- enable ssh-rsa as HostKeyAlgorithm
- fix: set ClientAliveInterval to 180 secs in sshd_config
- feat(azure): add waagent but disable provisioning
Must be merged to `rel-934`, NOT to `main`. Please do not squash commits in this PR.
```feature user
- enable ssh-rsa as HostKeyAlgorithm
- bump version to 934.3 in …
```

improvements for Garden Linux 934.3

---

features/kvm/file.include/etc/udev/rules.d/60-onmetal.rules

For the onmetal project, we run KVM VMs with Gardenlinux.
For the disks that are attached to the VMs, the actual device name specified in the libvirt domain xml is not guaranteed to map to the device name in the guest OS, Gardenlinux in our case.
As discussed with @gehoern, the disks used are going to have serial numbers in the form of "odX-abcdefabcdefabcd", where: 
- odX will be used as a new device name for the specific disk and will be a symlink `/dev/onmetal/odX -> actual_kernel_device_name`
- the serial abcdefabcdefabcd will be used as WWN and another symlink will get created `/dev/disk/by-id/wwn-abcdefabcdefabcd -> actual_kernel_device_name`

Add specific onmetal (vm) udev rules

---

container/base-test/Dockerfile

/kind test
/area os
Removes static pinning to a specific python version for the Garden Linux test containers to always use the latest version found in an upstream repo.
```feature user
test: remove python pinning from test container
```

test: remove python pinning from test container

---

container/base-test/Dockerfile
container/build-cert/Dockerfile
container/build-image/Dockerfile
container/build/Dockerfile

/kind bug
/area os
use /etc/apt/sources.list.d to be compatible with new version of debian:testing-slim images

fix: make container build work with new versions of debian:testing-slim

---

hack/gl-search-package.sh

This `gl-search-package.sh` script downloads the Packages file from repo.gardenlinux.io, and uses [fzf](https://github.com/junegunn/fzf) for easy to read and filter presentation of available gardenlinux packages.
fzf is a requirement, you can install it via 
```
sudo apt install fzf
```
Select target Garden Linux version by setting `gl_dist` in your env to the target gardenlinux version.
```
gl_dist=934.4 && ./gl-search-package.sh
```

feat(hack): add cli package search tool

---

VERSION
container/base-test/Dockerfile
container/build-cert/Dockerfile
container/build-image/Dockerfile
container/build/Dockerfile

/area os
* Build Environment Fixes
* fix: use /etc/apt/sources.list.d to be compatible with new version of debian:testing-slim images 
* Package updates
* Kernel 5.15.93
* vim/2:9.0.1000-4
* bind9/1:9.18.11-2
* containerd/1.6.17
* Note: We needed to disable publishing via Azure Community Galleries for this Release, because it is currently not usable for Gardener because of a Bug in Azure.
```feature user
* Package Updates
* Kernel 5.15.93
* vim/2:9.0.1000-4
* bind9/1:9.18.11-2
* containerd/1.6.17
* Note: Publishing to Azure Community Gallery is disabled
```

Prepare Release of 934-4

---

container/build-image/Dockerfile

Running `nightly`  build pipeline with rel-934 fails for all flavors requiring keys from aws kms (pxe and secureboot).
```
Unable to load module /usr/lib/aarch64-linux-gnu/pkcs11/aws_kms_pkcs11.so
PKCS11_get_private_key returned NULL
``` 
Note: currently debugging. Changes in this PR may not be final

Rel 934 kms fix

---

.github/workflows/build.yml
make_targets/kvm-secureboot
make_targets/metal-secureboot
make_targets/pxe

Disabling secureboot and pxe because of this bug: https://github.com/gardenlinux/gardenlinux/issues/1537

remove pxe and secureboot targets

---

features/_dev/exec.config
features/_dev/exec.post

* moves `features/_dev/exec.config` to `features/_dev/exec.post`. This is required because the new implementation of garden-feat orders features differently. Now, `_dev/exec.config` would run before `server/exec.config`, which leads to a broken `_dev/exec.config.
* Since `_dev` requires group "wheel" to be created first, we simply move _dev configuration to exec.post
* Since exec.post is not executed in chroot, we need to do it now in the features/_dev/exec.post explicitly.

fix(_dev): move _dev/exec.config to _dev/exec.post

---

bin/garden-build
bin/makepart

/kind bug
/area os
use `$fullfeatures` instead of `$features` in makepart to check if `_selinux` is enabled
fixes issue with selinux relabeling running on first boot if `_selinux` feature is included by other features instead of explicitly added to feature set

fix: makepart use fullfeatures

---

README.md

Adjusting Readme, since `python3-yaml` and `python3-networkx` are currently required to build Garden Linux.

doc(README): Add mandatory build dependencies to

---

features/chost/file.exclude
features/chost/file.include/etc/config.toml
features/chost/file.include/opt/cni/bin
features/chost/file.include/usr/lib/cni

containerd needs a proper setup for the cni bin folder.
overall standard is /opt/cni/bin ... this is even hardcoded in some cni's m(
the debian standard is /usr/lib/cni ... debian packages use this
i guess the intended location of containerd is /var/lib/containerd/io.containerd.grpc.v1.cri.cni
so that is why this is set.
also fixing for plugins "io.containerd.internal.v1.opt" setting to "/var/lib/containerd/io.containerd.internal.v1.opt"

cleaning up containerd configs

---

hack/gl-search-package.sh

Patches `hack/gl-search-package.sh` to ignore caching. This should reduce confusion when using this gl-search-package.sh tool when caches of apt CDNs are not expired or invalidated yet

hack(gl-search): ignore caching query parameter

---

container/base-test/Dockerfile
container/build-cert/Dockerfile

***Why do we need this?*** 
* A new debian python update causes pip to refuse installation of packages if environment is marked as externally managed. This issue breaks our dev and nightly
* https://github.com/pypa/pip/issues/11381
* alternatively, we can delete the EXTERNALLY-MANAGED files
***Reproduce issue***
```
make --directory=container build-cert
```
Before this PR we run into this:
```
STEP 10: RUN pip install git+https://github.com/awslabs/python-uefivars
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv. …
```

Fix: use venv for container

---

tests/helper/sshclient.py

- Paramiko.py3compat was removed from paramiko 3.0.0
- tests/helper/sshclient.py used a helper function from the removed paramiko module
- this PR implements the trivial wrapper in the helper function
Fixes #1540

fix: paramiko.py3compat was deprecated and removed from paramiko

---

container/base-test/Dockerfile

fix(base-test): Fix `base-test` Dockerfile if file not present
/kind bug
/area os
This fix will check if the file is present and only proceed with further actions on it if available.
Fixes #1568
`None`
```feature user
- target_group: dependency
```

fix(base-test): Fix `base-test` Dockerfile if file not present

---

README.md

fix(build): Fix macOS build support
* Adjust documentation to install Python dependencies by pip
/kind bug
/area os
Fix macOS build support by adjusting the documentation regarding missing pip modules
Fixes #1566
:warning: **Warning:** Only merge after PR #1565
```feature user
- target_group: developer
```

fix(build): Fix `macOS` build support

---

.github/workflows/build.yml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml

The bash set builtin "pipefail" is not set by run-actions in github actions. 
See GitHub Docs [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference) and also [here](https://github.com/actions/runner/blob/main/docs/adrs/0277-run-action-shell-options.md).
An additional keyword "shell" can be specified, which has other defaults then leaving "shell" unspecified.
"shell: bash" sets the defaults to
```
bash --noprofile --norc -eo pipefail {0}
```
If `shell: bash` is not specified, pipefail is unset.
The simplified code:
```
false | tee some/log/destination
```
will return a non-error code 0, if tee was successful. 
This is obviously not what we want when executing a test.
To connect the link to our test issues: we …

fix(ci): github actions does not set pipefail

---

.github/workflows/tests-only.yml

* the "ref" for actions/checkout must refer to a
full commitish. Thus we need to extract the
short commitish via git
* cname is not required for test-only
* cname generation has no stable interface across
garden linux versions.

fix(ci): test-only action

---

.github/workflows/aws_tests.sh
.github/workflows/azure_tests.sh
.github/workflows/gcp_tests.sh
.github/workflows/tests.yml

/kind test
/area os
Improves output of automatic platform test and actually fixes the pipeline for the platform tests in the `rel-934` branch.
```feature developer
Fixes the automatic test pipeline for the rel-934 release of Garden Linux.
```

Improving automatic platform tests for rel-934

---

tests/integration/aws.py

* glci code was removed from this repo, but it did contain important changes.
* the code in gardenlinux/glci did not contain these important changes
* bringing back the outdated function from glci caused a broken setup.
* this commit fixes this issue

fix: bring back latest register_image fun with boot and uefi feature

---

hack/generate_release_note.py

Adds a script to generate release notes.
Release note content:
* annotations from package definition .yaml from gardenlinux-package-build repo
* public cloud publishing information via manifests from s3
Status:
* Not integrated in pipeline, thus keeping it in hack/ folder. Script will be moved and integrated into the pipeline in a separate PR

feat: generate release notes script

---

features/server/file.include/etc/systemd/resolved.conf.d/00-disable-llmnr.conf
features/server/file.include/etc/systemd/resolved.conf.d/01-disable-mdns.conf

Because of security implications, after discussions with @gehoern and @damyan we decided to disable LLMNR and mDNS in systemd-resolved.
Fixes #

fix(resolved): disable LLMNR and mDNS

---

.github/workflows/differential-shellcheck.yml

This PR adds a gh action to run shellcheck on new code without throwing warning for long-time running existing code.
Re-uses the shared GH action: https://github.com/redhat-plumbers-in-action/differential-shellcheck
Fixes #1577 
Runs for PRs against main and rel- branches.

ci: add differential-shellcheck action

---

tests/helper/tests/users.py

* A test checks the permissions returned via "sudo -l -U $user" for all available users.
To perform this tests, the admin user must be
able to execute it without entering a password
in a test setup.
For all other cloud providers we do this implicitly already via cloud-init or something else.
For Azure this is not managed by garden linux,
but by the user (in this example, the platform tests.)

fix(azure test): make nopasswd explicit

---

.github/workflows/differential-shellcheck.yml

Run differential-shellcheck on push event to avoid comments from github-code-scanning on every PR.
* see https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215

fix: differential-shellcheck on push event

---

.github/workflows/check-pkgs-includes-from-features.yml
bin/check-pkgs-availability.sh

* take all packages defined in any pkg.include, and check if the packages are available in the
repo.gardenlinux.io

feat(ci): scan for missing packages

---

features/_pxe/exec.config
features/_pxe/file.include/etc/dracut.conf.d/20-gl-live.conf
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-sysroot-generator.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/squash-mount-generator.sh

/kind bug
/area os
As stated in #1601 ignition doesn't seem to work properly when building *_pxe and this is because it's not booting properly, because the gardenlinux-live dracut module is not added when the initrd is generated. This is happening because the order of features, when building, has changed. 
These changes here ensure the gardenlinux-live dracut module is enabled when _pxe is used and an extra initrd generation is not needed (done in cloud/metal).
Fixes #1601

fix(pxe): enable gl-live dracut module, remove extra dracut run

---

bin/start-vm
tests/integration/kvm.py

* using start-vm inside the test container (podman) does not work, since the watchdog option is not available
* kvm tests can not connect, because the start-vm never started

fix: kvm platform tests

---

features/ali/file.include/etc/kernel/cmdline.d/10-console.cfg
features/aws/file.include/etc/kernel/cmdline.d/10-console.cfg
features/azure/file.include/etc/kernel/cmdline.d/10-console.cfg
features/cloud/file.include/etc/kernel/cmdline.d/00-default.cfg
features/gardener/file.include/etc/kernel/cmdline.d/10-console.cfg
features/gcp/file.include/etc/kernel/cmdline.d/10-console.cfg
features/kvm/file.include/etc/kernel/cmdline.d/10-console.cfg
features/metal/file.include/etc/kernel/cmdline.d/00-default.cfg
features/metal/file.include/etc/kernel/cmdline.d/10-console.cfg
features/openstack/file.include/etc/kernel/cmdline.d/10-console.cfg
features/vmware/file.include/etc/kernel/cmdline.d/00-default.cfg
features/vmware/file.include/etc/kernel/cmdline.d/10-console.cfg

See #1614 for the reason why vmware needs a different order
Other cloud flavors should keep the serial console as default, also the start-vm feature does not work if serial console is not default.

fix: serial console default on cloud provider

---

tests/helper/tests/users.py

/kind test
/area os
The user tests are performed by the azureuser
on azure. In theory, azureuser should have full admin priviledges and, just like root, no requirement
to enter a password for sudo.
However:
* `sudo -l -U` requires a password
* `sudo -s sudo -l -U` works passwordless
* this commit is a workaround so the test can do the actual check if any user on the image
has un-intendet sudo priviledges.

fix(tests): workaround for azure sudo -l -U check

---

features/vmware/vmware.ovf.template

/area os
**What this PR does / why we need it**: this is required for ignition to read data from vApp properties and not use iso by default.
From the [documentation](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.vm_admin.doc/GUID-14A25C25-A6F8-4818-9D0C-C0247C0672FA.html):
```
If you select ISO image, an ISO image that contains the OVF template information is mounted in the CD-ROM drive.
If you select VMware Tools, the VMware Tools guestInfo.ovfEnv variable is initialized with the OVF environment document.
```
Currently OVA file produced by `make vmware` would expect that template config comes from a mounted ISO image. I am not sure if this is what cloud-init requires.
In the case of ignition, one would …

feature(vmware): switch ovf transport to vmware tools

---

features/server/exec.config

Because of SAP requirements we need to force that only the members of _wheel_ are allowed to run _su_.
We also need to force that a new user's permissions for .bashrc, _.profile_ and _.bash_logout_ to be 0640.
We also need to remove "netgroup: nis" from nsswitch.conf .
Fixes #

server exec.conf fixes

---

features/cloud/file.include/etc/profile.d/50-autologout.sh
features/cloud/test/test_autologout.py
features/sap/exec.post
features/sap/file.include/etc/issue
features/sap/file.include/etc/issue.net
features/sap/file.include/etc/motd
features/sap/file.include/etc/tmpfiles.d/legacy.conf
features/sap/pkg.include

Because of some extra provisioning and testing steps _python3-apt_ and _acl_ packages are needed.
Because of SAP requirements no symlinks in _/var/log/_ should point outside of _/var/log/_; _/var/log/README_ is a symlink created by tmpfilesd, so we're removing it.
Because of SAP requirements, special messages should be displayed for the user upon logon.
Fixes #

SAP specific changes

---

features/log/file.include.stat
features/sap/file.include.stat
features/sap/file.include/etc/audit/rules.d/privilege_escalation.rules
features/sap/file.include/etc/audit/rules.d/system_integrity.rules

Because of SAP requirements, the audit rules files should have 0640 permissions.
Fixes #

fix: fix content and permissions on audit rules

---

features/azure/file.exclude
features/cloud/file.include/etc/modprobe.d/disabled_firewire.conf
features/cloud/file.include/etc/modprobe.d/disabled_fs.conf
features/cloud/file.include/etc/modprobe.d/disabled_net.conf
features/cloud/file.include/etc/modprobe.d/disabled_udf.conf
features/cloud/file.include/etc/modprobe.d/disabled_usb.conf

Because of SAP requirements, we're disabling various unneeded kernel modules.
Fixes #

fix: disable unneeded kernel modules

---

hack/gl-search.sh

**What this PR does**:
* Adds a `download` option to the `hack/gl-search` tool. Browse, select and download any package from repo.gardenlinux.io without apt 
**Why we need it**
* Convenient and apt-independent method to quickly download a garden linux package
* Useful if you are on mac, a non-debian based distro or don't want to add repo.gardenlinux.io to your apt sources.
* option to download packages is useful if you want to debug, analyze or test a package without building a Garden Linux
* `gl-search` is a tool with a terminal based user interface, it is not designed for automation
* Requirement is `fzf` 
* PR includes unrelated refactor in package selection code

hack(gl-search): download garden linux package

---

features/githubActionRunner/pkg.include

We currently have python dependencies to build Garden Linux.
The user needs to decide how these python dependencies are installed in a build environment.
In case of the GitHub Action Runner, we should use apt as long as we are going the "self-hosted" ami route. 
This PR just adds missing dependencies to: 
`features/githubActionRunner`.
For a public runner, we may want to use the requirements.txt and something else to install CRE and stuff (not topic of this PR)

fix(github runner): include python dependencies via apt

---

container/Makefile
features/cloud/pkg.include
features/firecracker/pkg.include
features/metal/pkg.include

/area os
Garden Linux aims to support the latest LTS Kernel. 
For the main branch of Garden Linux, we should upgrade to the latest LTS version of the Kernel.
```other user
Upgrade linux to 6.1
```
**Credits**:
Thanks @dnan0s for reporting this

feat: upgrade to 6.1 kernel

---

features/base/test/test_basics.py

This PR removes the `test_loadavg` test. See Background below for why we remove this test.
The `features/base/test/test_basicy.py:test_startup_time` is a test we can use to identify if something during boot time took significantly longer than expected. This startup_time test does not provide enough information to identify the causes, but it does identify that we need to investigate.  So we don't lose information when removing `test_loadavg`. 
The `startup_time` test could be enhanced to show more information if it failed. 
This loadavg test is failing for our azure images in our nightlies (for a while now).
*What does this test do?*
This test reads the second value returned by `/proc/loadavg`, and asserts that it is smaller than `0.5`. If it is greater than 0.5, the test fails.
*What does …

fix: remove test_loadavg

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml
VERSION
bin/make_reproducible_ext4
bin/makepart

Prepare release for Garden Linux 934.8
- update packages for security (see https://gitlab.com/gardenlinux/gardenlinux-package-build/-/blob/main/packages/934.8.yaml)
-  increased journal size 
- update configure-aws-crendentials github actions from v1 to v2

release: prepare 934.8

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/tests-only.yml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml

/kind cleanup
/area os
Updates the GH action [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) to v2 in all GitHub actions.
```feature developer
The GitHub action configure-aws-credentials was updated to v2 in all GH action workflows.
```

Update aws-credentials action to v2

---

.github/workflows/release.sh

* the github action runner require python3-click installed as dependency.
* Open PR: https://github.com/gardenlinux/gardenlinux/pull/1654
* disable auto generation until dependency is available

fix(ci): turn off auto release note gen

---

features/githubActionRunner/pkg.include

The `release` github action in our gardenlinux/gardenlinux repository generates a release item on https://github.com/gardenlinux/gardenlinux/releases
To automatically generate the notes included for this release item, we use the python script [generate_release_note.py](https://github.com/gardenlinux/gardenlinux/blob/main/.github/workflows/generate_release_note.py).
Arguments and parameters are parsed via the python library `click`. This PR adds the dependency to the githubRunner feature.

ci: add python3-click as dependency to auto generate release notes

---

features/azure/test/test_azure_times.py
features/base/test/test_basics.py

/kind test
/area os
Boot time on azure has unpredictable components. Thus, we increase the platform test boot time thresholds for the higher variance in boot time on azure platform.
Fixes #1633

fix(test): azure boot is slower than other cloud provider

---

features/azure/test/test_azure_times.py

I forgot to apply changes from #1651 to the copied test for azure

fix: remove load_avg again

---

features/metal/exec.config
features/metal/file.exclude

Because haveged has been removed, we should no longer enable the service and also no longer exclude /etc/init.d/haveged

fix: remove haveged related leftovers

---

.gitignore

Those binary files are created by the 'start-vm' script and most likely should not be committed.

chore: Gitignore uefi vars files

---

tests/helper/utils.py
tests/integration/azure.py

Fixes #1661 
Adds a wait cmd via `systemctl is-system-running --wait` when a ssh connection has been established.
Currently, SSH is ready before systemd is on azure. This leads to failing tests when a for example a `systemd-analyze` cmd is issued, because systemd will return a non 0 exit code with the error message that systemd has not finished booting yet (please try again later).

test(fix): wait for systemd to finish on azure

---

tests/helper/sshclient.py

/kind test
/area os
Platform tests should fail during fixture setup if an SSH connection to a VM cannot be established within time. This removes tons of unnecessary log output if the SSH connection fails to establish.
```feature user
Garden Linux platform tests will fail early if an SSH connection cannot be established after a default timeout of 5 minutes.
```

test: abort all tests if SSH connection fails

---

tests/integration/gcp.py

/kind test
/area os
Importing an image to GCP for testing might take longer than two minutes which used to be the max. timeout for this operation. This PR increases the timeout to 10 minutes.
```feature user
GCP platform tests now have a longer timeout of 10 minutes for the image import.
```

test: increase timeout for GCP Image import

---

README.md

/kind bug
/area os
**What this PR does / why we need it**: The current link to CI is broken
Fixes # - 
```doc operator
fix broken link in doc
```
I just assume that this is the correct README as I haven't checked what was there before, but it looks fitting.

Fix CI link in readme

---

hack/.gl-search-functions.sh
hack/gl-search.sh

This PR fixes hack/gl-search.sh for osx users.
The issue was that osx bash does not load exported functions into sub shells automatically.
This commit puts the functions in a separate file, which is then sourced on demand.
@fwilhe Thanks for reporting!

hack(gl-search): fix bash subshell function export

---

tests/integration/azure.py
tests/integration/gcp.py

/kind test
/area os
This PR introduces two small fixes to the platform tests which - under certain conditions - could leak resources in GCP and Azure:
- on GCP, the GCS bucket used for uploaded the image to test will be deleted immediately after the image is inserted into GCE (so far, we only deleted the image blob immediately after import but left the empty bucket)
- on Azure, the SSH key used for the test will be explicitely removed and a longer timeout is granted for deleting the resource group of the test 
```feature user
The cleanup code for automatic Garden Linux platform tests was improved to prevent resource leakage.
```

tests: improve resource leakage

---

.github/workflows/release.yml

* The release.yml requires the full committish because the GitHub "create release API" expects the full commitish. Thus, we should add a small hint to tell the user of release action to provide the full commitish. 
* if short commitish is used the API returns 422, and the release action does not show the reason.

fix(ci): info that release action requires full committish

---

.github/workflows/check-packages.yml
.github/workflows/generate_package_report.py

The generate_package_report.py returns None if no package pipeline failed.

fix(ci): check packages should return None in good case

---

features/cloud/exec.config
features/cloud/file.include/usr/share/pam-configs/garden

We do not properly handle the passwdqc pam module so it will end up being used twice.
Fixes #

fix: properly handle passwdqc pam module

---

bin/inject-sshkey

We've received a notice from security that for the _inject-sshkey_ script the user input is not properly sanitised and command injections are possible.
This PR should take care of that.
Fixes #

fix: sanitize input for inject-sshkey

---

features/gardener/info.yaml
features/gardener/test/file.exclude.d/file.exclude.list
features/gardener/test/test_files_excluded.py
tests/Dockerfile
tests/helper/tests/files_excluded.py

/kind bug
/area os
The `firewall` feature would configure nftables with a default policy to DROP everything on the input chain that is not SSH. This severely harms any kind of Kubernetes operation as it interferes with CNI. Therefore, the firewall feature must not be used with the Gardener feature.
Additionally: a test that can check for the presence of undesired files (like `/etc/nft.d` and `/etc/nftables.conf` in this case) and which will fail if these files were found in the image.
```feature user
The `firewall` feature is excluded from the `gardener` feature as it will severely interfere with Kubernetes and CNI operations.
```

Exclude firewall feature from gardener feature

---

features/_readonly/fstab.mod

While `ephemeral_cryptsetup` mode provides better security than just `ephemeral` (protection against root partition being modified externally while system is running) it does significantly slow down system boot up, because the dm-integrity partition needs to be initialized.
Therefore it should be disabled by default.

disable cryptsetup for _readonly feature

---

bin/start-vm

It seems that uefi boot should be the default.
For compatibility, the uefi flag still exists but it is not needed.
A new 'legacy-bios' flag was added to disable uefi if needed.
Also add ubuntu to the conditional case for loading uefi code/vars for debian.
Without this change, running in uefi mode on an ubuntu host fails when paths are not configured by hand.

start-vm: Make uefi boot default, fix logic for ubuntu

---

features/_boot/exec.late

With the latest systemd version (254), the _kernel-install_ commands from __boot/exec.late_ no longer produce the loader entries and the build fails.
Fixes #

Set SYSTEMD_ESP_PATH to /boot/efi for kernel-install

---

.github/workflows/nightly-rel934.yml

The nightly for rel-934 is configured to build with the wrong version ([see log](https://github.com/gardenlinux/gardenlinux/actions/runs/5758958280/job/15612307141#step:8:6067
)). It uses the default `now` which evaluates to the current dates Garden Linux version. But the expected behaviour is to use the version specified in the VERSION file of the target branch. 
This PR explicitly sets the version as input, by reading the content of the VERSION file used in the rel-934 branch.

fix(ci): nightly for 934 must be triggered with version

---

docs/configuration/time-configuration.md

/area os
Includes a documentation that describes how Garden Linux configures NTP/PTP time sources for the different cloud providers.
```doc user
A documentation that describes how Garden Linux configures NTP/PTP time sources for the different cloud providers in included in the repo.
```

doc: description of time sources

---

.github/workflows/build.yml
.github/workflows/nightly.yml
.github/workflows/publish_container.yml

Currently all targets use the default modifier during build. This installs things like containerd, docker, and systemd inside the container image, which greatly increases the size of the container base image. We should remove this.

fix: remove modifiers from container base image

---

tests/helper/tests/files_excluded.py
tests/integration/chroot.py

/kind test
/area os
The files_excluded test which was introduced in PR #1705 contained two small errors that would ignore files from a feature's `file.exclude`. Those are fixed with this PR.
```feature user
The files_excluded test now also catches files that were excluded via `file.exclude`.
```

fixes to file_excluded test

---

tools/clean_ec2_ami.py

/area os
The tool `clean_ec2_ami.py` can delete EC2 AMIs with a given name across all regions and delete the associated snapshots along with them. Alternatively, it can only set the AMI image sharing policy to _private_.
```feature user
A tool to remove given AMIs from Amazons EC2 was added to the Garden Linux repository.
```

feat: a tool to remove EC2 amis with a given name

---

features/lima/README.md
features/lima/info.yaml
features/lima/pkg.include

/area os
Adds a feature that allows to build a GL image that is usable with [lima](https://lima-vm.io).
This makes it convenient to manage virtual machines and ssh into them which will help (potential) users/admins of GL-based systems to test/integrate the system.
Implements a part of #1727
```feature user
```

Add a feature for using with lima-vm

---

tools/clean_openstack_images.py

/area os
The tool `clean_openstack_images.py` can delete OpenStack images with a given name across all regions. This is especially useful if multiple images with the same name exist. Needless to say that this tool needs to be used VERY carefully.
```feature user
A tool to remove given OpenStack images from Glance was added to the Garden Linux repository.
```

feat: a tool to remove OpenStack images by name

---

.github/workflows/generate_release_note.py

* remove click as dependency. Click is nice, but having less dependencies in the pipeline is nicer.
* make commitish parameter required
* If image cannot be found, print helpful error message instead of aborting
* Added usage doc in top of script for now.
This is currently not part of the automated pipeline. A garden linux maintainer must execute this locally
```
python3 -m venv venv
source venv/bin/activate
pip install boto3 pyyaml
.github/workflows/generate_release_note.py generate --version 934.10 --commitish f057c9b 
```

refactor: generate release note

---

.github/workflows/dev.yml

It seems wasteful to build dev images when only docs are updated
See github docs on syntax https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths
/kind TODO
/area os
Fixes #
```feature user
```

Skip dev workflow when docs are updated

---

tests/integration/gcp.py

/kind test
/area os
Buckets in GCP that are used to upload the Garden Linux images to be tested in the automated platform tests are now created with [uniform bucket level access](https://cloud.google.com/storage/docs/using-uniform-bucket-level-access).
```feature developer
Buckets in GCP that are used to upload the Garden Linux images to be tested in the automated platform tests are now created with ["uniform bucket level access"](https://cloud.google.com/storage/docs/using-uniform-bucket-level-access).
```

test(gcp): enable uniform bucket access

---

tests/integration/azure.py

/kind test
/area os
The network security group that gets created for a platform test in Azure should not allow incoming SSH traffic from 0.0.0.0/0 but only from the machine that runs and controls the tests, thus increasing security.
```feature user
The network security group for Azure base platform tests will only allow incoming SSH traffic from the test system.
```

test: limit azure nsg to incoming ssh from test system

---

docs/architecture/decisions/0002-dists-can-never-change-retroactively.md

This is the ADR for the decision to freeze apt distributions from repo.gardenlinux.io (e.g. `1270.0`).

adr: dists can never change retroactively

---

hack/lima-dev-env.yaml

/area os
Adds a definition for a Garden Linux dev environment using [lima](https://github.com/lima-vm/lima) which can be used with the [VS Code SSH Remote plugin](https://code.visualstudio.com/docs/remote/ssh).
This adds a free software alternative for Garden Linux dev environments on non-linux host OS (except for the non-OSS VS Code parts).
SSH remote development allows a almost 'native' feel for editing/development in VS Code.
```feature user
```

Add lima/vscode ssh plugin dev environment

---

features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/squash-mount-generator.sh
features/_pxe/image.pxe.tar.gz

For onmetal the squashfs is usually attached to the VM and presented as a block device - the gl.url parameter is used as gl.url=/dev/disk/by-id... - this PR is adding support for that.
We also need to switch to ukify to generate the unified images - the offsets used when using objcopy are no longer correct and the generation of the unified image fails.
Fixes #

Fix pxe feature

---

bin/README.md
bin/start-vm

fix(startvm): Add note regarding UEFI firmware for ARM64 guests
/area os
Add note regarding UEFI firmware for ARM64 guests
Fixes #1773
```feature user
- category: doc
```

fix(startvm): Add note regarding UEFI firmware for ARM64 guests

---

.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upload_to_s3.yml
.gitignore
Makefile
features/base/test/test_users.py
features/openstack-baremetal/README.md
features/openstack-baremetal/convert
features/openstack-baremetal/exec.config
features/openstack-baremetal/file.include/etc/cloud/cloud.cfg.d/01_debian-cloud.cfg
features/openstack-baremetal/file.include/etc/cloud/cloud.cfg.d/50-datasource.cfg
features/openstack-baremetal/file.include/etc/cloud/cloud.cfg.d/99_disable-network-config.cfg
features/openstack-baremetal/file.include/etc/cloud/ds-identify.cfg
features/openstack-baremetal/file.include/etc/default/grub.d/90_openstack_cc_ee.cfg
features/openstack-baremetal/file.include/etc/kernel/cmdline.d/40-enable-swap-cgroup-accounting.cfg
features/openstack-baremetal/file.include/etc/profile.d/50-autologout.sh
features/openstack-baremetal/file.include/etc/repart.d/root.conf
features/openstack-baremetal/file.include/etc/sysctl.d/20-cloud.conf
features/openstack-baremetal/info.yaml
features/openstack-baremetal/pkg.include
features/openstack-baremetal/test/test_check_files.py
features/openstack-baremetal/test/test_content_in_file.py
features/openstack-baremetal/test/test_packages_musthave.py
features/openstack-baremetal/test/test_users.py
features/server/test/test_users.py
flavours.yaml
make_targets/openstack-baremetal
tests/conftest.py

/area os
Introduces a new `openstack-baremetal` feature to enable Garden Linux to run on OpenStack/CCEE bare metal nodes to be used as worker nodes with Gardener.
**Important note for the reviewer:**
This is for Garden Linux **934**. Must be merged into the `rel-934` branch, NOT into the `main` branch.
```feature user
The openstack-baremetal feature will produce Gardener compatible images of Garden Linux that run on OpenStack/CCEE bare metal machines.
```

Include feature for OpenStack/CCEE bare-metal

---

hack/gl-pkg-url.sh

If a developer needs to download packages but has no access to apt, this script can be used to list urls to binary packages of the repo.gardenlinux.io packages.
We still need package build container, kernel module build container, and an automation. this is just a snippet. 
```
./gl-pkg-url.sh 934.10 amd64 linux-headers
```
outputs: 
```
http://repo.gardenlinux.io/gardenlinux/pool/main/l/linux-5.15/linux-headers-5.15-amd64_5.15.125-0gardenlinux1_amd64.deb
http://repo.gardenlinux.io/gardenlinux/pool/main/l/linux-5.15/linux-headers-5.15-cloud-amd64_5.15.125-0gardenlinux1_amd64.deb
http://repo.gardenlinux.io/gardenlinux/pool/main/l/linux-5.15/linux-headers-5.15-firecracker-amd64_5.15.125-0gardenlinux1_amd64.deb
http://repo.gardenlinux.io/gardenlinux/pool/main/l/linux-5.15/linux-headers-5.15.1 …
```

hack: script to lists download paths of a given apt package

---

features/vmware/exec.config

fix(vmware): Fix vmware feature in combination with ARM64 based systems
/kind bug
/area os
Fix vmware feature in combination with ARM64 based systems.
Currently, the combination of the VMware feature, ARM64 based systems and ignition is unsupported and results in unbootable images.
Fixes #1778
```feature user
```

fix(vmware): Fix vmware feature in combination with ARM64 based systems

---

bin/README.md
bin/pkg2deps

feature(pkg2deps): Add `pkg2deps` to find missing dependencies of a given package from foreign repos
/area os
Add `pkg2deps` to find missing dependencies of a given package from foreign repos
Quicktest:
```
./pkg2deps -r http://ftp.debian.org/debian -d trixie -v 2.65 -g 934.10 -p dpkg-www
```
or
```
./pkg2deps -r http://ftp.debian.org/debian -d trixie -v 1.22.0 -g 934.10 -p dpkg
```
All params are documented within the docs, however for this example:
* -r | --remote | remote repo path
* -d | --distribution | Repo Distribution to use (Debian: trixie, bookworm, Sid,... | Garden Linux: 934.10,...)
* -g | --gardenlinux-version | Garden Linux Version to validate against (e.g. 934.10, …

feature(pkg2deps): Add `pkg2deps` to find missing dependencies

---

hack/lima-dev-env.yaml

/area os
Pin the images for dev env to a specific debian testing image. Currently there is a incompatible combination of the kernel and crun in debian testing ([bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1053821)), the selected images are old enough to not have this issue.
It might make sense to always have pinned images here but they would need to be updated from time to time.
Fixes #
```feature user
```

Pin debian images for dev env

---

tests/helper/sshclient.py

/kind test
/area os
Removes the (upstream) deprecated import `paramiko.util.u` which is not used in our test code.
Fixes #1799.
```feature user
An unnecessary import was removed from the Garden Linux test harness.
```

test: remove deprecated u import

---

.github/workflows/build.yml
.github/workflows/differential-shellcheck.yml

* @nkraetzschmar added a fix in his fork of [workflow-telemetry-action](https://github.com/nkraetzschmar/workflow-telemetry-action) github action  which is not in upstream. Forking his fork to move code ownership to gardenlinux org 
* pin other third party actions to commit

ci: pin extern github actions to commitsh or fork

---

hack/lima-dev-env/gl-dev.yaml

This debian testing image includes a fixed version of crun (1.11-1)
Follow up for #1796

Update dev env debian image

---

.github/workflows/build.yml
.github/workflows/build_container.yml
.github/workflows/check-packages.yml
.github/workflows/differential-shellcheck.yml
.github/workflows/nightly-rel934.yml
.github/workflows/publish_container.yml
.github/workflows/release.yml
.github/workflows/tests-only.yml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml

For consistency it makes sense to just apply actions pinning everywhere.
This was done using mheap/pin-github-action
Dependabot should be clever enough to update the pinned versions.

Pin all gh actions 

---

.github/workflows/release-page.yml

- Use 8 character long commit hash instead of full commit hash
- the `generate_release_notes.py` script requires the commit hash. The commit hash is used to retrieve the artifact. Therefore it must be the same length as in the artifact

fix: use short commitish also for generation of release note script

---

.github/workflows/generate_release_note.py

The package update section is generated with yaml files from the gitlab pipeline: 
https://gitlab.com/gardenlinux/gardenlinux-package-build/-/tree/main/packages?ref_type=heads
However, for a `.0` major release we do not have such a file. These files define the difference in packages between a patch release and the initial major

fix(generate release notes): no package update section for new major

---

.github/dependabot.yml
tests/Containerfile
tests/Pipfile.lock

* Pipfile.lock will be  updated via Dependabot
* Generating Pipfile.lock dynamically in container fails. This commit removes the dynamic Pipfile.lock generation in the container build step, thus removes the error source that the Pipfile.lock generation can fail during the container test image build step
* Fixes nightly and dev builds 
Fixes #1815 
Tested locally with 
```
podman build --squash --tag test --build-arg base="$(./build --print-container-image)" tests 
```

fix: check in Pipefile.lock for test container

---

hack/lima-dev-env/gl-dev.yaml
hack/lima-dev-env/update-lima-dev-env.py

Automatically use the latest version of the github cli when regenerating the lima dev env manifest.

chore(hack/lima-vm): Update github cli in script

---

.github/workflows/gl-kernelurls.py
bin/check-pkgs-availability.py
bin/garden-version
bin/pkg2deps
container/base-test/Dockerfile
docs/02_operators/apt_repo.md
hack/gl-pkg-url.sh

https is offered and configured for repo.gardenlinux.io, thus this should be the default in documentation, scripts and other. 
search and replace all http://repo.gardenlinux.io references with https://repo.gardenlinux.io

fix: use https for gardenlinux repo

---

.github/workflows/tests.yml
tests/integration/gcp.py

/kind test
/area os
Enables nightly tests for ARM64 images on GCP. Also fixes an embarrassing bug (missing function definition) in the GCP test cleanup code.
Before merging, the GCP test region and zone must be set to `europe-west4` and `europe-west4-c` respectively in GitHub Actions secrets.
```feature user
Nightly build artefacts for ARM64 are platform tested on GCP.
```

test: test ARM64 images on GCP

---

container/base-test/Dockerfile

/kind test
/area os
The only binary from the guestfs universe that is used in Garden Linux test containers is `virt-copy-in` which is actually part of `guestfish`. Therefore, all the other dependencies (especially Perl) of `libguestfs-tools` can be omitted.
```feature user
Guestfish is used instead of libguestfs-tools in test containers
```

Use guestfish instead of libguestfs-tools in test containers

---

container/Makefile
container/base-test/Dockerfile
tests/Pipfile

/kind test
/area os
Require azure-cli >= 2.44.0 for Azure platform tests. Also make sure that the `Pipfile.lock` is actually used in building the integration test containers so that we have tighter control over which versions of the packages are used.
```feature user
test: Require azure-cli >= 2.44.0 for tests
```

test: Require azure-cli >= 2.44.0 for tests

---

.github/workflows/gcp_tests.sh
.github/workflows/tests-only.yml
.github/workflows/tests.yml
tests/integration/gcp.py

/kind test
/area os
Supplies the target architecture of the artefact to be tested to the GCP platform test so that image names can be differentiated by architecture. Also selects the proper machine type.
Fixes 409 errors on GCP.
```feature user
Target Architecture of Garden Linux artefacts will be handed into GCP platform tests.
```

test: use architecture in GCP image names

---

features/vhost/pkg.include

fixes the 
gir1.2-libosinfo-1.0 : Depends: gir1.2-libxml2-2.0 but it is not installable
since virtinst is anyhow not needed.

fixing git1.2 availability issue

---

.github/labeler.yml
.github/pull_request_template.md
.github/workflows/labeler.yml

* Add github labeler action
* must be merged to main before the new labeler action can assign labels to PRs 
* test repo: https://github.com/Vincinator/test-labeler/pull/1 
* use PR template from gardenlinux/.github org repo

github: add labeler action 

---

features/_ignite/file.include/etc/dracut.conf.d/30-ignition.conf

Related to #1877 and #1879 but IMHO this is the proper fix, the dracut _systemd-networkd_ module needs to be explicitly requested so that all the dependencies are properly generated (url-lib, network, network-legacy).
Fixes #

fix: specifically request systemd-networkd for the ignite feature

---

SECURITY.md

Updating the security contacts.
Adding Niko, Florian, Stefan and myself.
Removing @msohn and @mvladev as person of contact for security issues (please let me know if you still volunteer and want to be mentioned in that SECURITY.md, happily add you again  just let me know)

doc: update security contacts

---

container/base-test/Dockerfile

* parameterize base-container debian dist
* install packages from debian dist by default
* apt pinning to install pkgs from repo.gardenlinux.io * define it explicitly, avoid unecessary conflicts
The integration test container build step fails (for rel-1312 branch), because there is a package conflict with gcc (see [here](https://github.com/gardenlinux/gardenlinux/actions/runs/7254256520/job/19775761030#step:4:60)). 
This is completely unrelated to the use case of the test container. Test container is used for communicating with the target test platforms, we do not need to maintain the CLI tools and CLI tool dependencies in our gardenlinux repo

base test container: use debian dist

---

.github/dependabot.yml
build
builder.dockerfile

This change is needed to allow keeping the builder updated via dependabot.

Define builder version in dockerfile

---

build
builder.dockerfile

This should fix the failed nightly builds because they make assumptions about what is written to stdout.

Update builder to include gardenlinux/builder#57

---

bin/start-vm

This PR adds the optional flag `--tpm2` to the `start-vm` shell script. If enabled, an emulated TPM chip is launched by a process in the background and injected into the VM as a new device.
Very useful for debugging and developing TPM related features, `swtpm` needs to be installed on the hosts OS though.

Add TPM2 emulation support to start-vm using `swtpm`

---

features/openstackbaremetal/file.include/etc/modprobe.d/10-disallow-nouveau.conf

Disables the nouveau kernel driver on OpenStack baremetal flavour by adding a corresponding parameter to `/etc/modprobe.d`.
```feature user
nouveau kernel driver is disallowed on OpenStack baremetal flavour.
```

Disallow loading of nouveau driver on OpenStack baremetal

---

.gitignore

Similar to efi vars files, those might be created when running `start-vm`. There is no plausible reason why one would want to commit this, so adding it to gitignore.

Add ipxe files to gitignore

---

features/ssh/file.include/etc/ssh/sshd_config

PR #1500 was introduced because some limitations with Azures Marketplace certification required `ssh-rsa` to be available as cipher algorithm for SSH host keys.
As Garden Linux is now published through Azure community image galleries and no longer via the Azure Marketplace, deviating from the recommended defaults for sshd is no longer required and thus, PR #1500 (commit 71e5a67f458506327b99755e5682d6f6b6ccaa7d) should be reverted.
```feature user
ssh-rsa is no longer available as cipher algorithm for SSH host keys.
```

Revert "enable ssh-rsa as HostKeyAlgorithm"

---

bin/start-vm

fix(startvm): Remove watchdog option due to incompatibility in newer versions
Remove watchdog option due to incompatibility in newer versions of `qemu-system-x86_64`. However, this also only worked with Debian version and on x86.
Fixes #1854
```feature user
```

fix(startvm): Remove watchdog option due to incompatibility in newer versions

---

features/_secureboot/pkg.include

* before 6.6 kernel the dracut pkgs were installed as dependency for the linux kernel
* 6.6 debian based garden linux kernel does not have this dependency.
* installing dracut explicitly in a feature where we need it
Fixes secureboot targets 
- ⚠️ There are more tests failing. These are unrelated to this PR and will be addressed with a new kernel containing: https://gitlab.com/gardenlinux/gardenlinux-package-linux-6.6/-/merge_requests/1  (CONFIG_REMOTEPROC got enabled in 6.6 non-cloud arm64 debian kernel config, and we did not explicitly disable it before)

fix: explicitly install dracut for secureboot feature

---

features/base/test/test_proc.py

This PR changes test_proc.py, so that it checks for files **starting with** "proc/" instead of containing "proc/" in the file name. 
The previous implementation of test_proc.py checked for any files in the image artifact containing the string "proc/". 
Fixes nightly builds ([see](https://github.com/gardenlinux/gardenlinux/actions/runs/8000143319/job/21866538698#step:14:352)) 
```
>       assert len(matches) == 1, f"/proc is not empty. Found: {matches}"
E       AssertionError: /proc is not empty. Found: ['proc/', 'usr/lib/modules/6.6.17-arm64/kernel/drivers/remoteproc/', 'usr/lib/modules/6.6.17-arm64/kernel/drivers/remoteproc/mtk_scp.ko.xz', 'usr/lib/modules/6.6.17-arm64/kernel/drivers/remoteproc/mtk_scp_ipi.ko.xz', …
```

fix: rewrite test_proc.py to check if proc/ is empty in image artifact

---

cert/Makefile
cert/gardenlinux-tpm-sign.conf
cert/tpm-sign.conf

As it often cannot be guaranteed that all hardware TPM chips support the standard key size of 4096 bit, this PR allows the generation of specific RSA keypairs for signing TPM PCR values, which only have a size of 2048 bit.

Support generation of 2048 bit RSA keys for TPM PCR value signing

---

README.md

README.md of main should only describe how main branch is build. Branches containing legacy code contain also a legacy readme.

doc: remove 934 reference in README.md

---

test

This is a sanity check. Running `./test foo` without having run `./build foo` before results in undesired behavior.
Fixes #1987

Test: Run only if artifact under test is built

---

.github/workflows/upload_to_s3.yml

cname is empty in upload to s3 pipeline because of issue #1980
```
Error: OCI runtime error: chmod `run/shm`: Operation not supported
```
https://github.com/gardenlinux/gardenlinux/actions/runs/8110254782/job/22168856733#step:7:26
Apply workaround from #1982 also for `.github/workflows/upload_to_s3.yml`
Fixes #1994

Fix nightly: apply crun workaround for upload to s3 action

---

tests/integration/gcp.py

Adds `GVNIC` and `VIRTIO_SCSI_MULTIQUEUE` guestOsFeatures to images for GCP platform tests.
Once this is merged and had a successful run, consider merging https://github.com/gardenlinux/glci/pull/50.
```feature user
Adds `GVNIC` and `VIRTIO_SCSI_MULTIQUEUE` guestOsFeatures to images for GCP platform tests.
```

tests: add GVNIC and VIRTIO_SCSI_MULTIQUEUE to GCP tests

---

.github/workflows/build.yml
.github/workflows/publish_container.yml
.github/workflows/tests-only.yml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml

Platform tests fail because of empty cname, and download-artifacts step tries to download all because no input was provided due to empty cname
```
Error: OCI runtime error: chmod `run/shm`: Operation not supported
cname=
```
Therefore this PR does two things:
1. Include fix, so that cname can be resolved with `./build --resolve-cname` in pipeline (crun workaround)
2. Make `get cname` steps fail in github actions bash environment that has **not** set `pipefail`

Fix platform tests apply crun workaround

---

tests/integration/gcp.py

Reverts gardenlinux/gardenlinux#2002 because of errors that appeared with GCP platform tests after this PR got merged. Needs more investigation.

Revert "tests: add GVNIC and VIRTIO_SCSI_MULTIQUEUE to GCP tests"

---

cert/Makefile

Needed because of this commit: https://github.com/awslabs/python-uefivars/commit/ec1eab1717c65ea36ca7160c96fe0e10e071fb66
Fixes this error `make: uefivars.py: No such file or directory` in our ci pipeline in the `certificates` job.

Rename uefivars.py to uefivars

---

features/openstack/file.include/etc/cloud/cloud.cfg.d/99_disable-network-config.cfg

Garden Linux images running on OpenStack baremetal need to be able to use cloud-init to set up potential network bonds
that get configured through a config-drive.
```feature user
cloud-init may configure the network ion OpenStack Baremetal
```

Enable cloud-init network config for OpenStack Baremetal

---

tests/integration/azure.py

add an additional force parameter to just delete the resource group without individually deleting all
sub-resources and set it to True for the moment
Fixes [#2036](https://github.com/gardenlinux/gardenlinux/issues/2036)
```feature user
```

simplify gallery image cleanup

---

features/openstackbaremetal/file.include/etc/cloud/cloud.cfg.d/65-network-config.cfg
features/openstackbaremetal/file.include/etc/cloud/cloud.cfg.d/99_disable-network-config.cfg
features/openstackbaremetal/file.include/etc/dracut.conf.d/49-include-bnxt-drivers.conf
features/openstackbaremetal/pkg.include
features/openstackbaremetal/test/test_check_files.py

To configure network bonds/trunks/LACP on OpenStack baremetal machines, cloud-init must be allowed to configure the network and hand over the network config to netplan so that it can take care of initialising the bond* interface before any
dhcp request is made.
Also, since some network interfaces take a little longer to initialise, this can introduce a race between them and
cloud-init-local which will fail if the network interfaces listed in a `network_config.json` are not present yet. The `bnxt_en` network driver is placed into initrd so that it loads and initialises at a very early stage to circumvent the race.
We need to resort to `netplan.io` because cloud-inits [network renderer for systemd-networkd](https://github.com/canonical/cloud-init/blob/ …

Cloud-init should configure the network on OpenStack Baremetal

---

features/ali/pkg.include
features/aws/pkg.include
features/openstack/pkg.include
features/openstackbaremetal/pkg.include
features/vmware/pkg.include

Remove python3-boto because it is not needed and does not exist in current debian testing. 
Fixes nightly 
python3-boto was removed from debian testing. 
```feature user
removed python3-boto from Ali, AWS, open stack, openstackbaremetal
```

remove python3-boto

---

.github/workflows/get_kernelurls.py

Note: release page action does not need to be run again for 1443.0, I triggered it from the  fix-generate-release-page-for-new-package-pipeline branch

use packages.gardenlinux.io for release page generation

---

bin/start-vm

Small syntax error on line 691 when _--tpm2_ is not used.
On debian, newer versions of OVMF no longer provide the 2M uefi code and vars.
Fixes #

Small fix for start-vm

---

features/sapmachine/exec.config
features/sapmachine/update-sapmachine.py

So far the SapMachine version we include needs to be updated manually.
This PR adds a script to help with that, but the update is still a manual process.
The script finds the latest minor/patch version of a given major version along with the checksums of the tarballs.
Running `update-sapmachine.py` will print out the variables to be used in `exec.config`.
A potential improvement is to edit the `exec.config` script automatically via `update-sapmachine.py`.
We still want the checksum and the exact SapMachine version to be stored in the git repo, so we don't want to hide this by automatically running `update-sapmachine.py` during the build for reproducibility reasons.

Add script to automatically bump SapMachine version

---

features/_dev/test/groups.chroot
features/gardener/test/groups.chroot

The file those links point to don't exist anymore.
Follow up for #985

Delete links to deleted file groups.chroot, follow up for #985

---

features/gdch/README.md
features/gdch/convert.gcpimage.tar.gz
features/gdch/exec.config
features/gdch/file.include/etc/cloud/cloud.cfg.d/01_debian-cloud.cfg
features/gdch/file.include/etc/cloud/cloud.cfg.d/99_disable-network-config.cfg
features/gdch/file.include/etc/kernel/cmdline.d/00-cmdline.cfg
features/gdch/file.include/etc/kernel/cmdline.d/10-console.cfg
features/gdch/file.include/etc/modprobe.d/gce-blacklist.conf
features/gdch/file.include/etc/sysctl.d/60-gce-network-security.conf
features/gdch/file.include/etc/systemd/timesyncd.conf.d/00-gardenlinux-gcp.conf
features/gdch/file.include/usr/lib/udev/google_nvme_id
features/gdch/file.include/usr/lib/udev/rules.d/64-gce-disk-removal.rules
features/gdch/file.include/usr/lib/udev/rules.d/65-gce-disk-naming.rules
features/gdch/info.yaml
features/gdch/pkg.exclude
features/gdch/pkg.include
features/gdch/test/test_blacklisted_packages.py
features/gdch/test/test_packages_musthave.py
features/gdch/test/test_users.py

Adds a GDCH feature to Garden Linux release 1312 for testing purposes.
Might need to be cherry-picked/ported to `main`.

Add a gdch feature to Garden Linux rel-1312

---

.github/workflows/publish_container.yml

Should fix this failed run https://github.com/gardenlinux/gardenlinux/actions/runs/8354499056/job/22868816771#logs

Set GH_TOKEN in workflow to use gh cli

---

.github/workflows/release_note.py

* security update annotations are not tracked in package repository, but in security tracker and other internal tooling.
* new package pipeline does not contain annotations for CVEs, thus we need to remove the packages updates section in the release page automation => need to include it manually

fix: release page automation - rm package updates section

---

.github/workflows/build.yml
.github/workflows/upload_to_s3.yml

Remove failing image config due to missing arm64 build of `open-vm-tools`
Those images are not consumed by anyone.
Fixes https://github.com/gardenlinux/process/issues/50
Nightly job using this pr branch: https://github.com/gardenlinux/gardenlinux/actions/runs/8601644058

Stop building openstack and vmware for arm64

---

LICENSE.md
README.md
docs/01_developers/build_image.md

This pull request enhances the README.md file to serve as a more comprehensive starting point for individuals unfamiliar with Garden Linux, including non-maintainers and developers. The adjustments aim to streamline the content and provide clear guidance on initiating the build process and accessing releases.
* badge showing latest LTS version of Garden Linux
* simple quick start sections: build, test, download
* remove unecessary license badge. we have LICENSE.md file which is commin practise and Github also displays it in UI
* remove toc. README is simple enough.
* add reference to bare container
* add reference to base container
* add reference to nvidia installer
* remove details about integration tests. Details …

Improve docs

---

.github/release.yml

* GitHub supports the generation of automatic release notes based on PRs. 
* PRs can be filtered and sorted into categories via PR labels
* more details: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

GitHub changelog generation

---

features/gdch/pkg.exclude

gdch requires chrony
Fixes the nightly platform build for new gdch feature

(main branch) fix gdch: exclude systemd-timesyncd in favour of chrony

---

features/base/test/test_kernel_config.py
features/cloud/test/test_kernel_config.py
features/metal/test/test_kernel_config.py
tests/helper/utils.py

Refactors the kernel config tests
* Checks all configurations of all installed kernels
* in theory, only one kernel is installed during build time. But if we include two different kernels in the image (intentionally or unintentionally), then we will have multiple /boot/config-* files, and the result of the kernel config test is useless- can not be trusted. Therefore this test does not assume anything about the number of installed kernels, and just verifies that all included configs are correct.  
* Check each config individually to identify wrong config directly
* Three test types:
* is enabled: either `y` or `m`
* is disabled: either not set or `n`
* is exact: check if exactly this line is contained in the config
Add another layer of verification …

tests: add kernel config tests

---

features/rootlessPodman/README.md
features/rootlessPodman/exec.config
features/rootlessPodman/info.yaml
features/rootlessPodman/pkg.include
features/rootlessPodman/test/test_packages_musthave.py

Feature for setting up podman to be used in rootless mode.
This is intended to be used in combination with the lima feature, but it might also be used standalone.

Rootless podman feature

---

features/_oci/README.md
features/_oras/README.md

Updates remaining references to old build.sh.  fixes #1689

docs: use new builder in oras and oci feature README

---

hack/enable_inactive_workflows

script to enable all workflows across all gardenlinux repos if GitHub once again decides to disable them due to inactivity

add hack/enable_inactive_workflows script

---

features/base/test/test_umask.py
tests/conftest.py

**What this PR does**
- repair `non_gcp` flag for python platform tests
- add a second umask test `test_umask_cmd` (check via `umask`) 
- disable `test_umask` for platform gcp tests (check by reading UMASK value from /etc/login.defs) 
**Why we need it?**
- pam_umask reads the umask value from /etc/login.defs: we need to test /etc/login.defs
- `/root/.bashrc`, `/root/.profile`, ... can overwrite default value from /etc/login.defs
- ➡️  we need to check via umask cmd in root bash environment
Conclusion: we need both tests. Disabling `/etc/login.defs` for gcp only is only acceptable, because we additionally have chroot tests that still check the file content.
|               | platform test (gcp) | chroot tests (gcp) |
|---------------|---------------|--------------|
| login.defs    | …

Umask test use umask cmd

---

features/_readonly/exec.config
features/_readonly/pkg.include
features/_secureboot/exec.config

In this commit we imitation the fix\[0\] for `_secureboot`. Since systemd 255 has renamed the  naming from pcrextend to pcrphase. Without the build fails:
building raw image kvm-python_dev_readonly-amd64-today
[.build/kvm-python_dev_readonly-amd64-today-local.raw 2024-05-08 11:00:22] using base fstab: /builder/features/base/fstab
[.build/kvm-python_dev_readonly-amd64-today-local.raw 2024-05-08 11:00:22] modifying fstab with /builder/features/_readonly/fstab.mod
[.build/kvm-python_dev_readonly-amd64-today-local.raw 2024-05-08 11:00:22] ---- fstab ----
[.build/kvm-python_dev_readonly-amd64-today-local.raw 2024-05-08 11:00:22] LABEL=EFI    /efi    vfat    ro,umask=0077    type=uefi,size=128MiB
[.build/kvm-python_dev_readonly-amd64-today-local.raw 2024-05-08 11:00:22] LABEL=USR    /usr …

Fixes the _readonly build

---

.github/workflows/release_note.py

We were missing the target_commitish parameter which means that github is using main branch instead.
Docs:
https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release

Add target_commitish parameter to POST release api call

---

.github/workflows/nightly.yml

Automatically uploads build artefacts to S3 in AWS CN as well to have better distribution of build artefacts to Chinese cloud platforms.
Fixes #2121 and fixes #2130
Tested in https://github.com/gardenlinux/gardenlinux/actions/runs/9398491888 and verified that artefacts are indeed present in S3 bucket of Garden Linux' AWS China subscription.
Must be cherry-picked to relevant release branches (rel-1312 and rel-1443) as well.

Upload build artefacts to AWS S3 in China during nightly

---

.github/workflows/dev.yml

Currently, a `dev` build does not retrieve the correct version if it is executed for a rel-* branch. 
This PR enables dev actions to run on rel-* branches. 
Pushes to a `rel-` branch will trigger a dev build with the correct version set. 
**Notes for Reviewer**
If this is merged, we will also backport it to rel-1443 branch

ci: read version from VERSION file

---

.github/workflows/upload_to_s3.sh

During the upload to S3 job of the `nightly` Action:
- md5sums and sha256sums will be calculated for every artefact
- both values will be supplied to S3 to verify proper upload ([ref](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html))
- md5sum and sha256sum will be added to the release manifest
- md5sum and sha256sum will be added as tags to every uploaded artefact (along with Garden Linux version, platform, architecture and comittish)
All this to have the possibility to track and check integrity of image artefacts right from the moment they come out of the build pipeline.
Tested in https://github.com/gardenlinux/gardenlinux/actions/runs/9465059139
Do not cherry-pick to `rel-*` …

Include checksums and additional tags to S3 artefact uploads

---

.github/workflows/get_kernelurls.py

The workflow failed because the 1312 line of Garden Linux still uses the repo.gardenlinux.io urls for packages
Merging this pr should fix [this failed workflow](https://github.com/gardenlinux/gardenlinux/actions/runs/9501093431/job/26185788979)

Handle special case for release page generation for version 1312.5

---

.github/workflows/release-page.yml
.github/workflows/release_note.py

* GitHub API requires the full commitish to create a release page
* To retrieve the correct metadata of Garden Linux published images from S3, we need to use the short commitish (8 characters). 
* Fixes output format of kmodbuild container

fix release page use long commitish

---

bin/start-vm

With these changes, NixOS users can build and start Garden Linux VMs without fiddling with the script.
For all features, you need the following NixOS configuration on x86_64:
```nix
environment.systemPackages = with pkgs; [
qemu
];
virtualisation.libvirtd = {
enable = true;
qemu.ovmf.packages = with pkgs; [
OVMFFull.fd
pkgsCross.aarch64-multiplatform.OVMF.fd
];
};
```
Ping @parthy @notandy 
N/A
I've successfully tested this on NixOS 24.05 to boot the `x86_64` `kvm-python_dev` target. I haven't tested the aarch64 image, because I don't know yet how to cross-compile an aarch64 image. I've manually validated the paths, though.
```feature user
NONE
```

Support NixOS in bin/start-vm

---

features/base/test/test_metadata_connection.py

We have to disable the IMDSv1. The test will fail without a token. So we request a token from IMDSv2 and provide it for our current test case.

Fix/disable IMDSv1

---

features/base/exec.config
features/stig/exec.config

Fixes the case when `/etc/login.defs`  does not contain a UMASK value by adding a check, and appending the desired configuration in this case.  
Fixes #2191

fix: set umask value even if /etc/login.defs did not set it before

---

.github/actions/setup/action.yml
.github/workflows/lima.yaml
.github/workflows/stig.yaml
.github/workflows/tests.yml

- Starting with the GitHub image runner version `20240225.1.0` podman/crun stopped working correctly. Rough summary is that the used kernel and crun 0.17 did not play well together. 
- @fwilhe introduced a workaround by using the binary release of crun 1.14.3
- The bug was fixed in ubuntu package 0.17+dfsg-1.1ubuntu0.1
- The workaround is most likely no longer needed. @fwilhe and I tested successfully with the current runner version (`20240721.1.0`, `ubuntu-latest`) and without the workaround
- I also checked that the current runner has crun 0.17+dfsg-1.1ubuntu0.1 
- This PR reverts the workaround so that the crun version that comes with the runner image is used.
https://github.com/actions/runner-images/issues/9425#issuecomment-1966373104 (runner bugreport) …

gh-actions: Remove Ubuntu 22.04 crun workaround

---

docs/architecture/decisions/0004-vendoring-go-dependencies.md

Motivated by https://github.com/gardenlinux/package-containerd/pull/2

Document architecture decision on vendoring go dependencies

---

docs/02_operators/apt_repo.md

Tiny nitpick, but the iso 8601 is more appropriate in an English text compared to the former way of using the German standard for noting dates.
More information on the date format:
- https://www.iso.org/iso-8601-date-and-time-format.html
- https://xkcd.com/1179/

Use iso 8601 date format

---

hack/compare-apt-repo-versions.sh
hack/get-selected-gl-bom.sh
hack/parse-aptsource.py

Helpful script to investigate differences in repo versions between different Garden Linux versions.
This script will download the apt source file of two given versions, unpack and compare them. Example output:

Add script to compare apt repo versions

---

.github/workflows/parse_aptsource.py
.github/workflows/release_note.py

Add a list of selected packages with their respective versions to the release notes workflow.
This should give Garden Linux developers and users a way to quickly identify the versions of relevant components in a specific Garden Linux version.

Include sbom information in release notes

---

.github/workflows/release_note.py
.gitignore

Adds a simple dry-run flag, so that we can re-generate the release note locally without uploading changes directly to a release in GitHub. 
Follow up for #2256

Release note dry run

---

.github/dependabot.yml
build
builder.dockerfile

Simplify the build by removing the dockerfile indirection.
This was intended to be used with dependabot but never really worked with how the builder image is published, so we can just remove it to simplify.

revert changes from #1874

---

.github/workflows/build.yml
.github/workflows/upload_to_s3.yml

This reverts commit f43dbbf49784e4a74183cb86bd2ceecf809e4aca.
Enable openstack arm64 targets in build.yml action and upload_to_s3.yml action. 
Fixes #2265
open-vm-tools is available in 1592.0 repo in general (see https://github.com/gardenlinux/repo/blob/41d727a2e85314cd4fc772d33e8d15e7bbe8876b/package-imports#L97) and also for arm64 specifically (checked with hack/gl-search.sh). 
As documented in the commit message of the reverted  f43dbbf commit, `open-vm-tools` was missing. It is back in debian testing. 
```feature user
enable arm64 openstack images
```

Revert disable openstack arm64 for rel-1592

---

.github/workflows/build.yml
.github/workflows/upload_to_s3.yml

This reverts commit f43dbbf49784e4a74183cb86bd2ceecf809e4aca.
Enable openstack arm64 targets in build.yml action and upload_to_s3.yml action. 
Fixes #2265
As documented in the commit message of the reverted  f43dbbf commit, `open-vm-tools` was missing. It is back in debian testing. 
```feature user
enable arm64 openstack images
```

Revert "Stop building openstack and vmware for arm64 (#2069)"

---

hack/compare-apt-repo-versions-gl-debian.sh

Script might be useful to chose which packages to upgrade in Garden Linux patch releases
Run the script like this `./hack/compare-apt-repo-versions-gl-debian.sh 1592.0`
Output looks like this
```
base-files 13.3 13.5
bash 5.2.21-2.1 5.2.21-2.1+b1
binutils 2.43-1 2.43-2
```
where the first version number is the version in Garden Linux, the right version number is the version in debian testing as of now.

Add Script to compare the apt repo version of Garden Linux with Debian

---

tests/integration/gcp.py

Virtual machines used in GCP platform tests must not import/include project wide SSH keys but only those that are explicitly specified in the test code.
```feature user
Project wide SSH keys are now blocked on virtual machines for GCP platform tests.
```

Block project wide SSH keys in GCP platform tests

---

build

Includes fix: make cross-arch build work with rosetta on mac  https://github.com/gardenlinux/builder/commit/68983eda4daa6627899749f80d63a678e6152728

Update builder image

---

features/vmware/make-ova

The actual-size is not the actual file size.
Not sure what it is, but differs from st_size and vsphere aborts loading files with the value qemu, 
but accepts them with the st_size value, which matches also what tar reports, when it is in the ova.
Fixes #2322
```
bugfix operator Fixes the import of OVA by correcting the `ovf:size` attribute
```

vmware: Fix ova vmdk size

---

.github/workflows/upload_to_s3.yml

This way, we only need one download step and the second step does not fail in case there are no platform-test logs uploaded by a previous workflow.
This PR is related to the error messages we see in https://github.com/gardenlinux/gardenlinux/issues/2328#issuecomment-2342921558.
These errors are actually expected as there are no platform-test logs for certain platforms. Currently a `continue-on-error: true` is build in for downloading the platform-test logs. This is working out but is a bit noisy.
This PR tries to get rid of those error messages by downloading all available artifacts for `*-${{ env.name}}`.
Fixes #2328
This pattern should work according to …

ci: use pattern to download build and platform-test artifacts

---

.github/workflows/build.yml
.github/workflows/publish_container.yml
.github/workflows/release-page.yml
.github/workflows/stig.yaml
.github/workflows/tests.yml
.github/workflows/upload_to_s3.yml

v3 is scheduled for deprecation on November 30, 2024
There are breaking changes:
- https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
- https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes
checked:
- We are not uploading to the same named Artifact multiple times.
- I think we do not have the use case of downloading artifacts that were created from action/upload-artifact@v3 and below are not supported.

ci: update actions/upload-artifact and actions/download-artifact to v4

---

features/_ignite/file.include/usr/lib/dracut/modules.d/30ignition-extra/after-net-online.conf
features/_ignite/file.include/usr/lib/dracut/modules.d/30ignition-extra/module-setup.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/99-any.conf
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/live-get-squashfs.sh
features/_pxe/file.include/usr/lib/dracut/modules.d/98gardenlinux-live/module-setup.sh

ignition-fetch.service is starting too soon with the default configuration, it should start after _network-online.target_
_systemd-networkd-wait-online.service_ should not start only if _/run/networkd/initrd/neednet_ exists[^1]
when fetching the squashfs, retry multiple times and retry on all errors
[^1]: https://github.com/dracut-ng/dracut-ng/blob/103/modules.d/01systemd-networkd/99-wait-online-dracut.conf#L3

Various pxe fixes

---

features/base/exec.config

sed inplace change in base exec.config messes up execute permissions, this restores them

fix: make /etc/update-motd.d/05-logo executable

---

features/_tpm2/exec.config
features/_tpm2/file.include/etc/repart.d/10-var.conf
features/_tpm2/file.include/etc/systemd/system-generators/detect-tpm
features/_tpm2/file.include/etc/systemd/system/check-tpm.service
features/_tpm2/file.include/etc/systemd/system/systemd-cryptsetup@var.service
features/_tpm2/file.include/etc/systemd/system/var.mount
features/_tpm2/file.include/usr/bin/check-tpm
features/_tpm2/info.yaml
features/_tpm2/pkg.include

provide an alternative implementation of mutable data handling for _trustedboot this uses a TPM 2.0 device to store the disk encryption secrets instead of using boot time random gen keys this allows for data to persist across reboots

feat: _tpm2

---

tests/platformSetup/kvm.py

Running KVM platform tests locally is currently broken.
- `~/.ssh` might not exists, `mkdir -p` fixes this.
- The no-watchdog flag was removed in #1948.
Related to #2304

fix kvm platform tests

---

.github/workflows/nightly.yml

The input `use_kms` is not set on sheduled `nightly` runs (not `workflow_dispatch`).
fixes #2356

make sure the `use_kms` input is always set

---

.github/labeler.yml

In #2302 the `tests/integration` dir was renamed `tests/platformSetup`, `.github/labeler.yml` references `tests/platform`, thoug.
Fixes #2336

fix labels after renamed dirs in #2302

---

.github/workflows/upload_to_s3.sh

- With https://github.com/gardenlinux/gardenlinux/pull/2308, the `gardenlinux_epoch` field ([ref](https://github.com/gardenlinux/gardenlinux/blob/cab0e41af85cc0812789972d078aaefa8a86d683/.github/workflows/upload_to_s3.sh#L26)) in the release manifests is no longer populated during the `nightly` jobs because the `garden-version` binary cannot be found ([ref](https://github.com/gardenlinux/gardenlinux/actions/runs/11027206393/job/30626455757#step:9:78)). This is probably because of changing the PWD [right here](https://github.com/gardenlinux/gardenlinux/blame/cab0e41af85cc0812789972d078aaefa8a86d683/.github/workflows/upload_to_s3.yml#L70).
- a possible fix is to add .`/bin` to `$PATH` to run `upload_to_s3.sh` from everywhere
**Which issue(s) this PR …

add .`/bin` to `$PATH` to run `upload_to_s3.sh` from everywhere

---

features/base/test/test_sgid_suid_files.py

`mount.nfs` is available on certain flavors/features and is another suid binary.
It is not yet allow-listed in `features/base/test/test_sgid_suid_files.py`.
Fixes #2375

features/base/test/test_sgid_suid_files: add mount.nfs

---

bin/.constants.sh
bin/garden-version

This moves some log outputs from stdout to stderr to give users some
information which binaries are missing when running the toolchain

chore: log errors correctly

---

cert/build

`./cert/build --container-engine docker` didn't worked since docker couldn't find the Containerfile
Fixes #2385
Nope
```feature user
NONE
```

better support docker build engine for cert building

---

build

includes fix for https://github.com/gardenlinux/seccomp_fake_xattr/issues/1

bump builder version

---

tests/tools/clean_orphans_aws.py

Allows to select the AWS region for clean_orphans_aws.py from the command line.
```feature user
Allows to select the AWS region for clean_orphans_aws.py from the command line.
```

Selectable region to clean_orphans_aws.py

---

README.md
docs/00_introduction/release.md

This is a follow up of https://github.com/gardenlinux/gardenlinux/pull/2410.
- The README itself still references LTS releases and this should be changed.
- The mermaid overview of current releases is a nice addition to the README.
- clarifications on nightly release download links (see also https://github.com/gardenlinux/gardenlinux/issues/2427)

adaptions and clarifications on releases in README

---

.github/workflows/platform-test-images.yml

This tries do address an issue where dependabot cannot write to the image registry.
Also we do not want to push to the registry on every push/pull_request, only after a successful merge to main.
This could fix #2431

do not always push platform test images

---

features/_pxe/file.include/etc/dracut.conf.d/30-omit-cdc-ether.conf

This is related to some ironcore issues.
When net booting, certain servers that don't have the Ethernet Over USB interface (used for in-band communication between the server and the BMC) disabled, this interface is going to get configured and it is going to make systemd consider the network as being online and certain services that require network will of course malfunction - e.q. fetching of the ignition config.

fix(pxe): cdc_ether should be omitted from the initrd

---

.github/workflows/release_note.py
hack/compare-apt-repo-versions.sh

Add a diff output to releases as we've done manually before.
Fixes #2295
Iideally this implementation would go in gardenlinux/python-gardenlinux-lib, but I wanted to keep the change simple. Moving this logic out is a potential refactoring item for later.
Instructions for testing locally:
Inside the gardenlinux repo, create a venv, install dependencies in that venv and run the script like this:
```bash
python3 -m venv venv
source venv/bin/activate
pip3 install --require-virtualenv requests boto3 pyyaml
```
Now you can run the script in *dry-run* mode:
```bash
python .github/workflows/release_note.py create --tag 1592.0 --commit 76203a3 --dry-run
python …
```

Automate diff output for release notes

---

features/gardener/file.include/etc/systemd/system/containerd.service.d/override.conf

With systemd version 256 the hard limits have been bumped to the kernel max allowed value.
Because containerd is using _LimitNOFILE=inifinity_ this is having a lot unforeseen effects and we'd like to keep the value to the value that has been used in Gardener so far - 2^20 - this has been agreed upon with @MrBatschner 
More info : [here](https://lists.debian.org/debian-devel/2024/06/msg00041.html) and https://github.com/containerd/containerd/commit/3ca39ef01608fdd44245c0173bf071682b3bfe3c

fix(gardener): keep LimitNOFILE same as old GL versions

---

features/_dev/pkg.include

dpkg-dev is needed for downloading the sources via `apt-get source` (at least for some packages), thus it should be available in dev images.

Add dpkg-dev package to _dev feature

---

.gitignore
bin/start-vm

Adds an optional parameter qcow=size to the start-vm image arguments. Providing this parameter will cause start-vm to create a copy-on-write file as an overlay of the input image and use that as a disk instead.
This has two uses:
1. Allows for testing images without modifying the build artifacts
2. Allows for simpler resizing of disk images during tests

feat: start-vm: add ability to create copy-on-write ephemeral disks

---

features/sap/file.include/etc/audit/rules.d/70-system-integrity.rules

In certain scenarios /lib64 symlink is missing, so till we have this fully figured out, we need to disable this rule.

fix: temporarily disable /lib64 audit rule

---

.github/workflows/upload_to_s3.yml

This PR is needed for the publication of container images to OCI.
The OCI upload workflow reads its artifacts from S3. I want to keep the workflow for container images and non-container images as similar as possible. If you ask yourself "Why are the artifacts not read directly from the workflow runs?", the answer is: this is only easily possible if your job is executed in the same workflow (like build and upload S3 are). When the upload OCI workflow is triggered nightly the intermediate step with S3 can be removed, but currently it is a good intermediate step because it makes artifacts "addressable". They can be downloaded with version number and commit.
Signed-off-by: Malte Münch <muench@b1-systems.de>

Upload container builds to S3 too

---

.github/workflows/release-page.yml

Currently an `exit 1` is thrown when a non existing platform test log file is uploaded in the release-page workflow.
This tries to fix it.
* https://github.com/gardenlinux/gardenlinux/actions/runs/11930076105/job/33250190914#step:6:121
* Could not test this. Test release will be done after merge.
* needs not backporting

ci: release-page - fix platform test upload error code

---

.github/workflows/upload_to_s3.yml

After testing the gcp_trustedboot_tpm2 images there is no upload. Seems that this slipped through.
`rel-1592` seems not to have trustedboot at all, so I will not backport this.

publish gcp_trustedboot_tpm2 on S3

---

.github/workflows/release_note.py
.gitignore

**What this PR does / why we need it**: Adds azure community gallery images to the release notes automation
Should look like this in the release page:
Relates to [#2488](https://github.com/gardenlinux/gardenlinux/issues/2488)

Take care of community gallery images for azure in release notes

---

features/khost/exec.late

This PR bumps k8s deb repository to `1.30` and installs `kubelet`, `kubectl` and `kubeadm` in v1.30.7.
Related https://github.com/gardenlinux/gardenlinux-ccloud/pull/14

Bump k8s version to 1.30.7 for `khost`

---

features/ssh/file.include/etc/systemd/system-preset/00-sshsocket-disable.preset

Disable the socket activation mechanism for SSH.
Fixes #2507

fix: disable ssh.socket

---

features/_usi/exec.config
features/_usi/exec.post
features/_usi/file.exclude
features/_usi/file.include/etc/systemd/system/home.mount
features/_usi/file.include/etc/systemd/system/opt.mount
features/_usi/file.include/etc/systemd/system/root.mount

Using bind mounts instead of symlinks allows changing them dynamically without having to modify the immutable EROFS.
This will also allow making the set of persistent locations run-time configurable in the future.
With this the new mounts look like:
```
/efi /dev/vda1 vfat rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro
/var /dev/mapper/var ext4 rw,relatime,seclabel
/etc overlay overlay rw,relatime,seclabel,lowerdir=/etc,upperdir=/var/etc.overlay,workdir=/var/etc.overlay.workdir,uuid=on
/opt /dev/mapper/var[/opt] ext4 rw,relatime,seclabel
/root /dev/mapper/var[/root] ext4 rw,relatime,seclabel
/home /dev/mapper/var[/home] ext4 rw,relatime,seclabel
```
Fixes #2508 …

feat: usi: use bind mounts for /opt /root /home instead of symlinks

---

flavors.yaml

Since merging #2514 the container flavor has some false features enabled and it cannot be published anymore:
https://github.com/gardenlinux/gardenlinux/actions/runs/12157353271/job/33910257296

fix container flavor

---

features/server/file.include/etc/sysctl.d/90-allow-ping-for-non-root-user.conf

We should allow non root users to use ping.
We need to do this since the needed capabilities are no longer added to _/usr/bin/ping_ via the Debian package post install script.
Fixes #

fix: add kernel parameter to allow ping for non root users

---

features/azure/file.include/etc/systemd/system/chronyd.service.d/10-after_dev-ptp_hyperv.device.conf
tests/helper/sshclient.py
tests/helper/utils.py
tests/platformSetup/gcp.py

- adds [tests/helper/utils.py: debugging in wait_systemd_boot](https://github.com/gardenlinux/gardenlinux/commit/93f177452afde9533ed779dc52a02206d2f91274)
- azure: adds systemd dependency to make sure PTP clocksource is available on azure (https://learn.microsoft.com/en-us/azure/virtual-machines/linux/time-sync#check-for-ptp-clock-source)
- gcp: increases wait for vm timeout to 10m
- general: if ssh banner cannot be decoded, retry
Fixes #2538
- successful nightly run: https://github.com/gardenlinux/gardenlinux/actions/runs/12279315300
- Needs no backports so far.

fix azure chronyd start and gcp ssh timeouts

---

.github/workflows/ali_tests.sh
.github/workflows/aws_tests.sh
.github/workflows/azure_tests.sh
.github/workflows/gcp_tests.sh
.github/workflows/gcp_trustedboot_tests.sh
.github/workflows/gcp_trustedboot_tpm2_tests.sh
.github/workflows/nightly.yml
.github/workflows/platform-test-images.yml
.github/workflows/tests.yml
tests/images/Makefile
tests/images/platform-test-base/Containerfile
tests/images/platform-test/ali/Containerfile
tests/images/platform-test/aws/Containerfile
tests/images/platform-test/azure/Containerfile
tests/images/platform-test/firecracker/Containerfile
tests/images/platform-test/gcp/Containerfile
tests/images/platform-test/kvm/Containerfile
tests/images/platform-test/openstack/Containerfile

Currently the latest release stable patch version of gardenlinux, e.g. `1592.4` is used as base for building platform-test images. This is not very flexible if we need to add new dependencies. From a security perspective @gehoern also made the point that it makes more sense to test with the latest code.
This PR changes the build input for the platform-test images to be the latest successful nightly (`ghcr.io/gardenlinux/gardenlinux:nightly`). It also publishes the platform-test images with the `nightly` tag (in the nightly run).
Fixes #2433
- successfull nightly run with changes: https://github.com/gardenlinux/gardenlinux/actions/runs/12278779208
- Needs …

use nightly as base for platform-test images

---

tests/helper/sshclient.py

We have connection issues in our platform tests. These come up at random which indicated that the VM might sometimes take longer to boot, define autorized_keys, ..., be available for connect.
This changes the behavior to retry in this cases.
Fixes #2547

fix  platform-tests: paramiko.ssh_exception.SSHException: Error reading SSH protocol banner

---

features/_usi/exec.post
features/_usi/pkg.include

install gardenlinux-update in _usi feature and write OCI public key to location expected by it
Fixes #2458

feat: enable in-place updates

---

tests/helper/sshclient.py

The changes to `helper.sshclient` in tests mainly focus on improving existing connection creation and adding optional enviroment variables to overwrite the hard coded defaults used until now.
Fixes #2552
The addition of environment variables are not applied anywhere so far. The same timeouts, retry count and wait seconds are applied by default even after the change.

Improve connection handling of `helper.sshclient` for tests

---

.github/workflows/azure_tests.sh

This PR increases the (currently default) 15 seconds retry wait time to 30 seconds for azure platform tests.
Fixes: #2552

Increase retry wait time for azure platform tests

---

.github/workflows/azure_tests.sh

This PR ensures that the defined retry wait second value is used for azure exporting it to the session Python will run on.
Fixes #2552

Ensure the defined retry wait second value is used for azure

---

features/azure/file.include/etc/systemd/system/chronyd.service.d/10-after_dev-ptp_hyperv.device.conf
features/azure/file.include/etc/udev/rules.d/60-hyperv-ptp.rules

This PR uses systemd's `BindTo` directive for `chronyd.service` as well as `chronyd-restricted.service`. Based on systemd that means:
> Configures requirement dependencies, very similar in style to Requires=. However, this dependency type is stronger: in addition to the effect of Requires= it declares that if the unit bound to is stopped, this unit will be stopped too. This means a unit bound to another unit that suddenly enters inactive state will be stopped too. Units can suddenly, unexpectedly enter inactive state for different reasons: the main process of a service unit might terminate on its own choice, the backing device of a device unit might be unplugged or the mount point of a mount unit might be unmounted without involvement of the system …

Ensure `/dev/ptp_hyperv` systemd unit is in active state for chrony

---

features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d
features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d/10-after_dev-ptp_hyperv.device.conf

After another appearance of the error `Starting chronyd-restricted.service - NTP client (restricted)... Could not open /dev/ptp_hyperv : No such file or directory` it was found that `chronyd-restricted.service.d` was never applied because it is a symlink. systemd expect drop-in files to be placed in directories. Linking individual drop-in files is supported while analysis shows that symlinking directories does not (for systemd 257).
If directories are symlinked `systemctl cat chronyd-restricted` only outputs the original unit. Symlinking the drop-in file results in the expected output of the drop-in file as well.
Fixes #2562
Fixes #2565

Ensure systemd detects drop-in files in `chronyd-restricted` for azure

---

features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d/05-private-devices-access.conf

This PR is an additional attempt to fix the issue `Starting chronyd-restricted.service - NTP client (restricted)... Could not open /dev/ptp_hyperv : No such file or directory`. Beside the fixes introduced in #2563 and #2566 the following setting is used in the default systemd unit: `PrivateDevices=yes`
`PrivateDevices=yes` means:
```
If true, sets up a new /dev/ mount for the executed processes and only adds API pseudo devices such as /dev/null, /dev/zero or /dev/random (as well as the pseudo TTY subsystem) to it, but no physical devices such as /dev/sda, system memory /dev/mem, system ports /dev/port and others. This is useful to turn off physical device access by the executed process.
```
Instead we would like to restrict access to pseudo devices …

Allow access to `ptp_hyperv` for `chronyd-restricted.service`

---

features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d/05-private-devices-access.conf

This PR is a follow-up of #2570 to ensure `rw` access is configured for `chronyd-restricted`.

Allow `rw` access to `/dev/ptp_hyperv` for `chronyd-restricted`

---

features/azure/file.include/etc/udev/rules.d/60-hyperv-ptp.rules

This PR tries to fix `Starting chronyd-restricted.service - NTP client (restricted)... Could not open /dev/ptp_hyperv : Permission denied` by granting access to `/dev/ptp_hyperv` to the group `_chrony`. PTP devices usually are accessible by `root` only and use mode `0600`. As stated in the original `chronyd-restricted.service` file it `... cannot use reference clocks, HW timestamping, RTC tracking, and other features.`. As we are interested in allowing access to a device this requires changes to the udev rule as well.

Allow access for group `_chrony` to access symlinked `/dev/ptp_hyperv`

---

features/azure/file.include/etc/systemd/system-preset/00-chrony-disable.preset
features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d/05-private-devices-access.conf
features/azure/file.include/etc/systemd/system/chronyd-restricted.service.d/10-after_dev-ptp_hyperv.device.conf
features/azure/file.include/etc/udev/rules.d/60-hyperv-ptp.rules

Only _chrony.service_ should be enabled.
Fixes #2576

fix: only chrony.service should run

---

features/base/exec.config

The removed code marks some packages as 'manually installed' as described in #1305.
This now breaks the build as some of those packages are not in the repo anymore.
This code was a workaround for an issue with debootstrap in 2022, I don't think we need this anymore, so we can remove it to make the build work again.
Fixes #2579

Remove mark manual for packages not in the repo

---

.github/workflows/upload_oci.yml

Closes https://github.com/gardenlinux/gardenlinux/issues/2551
The previous version of glcli was only able to apply the `mediaType` to new indexes, not update existing ones, which we need as [workflows/publish_container.yml](https://github.com/gardenlinux/gardenlinux/blob/main/.github/workflows/publish_container.yml) is actually writing to the OCI registry first before glcli uploads the rest.

Bump glcli version

---

hack/list-package-releases.sh

This is useful for finding outdated pinned versions in our package repo.

hack: add script to list package releases

---

tests/tools/clean_orphans_gcp.py

- Currently GCP subnets are not deleted before the actual network is deleted.
- Add option `A` to interactive mode to delete ALL resources that are found.

Fix GCP platform-test resource cleanup

---

.github/workflows/upload_to_s3.yml

no need to use 64 core, just need some runner not using the default runner ip addr range to avoid issues with upload to S3 china.

ci: use special upload runner instead of 64 core

---

tests/Containerfile

replaces pipenv install with pipenv sync, it is needed to only use lock file to install dependencies during tests, otherwise building testing container image might often fail, please see https://stackoverflow.com/a/53489664
Fixes #
```other developer
```

Use pipenv sync instead of install

---

bin/find-build-container-for
requirements.txt

This script might make it a bit more easy to maintain backports of packages, when needed.

Add utility script to find the correct build container for Garden Linux releases

---

features/base/exec.config

This improves general information displayed by systemd about the OS by
adding `VARIANT` and `VARIANT_ID` to the os-release file.
Details about the variables can be found in https://www.freedesktop.org/software/systemd/man/latest/os-release.html#VARIANT=

feat: improved os-release file

---

.github/workflows/release_note.py

Get list of fixed CVEs, grouped by upgraded package.
This automates some of the work needed when a new release is done.
Note that the output is known to be not perfect, it depends on the data available in glvd. Manual editing of the output is anticipated, but it should still reduce the manual effort needed on creating a new release.
Fixes https://github.com/gardenlinux/gardenlinux/issues/2653
Example output:
The following packages have been upgraded, to address the mentioned CVEs:
- upgrade 'jinja2' from `3.1.3-1` to `3.1.5-1gl0`
- CVE-2024-34064, CVE-2024-56201, CVE-2024-56326
- upgrade 'rsync' from `3.3.0-1` to `3.3.0+ds1-4gl0~bp1592`
- CVE-2024-12084, CVE-2024-12085, CVE-2024-12086, CVE-2024-12087, …

Automate package upgrade release notes using glvd

---

features/base/test/test_basics.py
tests/pytest.ini

This reverts commit ae4610dafd7e62020bfe820a91928b849a728900.
Looks like the added test is broken when run in the platform tests; likely running with different permissions when running platform tests vs chroot tests.
```
=================================== FAILURES ===================================
__________________________ test_gl_is_support_distro ___________________________
client = <helper.sshclient.RemoteClient object at 0x7feef08abe30>
@pytest.mark.security_id(1)
def test_gl_is_support_distro(client):
"""
This tests ensures that the vendor field is set to 'gardenlinux'.
"""
>       AptUpdate(client)
client     = <helper.sshclient.RemoteClient object at 0x7feef08abe30>
../features/base/test/test_basics.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```

Revert "Feature/test for support disto (#2654)"

---

features/base/test/test_basics.py

The `tolerated_kernel_time` in this test is actually the sum of kernel time + initrd time. Since #2591 the initrd is doing a lot more work on first boot, so this needs to be bumped up
#2661

fix: bump kernel time to work with _usi

---

tests/images/platform-test-base/Containerfile

Python 3.13 is the current version in debian trixie and the maintained version of python in Garden Linux today.

Upgrade python to 3.13 in platform tests

---

.github/workflows/platform-test-images.yml
.github/workflows/tests.yml

After the OpenTofu merge in https://github.com/gardenlinux/gardenlinux/pull/2543/ our nightly still builds platform-test-images for other platforms than tofu. This is not needed anymore and will be disabled by default by this PR.

build only tofu platform-test-images in nightly

---

.github/workflows/nightly.yml
.github/workflows/release-page.yml
.github/workflows/tests.yml

https://github.com/gardenlinux/glrd/pull/2 renamed some fields that need updating in our workflows.

bump glrd version to be compatible with v2 syntax

---

tests/platformSetup/Makefile

convert UUIDs to lowercase
`uuidgen` creates uppercase UUIDs on MacOs
Fixes #2622

platform-tests: convert UUIDs to lowercase on macos

---

.github/workflows/tests.yml

Right now if some of the tests have the result "failure" the job fails (which is ok) but the artifacts as in the pytest test log is not being uploaded. For the compliance reporting it would be good to keep those artifacts to then do reporting on them.
This PR is supposed to upload the test result log files independently of the test results themselves.
Fixes #
```feature user
```

Always upload test artifacts

---

.github/workflows/tests.yml

see: https://github.com/gardenlinux/gardenlinux/actions/runs/13265100948/job/37031786164
the test artifact upload step is still skipped
Fixes #
```feature user
```

change the behavior once more, the step to upload artifacts still gets skipped after a test failure

---

.github/workflows/tests.yml

platform-test logs are not named with a cname but a combination of $FLAVOR-$ARCH
This PR fixes this in the GithubActions.
This is a change introduced with https://github.com/gardenlinux/gardenlinux/pull/2543
https://github.com/gardenlinux/gardenlinux/blob/e033a4ea8aa4df50123e77960df32f7b049ba418/tests/Makefile#L56C215-L56C216

platform-test logs are not named with a cname but a combination of $FLAVOR-$ARCH

---

features/base/test/test_time_config.py
tests/Pipfile
tests/Pipfile.lock

This PR adds support to add a wrapper around tests to retry them for a specified amount of times if a given list of exceptions occurs. This is used for `base/test/test_time_config.py::test_ntp` and may be added for other tests as required.

Add generic support to retry failing tests

---

.github/workflows/build.yml
.github/workflows/upload_oci.yml

Include certs in build artifacts uploaded to S3 => GLCI can fetch from there rather then having to lookup corresponding git commit.
Resolves #2692 
Requires https://github.com/gardenlinux/python-gardenlinux-cli/pull/49

feat: include certs in build artifacts

---

features/base/test/test_password_shadow.py
tests/helper/tests/capabilities.py
tests/pytest.ini

In some cases the tests are being run by an unprivileged user. In those cases we need to run the commands with sudo. In other cases, sudo doesn't exist on the system. In those cases we must run the command with sudo.
Nightly on this branch looks promising: https://github.com/gardenlinux/gardenlinux/actions/runs/13313736886
Minor sneak in changes:
- the pytest.ini now contains -vvv as additional argument which shouldn't make a huge difference if the tests pass but in case they don't it can help to see the errors more clearly.
- [tests/helper/tests/capabilities.py](https://github.com/gardenlinux/gardenlinux/pull/2714/files#diff-4c8e94db6da1afedbf8da96c36123aff6d6f8c93275b6c30f9012c614aa7b0d0) now doesn't fail any longer in some cases in which "match" …

Fix broken nightly by fixing the test shadow password test

---

.github/workflows/tests.yml

fixes #2721
similar to PR for main branch: #2738
enables platform tests for arm64 on azure

enable arm64 azure platformtests for 1443

---

.github/workflows/nightly.yml

Add option to skip upload. Useful to test only platform tests from branches without permissions to write to S3.

feat: add skip_upload option to nightly workflow

---

.github/workflows/tests.yml

enable arm64 platform tests on azure 
for main branch: https://github.com/gardenlinux/gardenlinux/pull/2738
for rel-1443 branch: https://github.com/gardenlinux/gardenlinux/pull/2739
Fixes #2721

enable arm64 azure platform tests

---

.github/workflows/upload_oci.yml

Implements retry logic for **502 Bad Gateway** errors on GHCR upload. After 3 unsuccessful retries the action should then terminate.

Add auto rerun on GHCR upload

---

features/_slim/exec.late
features/_slim/file.exclude

The copyright files from _/usr/share/doc_ should not be excluded.
Fixes #2677

fix: do not exclude copyright files

---

.github/workflows/tests-only.yml

The version to build/tests images in the `tests-only.yml` workflow is set inconstantly.
This PR sets it to the nightly version by setting `version: now`.
https://github.com/gardenlinux/gardenlinux/actions/runs/13493390858 is a successful run started with:
```
gh workflow run "platform tests only" -f build=true --ref fix/2759 -f flavors_parse_params='--no-arch --json-by-arch --test-platform --include-only gcp-gardener_prod-amd64'
```
Fixes #2756

set nightly/now version in tests-only

---

.github/workflows/release_note.py

Output this style of markdown for the release notes:
Fixes https://github.com/gardenlinux/gardenlinux/issues/2777
```
The following packages have been upgraded, to address the mentioned CVEs:
- upgrade 'jinja2' from `3.1.3-1` to `3.1.5-1gl0`
- CVE-2024-34064
- CVE-2024-56201
- CVE-2024-56326
- upgrade 'rsync' from `3.3.0-1` to `3.3.0+ds1-4gl0~bp1592`
- CVE-2024-12084
- CVE-2024-12085
- CVE-2024-12086
- CVE-2024-12087
- CVE-2024-12088
- CVE-2024-12747
- upgrade 'curl' from `8.11.0-1gl0` to `8.11.1-1gl0`
- CVE-2024-11053
- upgrade 'python3.12' from `3.12.7-1gl1~bp1592` to `3.12.8-5gl0~bp1592`
- CVE-2024-12254
- CVE-2024-9287
```

Change format of CVEs in release notes to long-list style

---

features/_usi/image.esp.tar

Since https://github.com/dracut-ng/dracut-ng/pull/921 this is no longer automatically included
Fixes #2824
- => would only be needed if we plan to backport new dracut

fix: _usi: explicitly include systemd-cryptsetup dracut module

---

tests/platformSetup/tofu/variables.tf

Currently our Alibaba Cloud related platform tests are failing.
Switching the region from Frankfurt `eu-central-1` to London `eu-west-1` as this regions seems more stable at the moment.

switch ali region to eu-west-1

---

.github/workflows/upload_oci.yml

Addresses https://github.com/gardenlinux/gardenlinux/issues/2585
- Combine command execution and success check in conditional
- Exit immediately on successful push instead of breaking loop
- Remove redundant exit code checks for cleaner error handling
Thanks @5kt

Fix OCI upload retry logic for 502s

---

.github/workflows/release_note.py

This reverts commit 31608d701a178cbec7d7c3c45ec1429317a23ef9.
Revert until https://github.com/gardenlinux/glvd/issues/147 is implemented, because the feature is broken in its current state, and resolving it is not trivial and might not be done by the time we have a new release.

Revert "Automate package upgrade release notes using glvd (#2662)"

---

.github/workflows/platform-test-images.yml
.github/workflows/tests.yml

This was missed in https://github.com/gardenlinux/gardenlinux/pull/2835.
It enabled the build of platform test images in our nightly workflow.

define defaults for platform-test-images build/push in nightly

---

.github/workflows/platform-test-cleanup.yml
tests/platformSetup/tofu/modules/azure/main.tf

This adds a scheduled workflow that runs before our nightly and deletes all platform test resources that were built up with OpenTofu and are older than 1 day.
Fixes #2853
https://github.com/gardenlinux/gardenlinux/actions/runs/13840698510, https://github.com/gardenlinux/gardenlinux/actions/runs/13840763370 contain runs that deleted orphaned resources.

cleanup 1day old platform test resources via schedule

---

.github/workflows/build.yml
.github/workflows/tests.yml

This PR adds support for symlinked `cert` directories like used for [`gardenlinux-ccloud`](https://github.com/gardenlinux/gardenlinux-ccloud).
Fixes https://github.com/gardenlinux/gardenlinux-ccloud/issues/42

Use different path pattern for caching certificates

---

tests/platformSetup/Makefile

Fix path to generated login script for tofu platform test targets.

fix login to tofu platform test targets

---

features/chost/pkg.include

After discussing with @gehoern it was decided to remove _rootlesskit_ from the _chost_ feature.
At the moment nobody using this feature really needs the functionality provided by _rootlesskit_.

feat: remove rootlesskit from chost

---

.github/workflows/publish_container.yml

Building `kmodbuild_container` takes very long as it is not parallelized per architecture and does not use native builders.
https://github.com/gardenlinux/gardenlinux/actions/runs/13950195229 is a nightly run where this was tested successfully.

native and parallel build of kmodbuild_container

---

.github/workflows/build_platform_test_images.yml

This PR fixes an issue with GitHub workflow `build_platform_test_images.yml` trying to use the non-existent `archs` matrix.

Fix GitHub workflow trying to access non-existent `archs` matrix

---

.github/workflows/manual_tests.yml

This partly reverts add separated support for bare flavors if downloaded from S3 as they are not published there.

Remove bare flavors support from manual tests if downloaded from S3

---

.github/workflows/tests.yml

Another issue has been found with the alternative support in GitHub workflow `manual_tests.yml` with downloading S3 flavors. `tests.yml` was expecting input `bare_flavors_matrix`. It will be optional after merge.

Make GitHub workflow `tests.yml` input `bare_flavors_matrix` optional

---

.github/workflows/test_platform_flavor.yml

This PR fixes the key used to access the `test_platform_container` cache key in GitHub workflow `test_platform_flavor.yml`.

Fix the GitHub workflow platform-test container cache key used

---

.github/workflows/github.mjs
.github/workflows/platform_test_cleanup.yml
.github/workflows/test_platform_flavor.yml

This reverts commit 0e563240cf3c81b957ecf79d945015c50d856f63. While logging in to cloud providers only needed for a specific execution would improve stability as dependencies to external API endpoints are reduced our test implementation currently requires all providers to have access credentials.

Revert "Log in only to the cloud provider required ..."

---

.github/workflows/platform_test_cleanup.yml
.github/workflows/test_platform_flavor.yml

This one-liner imports `path` missing in `platform_test_cleanup.yml` and `test_platform_flavor.yml` GitHub workflows.

Fix missing import of `path` in GitHub workflow to login to GCP

---

.github/workflows/manual_release.yml
.github/workflows/nightly.yml
.github/workflows/publish.yml
.github/workflows/publish_s3.yml

This PR fixes the use of GitHub workflow variables to identify the branch to use for `main` as well.

Correctly read the git ref for branches as well as for `main`

---

.github/workflows/publish_oci_containers.yml

This PR removes `echo` spurious statements from restructuring the Github workflow `publish_oci_containers.yml`.

Remove `echo` spurious statements in workflow `publish_oci_containers`

---

.github/workflows/build.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/dev.yml
.github/workflows/publish_kmodbuild_container.yml

This PR changes the way GitHub workflows create the kmodbuild container by reusing the build one instead of downloading.

Reuse GitHub workflow build container for the kmodbuild container

---

.github/workflows/publish_s3.yml

This PR allows GitHub workflow `publish_s3.yml` to create releases in GLRD without tagging it as `nightly` if not executed on `main`.

Only skip tagging as `nightly` on `main` in GitHub workflow `publish_s3.yml`

---

features/gardener/exec.config

As the package google-compute-engine contains sysctls that turn on rp_filter on all interfaces which can interfere with CNI plugins, these lines have to be removed again in the Gardener feature.

Disable rp_filter in Gardener feature on GCP

---

.github/workflows/build_kmodbuild_container.yml
.github/workflows/manual_release.yml
.github/workflows/nightly.yml
.github/workflows/publish.yml
.github/workflows/publish_s3.yml

This PR fixes some statements used in GitHub workflows:
- It removes `always()` from `manual_release.yml`, `nightly.yml`, `publish.yml`, and `publish_s3.yml` as based on [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#always) it evaluates to true only for successful or canceled jobs.
- It removes `fail-on-cache-miss: true` from `build_kmodbuild_container.yml` as this prevents conditional execution afterwards

Cleanup various GitHub workflow statements

---

.github/workflows/build.yml

This PR changes how `outputs.use_kms` are used as `inputs.use_kms` later on to fix the evaluation of boolean.

Fix handling of `inputs` as `outputs` in GitHub reusable workflows

---

.github/workflows/publish_s3.yml

This PR adds missing inputs to job `upload_to_s3_cn` in GitHub workflow `publish_s3.yml`.

Adds missing inputs to job in GitHub workflow `publish_s3.yml`

---

.github/workflows/build.yml
.github/workflows/manual_release.yml

This PR synchronizes the flavors parse params used to create a release with the ones from `nightly`.

Synchronize flavors between nightly and release

---

.github/workflows/publish_s3.yml

This PR changes the GitHub workflow `publish_s3.yml` to access the right source for the flavors matrix required.

Use correct matrix source for GitHub workflow

---

.github/workflows/platform_test_cleanup.yml
.github/workflows/test_platform_flavor.yml

This PR fixes the access to the structure where alicloud credentials are stored in the secret for GitHub workflows.

Fix access to alicloud access credentials in GitHub workflows

---

.github/workflows/publish_s3.yml

This PR adds the missing `needs` declaration for job `prepare_certs` of the GitHub workflow `publish_s3.yml` to correctly access the output of it.

Add missing `needs` to job `prepare_certs` in GitHub workflow `publish_s3.yml`

---

.github/workflows/publish_oci_containers.yml

This PR fixes the environment variable names used in GitHub workflow `publish_oci_containers.yml`.

Fix environment variable names used in `publish_oci_containers.yml`

---

.github/workflows/manual_gh_release_page.yml
.github/workflows/release_note.py

Add new Release to glvd before creating release page, and use the glvd api to get a list of upgraded packages and fixed CVE.
Fixes https://github.com/gardenlinux/glvd/issues/147
Note to reviewer: This can't be properly tested on a pr branch, we'll have to see how well it works in main

Create package diff using glvd for release notes

---

.github/workflows/publish_s3.yml

This PR updates GLRD action to v3 and uses the provided `--version` and `--commit` parameters to create releases based on the given information.
Fixes #2923

Fix GLRD creating wrong nightly releases under certain circumstances

---

.github/workflows/publish.yml
.github/workflows/publish_oci_containers.yml

This PR work around an issue with caching being non-transactional in the GitHub workflow `publish_s3.yml`. Instead of running the whole push to ghcr.io linear we can push OCI images concurrently but only aggregate the results afterwards in a linear way for the OCI manifest to be created for all flavors in the last job.
Fixes #2924

Execute OCI image pushes concurrently

---

.github/workflows/publish_s3.yml

This PR reads the Git hash for the (known) short commit ID for calling `glrd`.

Read the Git hash for short commit ID in GitHub workflow `publish_s3.yml`

---

.github/workflows/publish_s3.yml

This PR fixes an issue in GitHub workflow `publish_s3.yml`:
```
fatal: ambiguous argument '<short rev>': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
```
While not occured locally the Ubuntu variant seems to be more restrictive regarding command line parameters.

Fix "ambiguous argument" in GitHub workflow executed `git` for `publish_s3.yml`

---

.github/workflows/publish_oci_containers.yml
.github/workflows/publish_s3.yml

This PR renames the cache keys for updateable caches to align with how `restore-keys` are implemented but unclear documented in GitHub workflow `publish_oci_containers.yml`.

Fix correct use of cache restore keys

---

tests/images/Makefile

`arm64` or `aarch64` should both resolve to `arm64` in this case. 
`uname -m` on osx returns `arm64`, which would result in an empty `TARGETARCH` variable during building , since no existing conditions are met. 
**Reproduce**:  
```
make --directory=tests/images build-platform-test
```

fix: support arm64 machine hardware type for platform-test images

---

features/base/test/test_time_config.py
tests/conftests/platforms.py

The test
base/test/test_time_config.py::test_clocksource
will fail with
AssertionError: unknown hypervisor qemu
This happens because systemd-detect-virt will output "qemu" in case we start tests via qemu target, e.g.:
make --directory=tests aws-gardener_prod-amd64-qemu-test-platform
In order to exclude this test for this test target, we need to add new fixtures for "qemu" iaas. As defined in [tests/conftest.py::testconfig](https://github.com/gardenlinux/gardenlinux/blob/d659d9bc8a843ae1ba49bbff9fb2e14a826fd6b8/tests/conftest.py#L173), iaas can be set to qemu.
This commit adds:
- fixtures to exclude/include qemu iaas
- excludes test_time_config.py::test_clocksource for qemu platform

fix test: disable test_clocksource on qemu without kvm support

---

.github/workflows/build_kmodbuild_container.yml
.github/workflows/build_requirements.yml

This PR switches the value of commit ID to long `git` hashes (again). While most scripts in GardenLinux works for both hash variants and Git support both as committish some processes expect long hashes to be used. Additionally the commit ID got mixed up previously in GitHub workflow for [testing](https://github.com/gardenlinux/gardenlinux/blob/b5c0e06b6ad0de14be247d15129999e2c385ffd8/.github/workflows/tests.yml#L116). Restore previous behavior of always providing the long commit hash.

Use long git hashes as commit ID input for GitHub workflows

---

.github/workflows/publish_oci_containers.yml

Added support for more file types. 
https://github.com/gardenlinux/python-gardenlinux-cli/releases/tag/0.6.4 required by @5kt  for CC.

update python-gardenlinux-cli to 0.6.4

---

.github/workflows/upload_to_s3.yml

This PR adjust the behavior of the upload to S3 GitHub action to leverage GitHub hosted runners
Based on the discussion in #2961 using the (free) GitHub hosted directly should work for upload to S3 for both normal AWS and AWS China. If this change should not be compatible we can try again with a more suffisticated fallback solution as discussed in #2961. 
Switching to the free GitHub hosted runners reduces the amount of paid GitHub Action minutes by roughly 200k minutes / 10 days (https://github.com/gardenlinux/gardenlinux/actions/metrics/usage). 
n/a
```other developer
Upload artifacts to S3 using free GitHub hosted runners
```

switch to free github-hosted runners for S3 upload

---

README.md
docs/01_developers/build_image.md

Feedback from new contributors shows that this part was too easy to miss, so making it a bit more explicit may help to avoid frustration.

Warn more explicitly about memory consumption of build process

---

features/lima/README.md
features/lima/convert.qcow2
features/lima/info.yaml
features/lima/pkg.include

This PR adds a `lima` feature that enables the resulting image to be usable with https://lima-vm.io
This is useful for a few reasons:
- lima takes care of creating a user, generating an ssh key and some other aspects that Garden Linux does not have its own tooling for
- This allows developers and interested externals to create Garden Linux virtual machines for testing, evaluation and similar purposes
Part of https://github.com/gardenlinux/gardenlinux/issues/2964

Allow building images suitable for use with lima-vm

---

images/kmodbuild/Containerfile

libdb in kmodbuild.
We download the package exclusion file from github.com/gardenlinux/repo main branch, and purge those packages that were installed.
We use main branch of gardenlinux/repo instead of dynamic inferred branch, since main branch will be most up-to-date and we can still build kmodbuild in feature branches.
Fixes #2988 
**Notes for reviewer** 
How to build this PR and verify 
```
version="1592.9"
base="ghcr.io/gardenlinux/gardenlinux:$version
snapshot="$(gh api "/repos/gardenlinux/repo/contents/.container?ref=$version" | jq -r '.content' | base64 -d)"
arch=<your favorite arch (or the one you have)>
podman build --arch $arch --build-arg base="$base" --build-arg snapshot="$snapshot" -t …
```

fix: purge packages based on repo exlusion list

---

.github/workflows/build.yml
.github/workflows/build_flavor.yml
.github/workflows/build_requirements.yml
.github/workflows/download_workflow_data.yml
.github/workflows/manual_release.yml
.github/workflows/manual_tests.yml
.github/workflows/nightly.yml
.github/workflows/publish.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/publish_s3.yml
.github/workflows/test_platform_flavor.yml

This PR is intended to support intended changes of #3016 with a streamlined variant of GardenLinux release targets. It requires less input and reuses the given additional information internally to calculate settings required for build and release steps.

Streamline GitHub workflow release target logic

---

.github/workflows/publish_s3.yml

This PR renames (moves) `secureboot` certificate files to be prefixed with the "cname". This restores the file names used before #2842.

Move `secureboot` files to be prefixed with "cname" before upload S3

---

.github/workflows/publish_s3.yml

This PR renames (moves) secureboot certificate files to be prefixed with the "cname". This restores the file names used before #2842. This PR (v2) fixes a typical Friday issue with committing an `echo mv` statement instead of the actual `mv`. ;)

Move secureboot files to be prefixed with "cname" before upload S3 (v2)

---

.github/workflows/publish_s3.yml

This PR takes `$CNAME` out of the `for` loop for moving `secureboot` certificate files. This ensures the file name is used correctly in the loop instead.

Fix `secureboot` file moves to not include directory names in `for` loop

---

features/multipath/file.include/etc/multipath.conf

Fixes issue on gardener, where `multipathd` accessing regular SCSI devices is interfering with `mke2fs` during persistent volume creation.

fix: multipath ignore everything except iscsi and nvme/tcp

---

.github/workflows/publish_oci_containers.yml

Bumps python-gardenlinux-cli for oci upload.
New features:
* Add initrd.unified - initrd containing the rootfs

update python-gardenlinux-cli to 0.6.5

---

.github/workflows/manual_gh_release_page.yml
.github/workflows/release_note.py

For the new major release, we have those additional variants. The 'traditional' image variants still exist because the new variants have certain restrictions so they can't satisfy all use-cases.
Fixes #3044

Include _usi and _tpm2_trustedboot variants in release page

---

.github/workflows/release_note.py

In the previous commit, I forgot to exclude _usi and _tpm2_trustedboot
Follow up for f55e91667158f7f39ab3b392e5ed557bd88015a7, #3050

Skip ali for _usi and _tpm2_trustedboot images

---

.github/workflows/manual_gh_release_page.yml
.github/workflows/release_note.py

should fix failing workflow run for rel-1592:
https://github.com/gardenlinux/gardenlinux/actions/runs/15341910973/job/43169784446
by allowing to run it with the new image_variants arg set to an empty string.

fix: make image_variants optional in release page action

---

.github/workflows/test_platform_flavor.yml

This PR fixes an issue with access to GitHub secrets for Azure that prevent "Platform Test Cleanup" to succeed.
Fixes #3066

Use the correct GitHub secrets to access the Azure cloud provider for "Platform Test Cleanup"

---

features/gardener/test/test_sysctls.py
tests/helper/tests/sysctl.py

For the Gardener feature, the sysctls `net.ipv4.conf.all.rp_filter` and `net.ipv4.conf.default.rp_filter` must not be set to `1` as it will interfere with CNI plugins like Calico or Cilium.
This test tests if those sysctls are set to 1 and will fail if so.
For this test to work, I created an new test helper `check_sysctl()`. Even though we already had a test helper `test_kernel_parameter()` (this name is utterly misleading btw), it is too inflexible as it only allows to test for a certain sysctl to be set to a certain value. With `check_sysctl()`, I introduced an operator with which it is possible to test wether a sysctl `is` a certain value, `isnot` a certain value, `isnotorisnotset` a certain value, `isset` but the value does not matter, …

test rp_filter in Gardener feature not set to 1

---

.github/workflows/upload_to_s3.sh
.github/workflows/upload_to_s3.yml

Our S3 uploads to China are currently taking ~12 hours.
Let's [Configure AWS S3 multipart upload](https://github.com/gardenlinux/gardenlinux/commit/8495196ad10b3f0d7fc19f006e92e334c8e0ef44) and see if this improves things.
Fixes https://github.com/gardenlinux/gardenlinux/issues/3087
**Special notes for reviewer**:
I confirmed in https://github.com/gardenlinux/gardenlinux/actions/runs/15467586915 to not break the non China S3 upload.

Configure AWS S3 multipart upload

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/download_workflow_data.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/publish_s3.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml

This PR bumps the `python-gardenlinux-lib` based GitHub actions to 0.7.1.
Fixes #3097

Bump `python-gardenlinux-lib` actions to 0.7.1

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/publish_s3.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml

This PR bumps the `python-gardenlinux-lib` based GitHub actions to 0.7.2. The new version is less restrictive in checking existing OCI image indices.
Fixes #3097

Bump `python-gardenlinux-lib` to 0.7.2

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/publish_s3.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml

This PR bumps the `python-gardenlinux-lib` based GitHub actions to 0.7.3. The new version further fixes issues in checking existing OCI image indices.
Fixes #3097

Bump `python-gardenlinux-lib` to 0.7.3

---

.github/workflows/publish_oci_containers.yml

This PR adds downloading the manifest cached earlier before trying to use it for upload.

Fix missing manifest download in `publish_oci_containers.yml`

---

.github/workflows/publish_s3.yml
.github/workflows/upload_to_s3.yml

This PR allows selectable test artifacts in GitHub workflow `publish_s3.yml` to handle flavor tests without a full test suite correctly.

Improve GitHub workflow `publish_s3.yml` to handle flavor tests correctly

---

.github/workflows/publish_s3.yml
.github/workflows/upload_to_s3.yml

This PR allows `publish_s3.yml` to complete successfully if `$CNAME` directory exists or has been already created in a previous step.

Allow `publish_s3.yml` to complete successfully if `$CNAME` directory exists

---

hack/glvd-search.sh

As discussed with @Vincinator it would be nice to have a `gl-search` like tool for glvd. This is a very first and rough draft for such a tool to browse vulnerabilities by Garden Linux versions.
TODO:

Add script to browse glvd data on the terminal with fuzzy search

---

.github/workflows/build_platform_test_images.yml

We should dynamically resolve `IMAGE_REGISTRY` to be compatible with https://github.com/gardenlinux/gardenlinux-ccloud.

dynamically resolve IMAGE_REGISTRY

---

tests/images/platform-test/tofu/.terraformrc

In OpenTofu remove provider overwrite for GCP since https://github.com/gardenlinux/gardenlinux/pull/3164 the upstream provider ist used.
Currently nightly.

tofu: remove provider overwrite for GCP

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml

Bump python-gardenlinux-lib (s3 artifact manifest modifiers from https://github.com/gardenlinux/python-gardenlinux-lib/pull/135).
This is a follow up of https://github.com/gardenlinux/gardenlinux/pull/3166. Where the `0.8.1` tag missed the actual bump in the actions that are called from `gardenlinux`:
https://github.com/gardenlinux/python-gardenlinux-lib/commit/ab3ba864b1ab0ed6566c7cb1a49114210c895db1

bump python-gardenlinux-lib (s3 artifact manifest modifiers) - 2nd try

---

features/lima/info.yaml
features/lima/pkg.include

The lima-vm image included a bunch of features that are probably not useful or needed in the lima use-case. This PR excludes some features to build smaller and more focussed images for the lima use-case.
Related to https://github.com/gardenlinux/gardenlinux/issues/2965

Reduce number of features included in 'lima' image

---

Pipfile
requirements.txt

Fix dependencies on `python-gardenlinux-lib` in `Pipefile` as it was renamed to `gardenlinux`.
`Pipfile` is not currently used anywhere and is just an alternative to `requirements.txt`.
`tests/Pipfile` cannot be bumped until https://github.com/gardenlinux/python-gardenlinux-lib/pull/132 is merged.

Fix dependencies on `python-gardenlinux-lib` in `Pipefile`

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml
Pipfile
requirements.txt

This PR bumps `python-gardenlinux-lib` to 0.8.5. The new version fixes an issue related to PXE file names not matching the extension but the full file name.
Fixes #3201

Bump `python-gardenlinux-lib` to 0.8.5

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml
Pipfile
requirements.txt

This PR bumps `python-gardenlinux-lib` to 0.8.6. This version fixes the handling of file names with directories for media-type lookups.
Fixes #3201

Bump `python-gardenlinux-lib` to 0.8.6

---

.github/workflows/cpe.yml

For some of our stakeholders, we need to provide a [CPE](https://nvd.nist.gov/products/cpe) within a release. This file needs to be encoded as a JSON file. In this PR, we add a workflow that allows us to 'predict' an entry CPE entry. This CPE file is incomplete but sufficient for our stakeholder. In a separate workflow, we will notify the NIST about a release; however, it takes several days or weeks until a proper CPE entry is updated by the NIST. With the prediction, we allow stakeholders to update their dataset and do not have to wait until the NIST has responded. 
The code responsible is placed in [here](https://github.com/gardenlinux/cpe/blob/main/predict-cpe.py). In this separate repository, which also builds the container.  
**Which issue(s) …

Add workflow for CPE

---

bin/start-vm
features/_fwcfg/exec.config
features/_fwcfg/file.include/etc/systemd/system/qemu-fw_cfg-script.service
features/_fwcfg/file.include/usr/bin/run-qemu-fw_cfg-script
features/_fwcfg/info.yaml
features/cloud/info.yaml
features/metal/info.yaml

This change will allow us to provide setup scripts (similar to the AWS user-data-script or equivalent on other cloud providers) while running in a VM under QEMU.
**Security considerations:**
While this at first glance appears to provide an easy attack surface / backdoor, we need to keep in mind that setting or spoofing such fw_cfg values would require an attacker to control the hypervisor and/or the firmware. Given an adversary with such capabilities it would also be possible for the attacker to directly modify system memory to modify / inject code into kernel space, so this fw_cfg based script execution does not provide such an attacker significant additional capabilites.

feat: add option to run VM configure script via QEMU fw_cfg

---

build

This builder update contains the following commits in the builder repo:
- [33391d8](https://github.com/gardenlinux/builder/commit/33391d8821ac62794512753879942fc2155f1965) Merge pull request #121 from gardenlinux/feat/output_requirements
- [1e349a9](https://github.com/gardenlinux/builder/commit/1e349a933b1e93d2d720719e64c97d4a5d0f57b9) feat: output target requirements
- [fd7a1a9](https://github.com/gardenlinux/builder/commit/fd7a1a9a0b739ca82632694128508c751727f490) This commit supports `$LOG_WITH_TIMESTAMP` to generate shorter log output
- [6c9fd2a](https://github.com/gardenlinux/builder/commit/6c9fd2a2f7a4f500ba8b30246dd1896f7df15382) Merge pull request #118 from gardenlinux/feat/download-aws-library
- [9e4f860](https://github.com/gardenlinux/builder/commit/9e4f860878aa4c87a66663975aa38d …

update builder to latest version

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml
Pipfile
requirements.txt

Bump python-gardenlinux-lib to 0.8.8
Not sure if this is related to https://github.com/gardenlinux/gardenlinux/actions/runs/16668198895/job/47179414305

Bump python-gardenlinux-lib to 0.8.8

---

.github/workflows/build_flavor.yml
.github/workflows/build_flavors_matrix.yml
.github/workflows/build_kmodbuild_container.yml
.github/workflows/download_flavors_images.yml
.github/workflows/publish_oci_containers.yml
.github/workflows/test_flavor_chrooted.yml
.github/workflows/test_platform_flavor.yml
.github/workflows/upload_to_s3.yml
Pipfile
requirements.txt

This PR bumps `python-gardenlinux-lib` to 0.8.9. This version generalizes mime type assignment for log files.

Bump `python-gardenlinux-lib` to 0.8.9

---

tests-ng/util/run.sh

to work with major.minor version string within artifact name

fix: extension parsing in test-ng run

---

tests-ng/plugins/sshd.py
tests-ng/plugins/systemd.py
tests-ng/plugins/utils.py
tests-ng/test_basics.py
tests-ng/test_ssh.py
tests-ng/util/run_cloud.sh

Convert test to assert desired properties are part of the sshd config.
Part of https://github.com/gardenlinux/gardenlinux/issues/3181

Port SSH tests to new framework

---

features/_pxe/image.pxe.tar.gz
features/_usi/image.esp.tar

```
[.build/kvm-gardener_prod_trustedboot-arm64-1962.0-adec8673.esp.tar 2025-08-14 07:03:13] dracut[I]: *** Creating initramfs image file '/initrd.tmp' done ***
[.build/kvm-gardener_prod_trustedboot-arm64-1962.0-adec8673.esp.tar 2025-08-14 07:03:13] dracut[I]: *** Moving image file '/initrd.tmp' to '/initrd' ***
[.build/kvm-gardener_prod_trustedboot-arm64-1962.0-adec8673.esp.tar 2025-08-14 07:03:13] mv: cannot move '/initrd.tmp' to '/initrd': Device or resource busy
[.build/kvm-gardener_prod_trustedboot-arm64-1962.0-adec8673.esp.tar 2025-08-14 07:03:13] rm: cannot remove '/initrd': Device or resource busy
[.build/kvm-gardener_prod_trustedboot-arm64-1962.0-adec8673.esp.tar 2025-08-14 07:03:13] dracut[F]: Move of /initrd failed
completed in 101 …
```

fix: dracut move of /initrd failed

---

tests-ng/README.md
tests-ng/plugins/booted.py
tests-ng/plugins/modify.py
tests-ng/plugins/shell.py
tests-ng/test_basics.py
tests-ng/test_ssh.py

This PR allows us to better keep track of the reason for certain markers. This field is optional, so for obvious cases it can be left empty, but I think in most cases it is actually useful to document the reasoning for setting a certain marker.
Fixes https://github.com/gardenlinux/gardenlinux/issues/3319

Enhance test markers to include optional 'reasons' argument

---

docs/01_developers/bare_container.md

Fixes https://github.com/gardenlinux/gardenlinux/issues/3313
The existing docs create confusion, see the linked issue

Fix docs for how to call python3 in bare container

---

README.md

We have OpenSSL Version 3.5 in 1877, and we have not shipped OpenSSL 3.0 since 1312.

Bump OpenSSL Version 3.5 in README

---

tests-ng/README.md
tests-ng/plugins/features.py
tests-ng/test_basics.py

Excludes the tests on features where the machine does not properly boot up in qemu for various reasons, such as backend systems that are required but not available 
This is okay because those features are not made for running in a plain qemu vm
Adds an optional 'reason' field to the 'features' fixture

Tests: Implement 'no failed units' testcase

---

tests-ng/test_basics.py

This would have helped us identify the issue fixed here https://github.com/gardenlinux/package-linux/commit/b52e5a9688c80c016ac13cb04702bf4f8103c9d4
This test case is new, suggested by @5kt based on issues with booting the kernel in secure boot mode

Test that kernel is not tainted

---

tests/platformSetup/tofu/modules/azure/main.tf

This PR fixes UEFI related keys for OpenTofu Azure v4.41.0 to reflect latest [proposed upstream changes](https://github.com/hashicorp/terraform-provider-azurerm/pull/28076).

Fix UEFI related keys for OpenTofu Azure

---

tests/platformSetup/tofu/modules/azure/main.tf

This reverts PR with commit 60baf2303167a6018704d50aa46366e2268b2ee7. The `depends_on` definition has already been added and seems to be not correctly detecting dependencies.

Revert "Define a created OpenTofu Azure NIC as a explicit dependency for the VM"

---

features/_usi/image.esp.tar
features/_usi/pkg.include

New systemd-boot comes with a newer EFI boot stub that no longer works correctly when using the older `ukify` utility in the builder container.
We could just bump the utility inside the builder, but long term it might be better to always use `ukify` from the chroot directly to ensure these don't run out of sync again.

fix: use ukify from chroot to restore compatibility with newer systemd

---

features/python/pkg.include

In PR we add the package [what-is-python](https://tracker.debian.org/pkg/what-is-python) that contains a symlink from python to python3. By default, we will install the binary package `python-is-python3` to the Python feature. You can invoke the Python binary via `/usr/bin/python` or just invoking `python`. 
Related to: #3313

Add the what-is-python package to the python feature.

---

.github/workflows/manual_gh_release_page.yml

Follow up of https://github.com/gardenlinux/gardenlinux/pull/3407 that fixes manual_gh_release_page.yml:
- fetch full history to find commit in release_note.py
This fixes #3406 and it's wrong checkout of files.

fix: in manual_gh_release_page.yml put flavors_matrix into own step - fetch full history to find commit in release_note.py

---

.github/workflows/manual_gh_release_page.yml
.github/workflows/release_note.py

Enable Github Release workflow to be tagged as latest.
Fixes #2895

enable latest flag in release_note.py

---

features/lima/README.md

Follow up for #3453, we don't depend on the kvm feature anymore

[no ci] fix readme of lima feature

---

.github/workflows/build.yml
.github/workflows/build_test_dist.yml
.github/workflows/manual_tests.yml
.github/workflows/tests.yml

This PR moves the `Build Test Distribution` workflow to the GitHub build workflow stage. Building and testing should be separated and isolated workflows for easier maintenance and separation of tasks.

Move "Test Distribution Build" to the correct GH workflow stage

---

.github/workflows/test_flavor_qemu.yml
tests-ng/README.md
tests-ng/util/run_qemu.sh

We noticed after merging https://github.com/gardenlinux/gardenlinux/pull/3481 that QEMU tests might fail but do not throw a correct error code.
This PR adds parsing the JUnit XML to get number of errors.
Fixes #3499

fix: test-ng: correctly detect errors in QEMU tests

---

.github/workflows/build_test_dist.yml
.github/workflows/github.mjs
.github/workflows/tests.yml

This PR moves the GitHub workflow test environment determination to a separate function. The advantage of this approach is a much more readable GitHub workflow definition for conditional execution.

Move GitHub workflow test environments determination to separate function

---

tests-ng/util/run_qemu.sh

We noticed after merging https://github.com/gardenlinux/gardenlinux/pull/3481 that QEMU tests might fail but do not throw a correct error code.
This PR adds parsing the JUnit XML to get number of errors and failures.
Follow up of https://github.com/gardenlinux/gardenlinux/pull/3500 that also catches "failures".

fix: test-ng: correctly detect errors and failures in QEMU tests

---

.github/workflows/tests.yml

This PR fixes an hidden dependency for `qemu` to execute `cloud` tests. This dependency has been introduced in #3481.

Fix hidden dependency for `qemu` to execute `cloud` tests

---

tests-ng/test_su.py

Migrate https://github.com/gardenlinux/gardenlinux/blob/main/features/base/test/test_su.py to the new testing framework.
Fixes #3526 
Refs #3181 

Migrate test_su

---

features/vhost/pkg.include

- Rename `libgoogle-perftools4` and `libtcmalloc-minimal4` to `libgoogle-perftools4t64` and `libtcmalloc-minimal4t64`
Fixes #3617

fix: rename packages in `vhost` `pkg.include`
